/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class AgentResponseDto {

    @JsonProperty("_id")
    private String id;


    @JsonProperty("name")
    private String name;


    @JsonProperty("identifier")
    private String identifier;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private String description;


    @JsonProperty("behavior")
    private AgentBehaviorDto behavior;


    @JsonProperty("active")
    private boolean active;

    /**
     * Production bridge URL
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bridgeUrl")
    private String bridgeUrl;

    /**
     * Development bridge URL (set by npx novu dev)
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("devBridgeUrl")
    private String devBridgeUrl;

    /**
     * Whether the dev bridge override is active
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("devBridgeActive")
    private Boolean devBridgeActive;

    /**
     * Whether the agent brain is self-hosted (bridge) or managed by a third-party provider
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("runtime")
    private AgentResponseDtoRuntime runtime;

    /**
     * Discovery scope of the agent. Always `public` today; reserved for the upcoming private-agents
     * feature.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("visibility")
    private Visibility visibility;

    /**
     * Present when runtime is "managed". Contains provider and external identifiers.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("managedRuntime")
    private ManagedRuntimeResponseDto managedRuntime;


    @JsonProperty("_environmentId")
    private String environmentId;


    @JsonProperty("_organizationId")
    private String organizationId;

    /**
     * Mongo user id of the user who created the agent
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("createdBy")
    private String createdBy;


    @JsonProperty("createdAt")
    private String createdAt;


    @JsonProperty("updatedAt")
    private String updatedAt;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("integrations")
    private List<AgentIntegrationSummaryDto> integrations;

    /**
     * Cloud only. `true` when the agent falls outside the organization plan agent limit (by creation order
     * among active agents — inactive agents do not consume slots). Only plan limits produce this flag —
     * system-capped organizations (enterprise/unlimited tiers) are never over-limit.
     * 
     * <p>Over-limit agents are still stored but will not respond to inbound messages until the plan is
     * upgraded or older agents are deactivated.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("exceedsPlanLimit")
    private Boolean exceedsPlanLimit;

    @JsonCreator
    public AgentResponseDto(
            @JsonProperty("_id") @Nonnull String id,
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("identifier") @Nonnull String identifier,
            @JsonProperty("description") @Nullable String description,
            @JsonProperty("behavior") @Nonnull AgentBehaviorDto behavior,
            @JsonProperty("active") boolean active,
            @JsonProperty("bridgeUrl") @Nullable String bridgeUrl,
            @JsonProperty("devBridgeUrl") @Nullable String devBridgeUrl,
            @JsonProperty("devBridgeActive") @Nullable Boolean devBridgeActive,
            @JsonProperty("runtime") @Nullable AgentResponseDtoRuntime runtime,
            @JsonProperty("visibility") @Nullable Visibility visibility,
            @JsonProperty("managedRuntime") @Nullable ManagedRuntimeResponseDto managedRuntime,
            @JsonProperty("_environmentId") @Nonnull String environmentId,
            @JsonProperty("_organizationId") @Nonnull String organizationId,
            @JsonProperty("createdBy") @Nullable String createdBy,
            @JsonProperty("createdAt") @Nonnull String createdAt,
            @JsonProperty("updatedAt") @Nonnull String updatedAt,
            @JsonProperty("integrations") @Nullable List<AgentIntegrationSummaryDto> integrations,
            @JsonProperty("exceedsPlanLimit") @Nullable Boolean exceedsPlanLimit) {
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.identifier = Optional.ofNullable(identifier)
            .orElseThrow(() -> new IllegalArgumentException("identifier cannot be null"));
        this.description = description;
        this.behavior = Optional.ofNullable(behavior)
            .orElseThrow(() -> new IllegalArgumentException("behavior cannot be null"));
        this.active = active;
        this.bridgeUrl = bridgeUrl;
        this.devBridgeUrl = devBridgeUrl;
        this.devBridgeActive = devBridgeActive;
        this.runtime = runtime;
        this.visibility = visibility;
        this.managedRuntime = managedRuntime;
        this.environmentId = Optional.ofNullable(environmentId)
            .orElseThrow(() -> new IllegalArgumentException("environmentId cannot be null"));
        this.organizationId = Optional.ofNullable(organizationId)
            .orElseThrow(() -> new IllegalArgumentException("organizationId cannot be null"));
        this.createdBy = createdBy;
        this.createdAt = Optional.ofNullable(createdAt)
            .orElseThrow(() -> new IllegalArgumentException("createdAt cannot be null"));
        this.updatedAt = Optional.ofNullable(updatedAt)
            .orElseThrow(() -> new IllegalArgumentException("updatedAt cannot be null"));
        this.integrations = integrations;
        this.exceedsPlanLimit = exceedsPlanLimit;
    }
    
    public AgentResponseDto(
            @Nonnull String id,
            @Nonnull String name,
            @Nonnull String identifier,
            @Nonnull AgentBehaviorDto behavior,
            boolean active,
            @Nonnull String environmentId,
            @Nonnull String organizationId,
            @Nonnull String createdAt,
            @Nonnull String updatedAt) {
        this(id, name, identifier,
            null, behavior, active,
            null, null, null,
            null, null, null,
            environmentId, organizationId, null,
            createdAt, updatedAt, null,
            null);
    }

    public String id() {
        return this.id;
    }

    public String name() {
        return this.name;
    }

    public String identifier() {
        return this.identifier;
    }

    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }

    public AgentBehaviorDto behavior() {
        return this.behavior;
    }

    public boolean active() {
        return this.active;
    }

    /**
     * Production bridge URL
     */
    public Optional<String> bridgeUrl() {
        return Optional.ofNullable(this.bridgeUrl);
    }

    /**
     * Development bridge URL (set by npx novu dev)
     */
    public Optional<String> devBridgeUrl() {
        return Optional.ofNullable(this.devBridgeUrl);
    }

    /**
     * Whether the dev bridge override is active
     */
    public Optional<Boolean> devBridgeActive() {
        return Optional.ofNullable(this.devBridgeActive);
    }

    /**
     * Whether the agent brain is self-hosted (bridge) or managed by a third-party provider
     */
    public Optional<AgentResponseDtoRuntime> runtime() {
        return Optional.ofNullable(this.runtime);
    }

    /**
     * Discovery scope of the agent. Always `public` today; reserved for the upcoming private-agents
     * feature.
     */
    public Optional<Visibility> visibility() {
        return Optional.ofNullable(this.visibility);
    }

    /**
     * Present when runtime is "managed". Contains provider and external identifiers.
     */
    public Optional<ManagedRuntimeResponseDto> managedRuntime() {
        return Optional.ofNullable(this.managedRuntime);
    }

    public String environmentId() {
        return this.environmentId;
    }

    public String organizationId() {
        return this.organizationId;
    }

    /**
     * Mongo user id of the user who created the agent
     */
    public Optional<String> createdBy() {
        return Optional.ofNullable(this.createdBy);
    }

    public String createdAt() {
        return this.createdAt;
    }

    public String updatedAt() {
        return this.updatedAt;
    }

    public Optional<List<AgentIntegrationSummaryDto>> integrations() {
        return Optional.ofNullable(this.integrations);
    }

    /**
     * Cloud only. `true` when the agent falls outside the organization plan agent limit (by creation order
     * among active agents — inactive agents do not consume slots). Only plan limits produce this flag —
     * system-capped organizations (enterprise/unlimited tiers) are never over-limit.
     * 
     * <p>Over-limit agents are still stored but will not respond to inbound messages until the plan is
     * upgraded or older agents are deactivated.
     */
    public Optional<Boolean> exceedsPlanLimit() {
        return Optional.ofNullable(this.exceedsPlanLimit);
    }

    public static Builder builder() {
        return new Builder();
    }


    public AgentResponseDto withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    public AgentResponseDto withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    public AgentResponseDto withIdentifier(@Nonnull String identifier) {
        this.identifier = Utils.checkNotNull(identifier, "identifier");
        return this;
    }


    public AgentResponseDto withDescription(@Nullable String description) {
        this.description = description;
        return this;
    }


    public AgentResponseDto withBehavior(@Nonnull AgentBehaviorDto behavior) {
        this.behavior = Utils.checkNotNull(behavior, "behavior");
        return this;
    }


    public AgentResponseDto withActive(boolean active) {
        this.active = active;
        return this;
    }


    /**
     * Production bridge URL
     */
    public AgentResponseDto withBridgeUrl(@Nullable String bridgeUrl) {
        this.bridgeUrl = bridgeUrl;
        return this;
    }


    /**
     * Development bridge URL (set by npx novu dev)
     */
    public AgentResponseDto withDevBridgeUrl(@Nullable String devBridgeUrl) {
        this.devBridgeUrl = devBridgeUrl;
        return this;
    }


    /**
     * Whether the dev bridge override is active
     */
    public AgentResponseDto withDevBridgeActive(@Nullable Boolean devBridgeActive) {
        this.devBridgeActive = devBridgeActive;
        return this;
    }


    /**
     * Whether the agent brain is self-hosted (bridge) or managed by a third-party provider
     */
    public AgentResponseDto withRuntime(@Nullable AgentResponseDtoRuntime runtime) {
        this.runtime = runtime;
        return this;
    }


    /**
     * Discovery scope of the agent. Always `public` today; reserved for the upcoming private-agents
     * feature.
     */
    public AgentResponseDto withVisibility(@Nullable Visibility visibility) {
        this.visibility = visibility;
        return this;
    }


    /**
     * Present when runtime is "managed". Contains provider and external identifiers.
     */
    public AgentResponseDto withManagedRuntime(@Nullable ManagedRuntimeResponseDto managedRuntime) {
        this.managedRuntime = managedRuntime;
        return this;
    }


    public AgentResponseDto withEnvironmentId(@Nonnull String environmentId) {
        this.environmentId = Utils.checkNotNull(environmentId, "environmentId");
        return this;
    }


    public AgentResponseDto withOrganizationId(@Nonnull String organizationId) {
        this.organizationId = Utils.checkNotNull(organizationId, "organizationId");
        return this;
    }


    /**
     * Mongo user id of the user who created the agent
     */
    public AgentResponseDto withCreatedBy(@Nullable String createdBy) {
        this.createdBy = createdBy;
        return this;
    }


    public AgentResponseDto withCreatedAt(@Nonnull String createdAt) {
        this.createdAt = Utils.checkNotNull(createdAt, "createdAt");
        return this;
    }


    public AgentResponseDto withUpdatedAt(@Nonnull String updatedAt) {
        this.updatedAt = Utils.checkNotNull(updatedAt, "updatedAt");
        return this;
    }


    public AgentResponseDto withIntegrations(@Nullable List<AgentIntegrationSummaryDto> integrations) {
        this.integrations = integrations;
        return this;
    }


    /**
     * Cloud only. `true` when the agent falls outside the organization plan agent limit (by creation order
     * among active agents — inactive agents do not consume slots). Only plan limits produce this flag —
     * system-capped organizations (enterprise/unlimited tiers) are never over-limit.
     * 
     * <p>Over-limit agents are still stored but will not respond to inbound messages until the plan is
     * upgraded or older agents are deactivated.
     */
    public AgentResponseDto withExceedsPlanLimit(@Nullable Boolean exceedsPlanLimit) {
        this.exceedsPlanLimit = exceedsPlanLimit;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AgentResponseDto other = (AgentResponseDto) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.identifier, other.identifier) &&
            Utils.enhancedDeepEquals(this.description, other.description) &&
            Utils.enhancedDeepEquals(this.behavior, other.behavior) &&
            Utils.enhancedDeepEquals(this.active, other.active) &&
            Utils.enhancedDeepEquals(this.bridgeUrl, other.bridgeUrl) &&
            Utils.enhancedDeepEquals(this.devBridgeUrl, other.devBridgeUrl) &&
            Utils.enhancedDeepEquals(this.devBridgeActive, other.devBridgeActive) &&
            Utils.enhancedDeepEquals(this.runtime, other.runtime) &&
            Utils.enhancedDeepEquals(this.visibility, other.visibility) &&
            Utils.enhancedDeepEquals(this.managedRuntime, other.managedRuntime) &&
            Utils.enhancedDeepEquals(this.environmentId, other.environmentId) &&
            Utils.enhancedDeepEquals(this.organizationId, other.organizationId) &&
            Utils.enhancedDeepEquals(this.createdBy, other.createdBy) &&
            Utils.enhancedDeepEquals(this.createdAt, other.createdAt) &&
            Utils.enhancedDeepEquals(this.updatedAt, other.updatedAt) &&
            Utils.enhancedDeepEquals(this.integrations, other.integrations) &&
            Utils.enhancedDeepEquals(this.exceedsPlanLimit, other.exceedsPlanLimit);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, name, identifier,
            description, behavior, active,
            bridgeUrl, devBridgeUrl, devBridgeActive,
            runtime, visibility, managedRuntime,
            environmentId, organizationId, createdBy,
            createdAt, updatedAt, integrations,
            exceedsPlanLimit);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AgentResponseDto.class,
                "id", id,
                "name", name,
                "identifier", identifier,
                "description", description,
                "behavior", behavior,
                "active", active,
                "bridgeUrl", bridgeUrl,
                "devBridgeUrl", devBridgeUrl,
                "devBridgeActive", devBridgeActive,
                "runtime", runtime,
                "visibility", visibility,
                "managedRuntime", managedRuntime,
                "environmentId", environmentId,
                "organizationId", organizationId,
                "createdBy", createdBy,
                "createdAt", createdAt,
                "updatedAt", updatedAt,
                "integrations", integrations,
                "exceedsPlanLimit", exceedsPlanLimit);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String name;

        private String identifier;

        private String description;

        private AgentBehaviorDto behavior;

        private boolean active;

        private String bridgeUrl;

        private String devBridgeUrl;

        private Boolean devBridgeActive;

        private AgentResponseDtoRuntime runtime;

        private Visibility visibility;

        private ManagedRuntimeResponseDto managedRuntime;

        private String environmentId;

        private String organizationId;

        private String createdBy;

        private String createdAt;

        private String updatedAt;

        private List<AgentIntegrationSummaryDto> integrations;

        private Boolean exceedsPlanLimit;

        private Builder() {
          // force use of static builder() method
        }

        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        public Builder identifier(@Nonnull String identifier) {
            this.identifier = Utils.checkNotNull(identifier, "identifier");
            return this;
        }

        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }

        public Builder behavior(@Nonnull AgentBehaviorDto behavior) {
            this.behavior = Utils.checkNotNull(behavior, "behavior");
            return this;
        }

        public Builder active(boolean active) {
            this.active = active;
            return this;
        }

        /**
         * Production bridge URL
         */
        public Builder bridgeUrl(@Nullable String bridgeUrl) {
            this.bridgeUrl = bridgeUrl;
            return this;
        }

        /**
         * Development bridge URL (set by npx novu dev)
         */
        public Builder devBridgeUrl(@Nullable String devBridgeUrl) {
            this.devBridgeUrl = devBridgeUrl;
            return this;
        }

        /**
         * Whether the dev bridge override is active
         */
        public Builder devBridgeActive(@Nullable Boolean devBridgeActive) {
            this.devBridgeActive = devBridgeActive;
            return this;
        }

        /**
         * Whether the agent brain is self-hosted (bridge) or managed by a third-party provider
         */
        public Builder runtime(@Nullable AgentResponseDtoRuntime runtime) {
            this.runtime = runtime;
            return this;
        }

        /**
         * Discovery scope of the agent. Always `public` today; reserved for the upcoming private-agents
         * feature.
         */
        public Builder visibility(@Nullable Visibility visibility) {
            this.visibility = visibility;
            return this;
        }

        /**
         * Present when runtime is "managed". Contains provider and external identifiers.
         */
        public Builder managedRuntime(@Nullable ManagedRuntimeResponseDto managedRuntime) {
            this.managedRuntime = managedRuntime;
            return this;
        }

        public Builder environmentId(@Nonnull String environmentId) {
            this.environmentId = Utils.checkNotNull(environmentId, "environmentId");
            return this;
        }

        public Builder organizationId(@Nonnull String organizationId) {
            this.organizationId = Utils.checkNotNull(organizationId, "organizationId");
            return this;
        }

        /**
         * Mongo user id of the user who created the agent
         */
        public Builder createdBy(@Nullable String createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        public Builder createdAt(@Nonnull String createdAt) {
            this.createdAt = Utils.checkNotNull(createdAt, "createdAt");
            return this;
        }

        public Builder updatedAt(@Nonnull String updatedAt) {
            this.updatedAt = Utils.checkNotNull(updatedAt, "updatedAt");
            return this;
        }

        public Builder integrations(@Nullable List<AgentIntegrationSummaryDto> integrations) {
            this.integrations = integrations;
            return this;
        }

        /**
         * Cloud only. `true` when the agent falls outside the organization plan agent limit (by creation order
         * among active agents — inactive agents do not consume slots). Only plan limits produce this flag —
         * system-capped organizations (enterprise/unlimited tiers) are never over-limit.
         * 
         * <p>Over-limit agents are still stored but will not respond to inbound messages until the plan is
         * upgraded or older agents are deactivated.
         */
        public Builder exceedsPlanLimit(@Nullable Boolean exceedsPlanLimit) {
            this.exceedsPlanLimit = exceedsPlanLimit;
            return this;
        }

        public AgentResponseDto build() {
            return new AgentResponseDto(
                id, name, identifier,
                description, behavior, active,
                bridgeUrl, devBridgeUrl, devBridgeActive,
                runtime, visibility, managedRuntime,
                environmentId, organizationId, createdBy,
                createdAt, updatedAt, integrations,
                exceedsPlanLimit);
        }

    }
}
