/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class ChannelSettingsDto {
    /**
     * The provider identifier for the credentials
     */
    @JsonProperty("providerId")
    private ChatOrPushProviderEnum providerId;

    /**
     * The integration identifier
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("integrationIdentifier")
    private String integrationIdentifier;

    /**
     * Credentials payload for the specified provider
     */
    @JsonProperty("credentials")
    private ChannelCredentials credentials;

    /**
     * The unique identifier of the integration associated with this channel.
     */
    @JsonProperty("_integrationId")
    private String integrationId;

    @JsonCreator
    public ChannelSettingsDto(
            @JsonProperty("providerId") @Nonnull ChatOrPushProviderEnum providerId,
            @JsonProperty("integrationIdentifier") @Nullable String integrationIdentifier,
            @JsonProperty("credentials") @Nonnull ChannelCredentials credentials,
            @JsonProperty("_integrationId") @Nonnull String integrationId) {
        this.providerId = Optional.ofNullable(providerId)
            .orElseThrow(() -> new IllegalArgumentException("providerId cannot be null"));
        this.integrationIdentifier = integrationIdentifier;
        this.credentials = Optional.ofNullable(credentials)
            .orElseThrow(() -> new IllegalArgumentException("credentials cannot be null"));
        this.integrationId = Optional.ofNullable(integrationId)
            .orElseThrow(() -> new IllegalArgumentException("integrationId cannot be null"));
    }
    
    public ChannelSettingsDto(
            @Nonnull ChatOrPushProviderEnum providerId,
            @Nonnull ChannelCredentials credentials,
            @Nonnull String integrationId) {
        this(providerId, null, credentials,
            integrationId);
    }

    /**
     * The provider identifier for the credentials
     */
    public ChatOrPushProviderEnum providerId() {
        return this.providerId;
    }

    /**
     * The integration identifier
     */
    public Optional<String> integrationIdentifier() {
        return Optional.ofNullable(this.integrationIdentifier);
    }

    /**
     * Credentials payload for the specified provider
     */
    public ChannelCredentials credentials() {
        return this.credentials;
    }

    /**
     * The unique identifier of the integration associated with this channel.
     */
    public String integrationId() {
        return this.integrationId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The provider identifier for the credentials
     */
    public ChannelSettingsDto withProviderId(@Nonnull ChatOrPushProviderEnum providerId) {
        this.providerId = Utils.checkNotNull(providerId, "providerId");
        return this;
    }


    /**
     * The integration identifier
     */
    public ChannelSettingsDto withIntegrationIdentifier(@Nullable String integrationIdentifier) {
        this.integrationIdentifier = integrationIdentifier;
        return this;
    }


    /**
     * Credentials payload for the specified provider
     */
    public ChannelSettingsDto withCredentials(@Nonnull ChannelCredentials credentials) {
        this.credentials = Utils.checkNotNull(credentials, "credentials");
        return this;
    }


    /**
     * The unique identifier of the integration associated with this channel.
     */
    public ChannelSettingsDto withIntegrationId(@Nonnull String integrationId) {
        this.integrationId = Utils.checkNotNull(integrationId, "integrationId");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ChannelSettingsDto other = (ChannelSettingsDto) o;
        return 
            Utils.enhancedDeepEquals(this.providerId, other.providerId) &&
            Utils.enhancedDeepEquals(this.integrationIdentifier, other.integrationIdentifier) &&
            Utils.enhancedDeepEquals(this.credentials, other.credentials) &&
            Utils.enhancedDeepEquals(this.integrationId, other.integrationId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            providerId, integrationIdentifier, credentials,
            integrationId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ChannelSettingsDto.class,
                "providerId", providerId,
                "integrationIdentifier", integrationIdentifier,
                "credentials", credentials,
                "integrationId", integrationId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private ChatOrPushProviderEnum providerId;

        private String integrationIdentifier;

        private ChannelCredentials credentials;

        private String integrationId;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The provider identifier for the credentials
         */
        public Builder providerId(@Nonnull ChatOrPushProviderEnum providerId) {
            this.providerId = Utils.checkNotNull(providerId, "providerId");
            return this;
        }

        /**
         * The integration identifier
         */
        public Builder integrationIdentifier(@Nullable String integrationIdentifier) {
            this.integrationIdentifier = integrationIdentifier;
            return this;
        }

        /**
         * Credentials payload for the specified provider
         */
        public Builder credentials(@Nonnull ChannelCredentials credentials) {
            this.credentials = Utils.checkNotNull(credentials, "credentials");
            return this;
        }

        /**
         * The unique identifier of the integration associated with this channel.
         */
        public Builder integrationId(@Nonnull String integrationId) {
            this.integrationId = Utils.checkNotNull(integrationId, "integrationId");
            return this;
        }

        public ChannelSettingsDto build() {
            return new ChannelSettingsDto(
                providerId, integrationIdentifier, credentials,
                integrationId);
        }

    }
}
