/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * ContentIssueEnum
 * 
 * <p>Type of step content issue
 */
public class ContentIssueEnum {

    public static final ContentIssueEnum ILLEGAL_VARIABLE_IN_CONTROL_VALUE = new ContentIssueEnum("ILLEGAL_VARIABLE_IN_CONTROL_VALUE");
    public static final ContentIssueEnum INVALID_FILTER_ARG_IN_VARIABLE = new ContentIssueEnum("INVALID_FILTER_ARG_IN_VARIABLE");
    public static final ContentIssueEnum INVALID_URL = new ContentIssueEnum("INVALID_URL");
    public static final ContentIssueEnum MISSING_VALUE = new ContentIssueEnum("MISSING_VALUE");
    public static final ContentIssueEnum TIER_LIMIT_EXCEEDED = new ContentIssueEnum("TIER_LIMIT_EXCEEDED");
    public static final ContentIssueEnum UNSUPPORTED_PROPERTY = new ContentIssueEnum("UNSUPPORTED_PROPERTY");
    public static final ContentIssueEnum CHAT_CARD_LIMIT_EXCEEDED = new ContentIssueEnum("CHAT_CARD_LIMIT_EXCEEDED");
    public static final ContentIssueEnum CHAT_CARD_INVALID_BUTTON = new ContentIssueEnum("CHAT_CARD_INVALID_BUTTON");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, ContentIssueEnum> values = createValuesMap();
    private static final Map<String, ContentIssueEnumEnum> enums = createEnumsMap();

    private final String value;

    private ContentIssueEnum(String value) {
        this.value = value;
    }

    /**
     * Returns a ContentIssueEnum with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as ContentIssueEnum
     */ 
    @JsonCreator
    public static ContentIssueEnum of(String value) {
        synchronized (ContentIssueEnum.class) {
            return values.computeIfAbsent(value, v -> new ContentIssueEnum(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<ContentIssueEnumEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        ContentIssueEnum other = (ContentIssueEnum) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "ContentIssueEnum [value=" + value + "]";
    }

    // return an array just like an enum
    public static ContentIssueEnum[] values() {
        synchronized (ContentIssueEnum.class) {
            return values.values().toArray(new ContentIssueEnum[] {});
        }
    }

    private static final Map<String, ContentIssueEnum> createValuesMap() {
        Map<String, ContentIssueEnum> map = new LinkedHashMap<>();
        map.put("ILLEGAL_VARIABLE_IN_CONTROL_VALUE", ILLEGAL_VARIABLE_IN_CONTROL_VALUE);
        map.put("INVALID_FILTER_ARG_IN_VARIABLE", INVALID_FILTER_ARG_IN_VARIABLE);
        map.put("INVALID_URL", INVALID_URL);
        map.put("MISSING_VALUE", MISSING_VALUE);
        map.put("TIER_LIMIT_EXCEEDED", TIER_LIMIT_EXCEEDED);
        map.put("UNSUPPORTED_PROPERTY", UNSUPPORTED_PROPERTY);
        map.put("CHAT_CARD_LIMIT_EXCEEDED", CHAT_CARD_LIMIT_EXCEEDED);
        map.put("CHAT_CARD_INVALID_BUTTON", CHAT_CARD_INVALID_BUTTON);
        return map;
    }

    private static final Map<String, ContentIssueEnumEnum> createEnumsMap() {
        Map<String, ContentIssueEnumEnum> map = new HashMap<>();
        map.put("ILLEGAL_VARIABLE_IN_CONTROL_VALUE", ContentIssueEnumEnum.ILLEGAL_VARIABLE_IN_CONTROL_VALUE);
        map.put("INVALID_FILTER_ARG_IN_VARIABLE", ContentIssueEnumEnum.INVALID_FILTER_ARG_IN_VARIABLE);
        map.put("INVALID_URL", ContentIssueEnumEnum.INVALID_URL);
        map.put("MISSING_VALUE", ContentIssueEnumEnum.MISSING_VALUE);
        map.put("TIER_LIMIT_EXCEEDED", ContentIssueEnumEnum.TIER_LIMIT_EXCEEDED);
        map.put("UNSUPPORTED_PROPERTY", ContentIssueEnumEnum.UNSUPPORTED_PROPERTY);
        map.put("CHAT_CARD_LIMIT_EXCEEDED", ContentIssueEnumEnum.CHAT_CARD_LIMIT_EXCEEDED);
        map.put("CHAT_CARD_INVALID_BUTTON", ContentIssueEnumEnum.CHAT_CARD_INVALID_BUTTON);
        return map;
    }
    
    
    public enum ContentIssueEnumEnum {

        ILLEGAL_VARIABLE_IN_CONTROL_VALUE("ILLEGAL_VARIABLE_IN_CONTROL_VALUE"),
        INVALID_FILTER_ARG_IN_VARIABLE("INVALID_FILTER_ARG_IN_VARIABLE"),
        INVALID_URL("INVALID_URL"),
        MISSING_VALUE("MISSING_VALUE"),
        TIER_LIMIT_EXCEEDED("TIER_LIMIT_EXCEEDED"),
        UNSUPPORTED_PROPERTY("UNSUPPORTED_PROPERTY"),
        CHAT_CARD_LIMIT_EXCEEDED("CHAT_CARD_LIMIT_EXCEEDED"),
        CHAT_CARD_INVALID_BUTTON("CHAT_CARD_INVALID_BUTTON"),;

        private final String value;

        private ContentIssueEnumEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

