/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Map;
import java.util.Optional;


public class ControlsMetadataDto {
    /**
     * JSON Schema for data
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dataSchema")
    private Map<String, Object> dataSchema;

    /**
     * UI Schema for rendering
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("uiSchema")
    private UiSchema uiSchema;

    @JsonCreator
    public ControlsMetadataDto(
            @JsonProperty("dataSchema") @Nullable Map<String, Object> dataSchema,
            @JsonProperty("uiSchema") @Nullable UiSchema uiSchema) {
        this.dataSchema = dataSchema;
        this.uiSchema = uiSchema;
    }
    
    public ControlsMetadataDto() {
        this(null, null);
    }

    /**
     * JSON Schema for data
     */
    public Optional<Map<String, Object>> dataSchema() {
        return Optional.ofNullable(this.dataSchema);
    }

    /**
     * UI Schema for rendering
     */
    public Optional<UiSchema> uiSchema() {
        return Optional.ofNullable(this.uiSchema);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * JSON Schema for data
     */
    public ControlsMetadataDto withDataSchema(@Nullable Map<String, Object> dataSchema) {
        this.dataSchema = dataSchema;
        return this;
    }


    /**
     * UI Schema for rendering
     */
    public ControlsMetadataDto withUiSchema(@Nullable UiSchema uiSchema) {
        this.uiSchema = uiSchema;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ControlsMetadataDto other = (ControlsMetadataDto) o;
        return 
            Utils.enhancedDeepEquals(this.dataSchema, other.dataSchema) &&
            Utils.enhancedDeepEquals(this.uiSchema, other.uiSchema);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            dataSchema, uiSchema);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ControlsMetadataDto.class,
                "dataSchema", dataSchema,
                "uiSchema", uiSchema);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Map<String, Object> dataSchema;

        private UiSchema uiSchema;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * JSON Schema for data
         */
        public Builder dataSchema(@Nullable Map<String, Object> dataSchema) {
            this.dataSchema = dataSchema;
            return this;
        }

        /**
         * UI Schema for rendering
         */
        public Builder uiSchema(@Nullable UiSchema uiSchema) {
            this.uiSchema = uiSchema;
            return this;
        }

        public ControlsMetadataDto build() {
            return new ControlsMetadataDto(
                dataSchema, uiSchema);
        }

    }
}
