/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * CreateLineUserEndpointDtoType
 * 
 * <p>Type of channel endpoint
 */
public enum CreateLineUserEndpointDtoType {
    LINE_USER("line_user");

    @JsonValue
    private final String value;

    CreateLineUserEndpointDtoType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<CreateLineUserEndpointDtoType> fromValue(String value) {
        for (CreateLineUserEndpointDtoType o: CreateLineUserEndpointDtoType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

