/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class CreatedSubscriberDto {
    /**
     * The ID of the subscriber that was created.
     */
    @JsonProperty("subscriberId")
    private String subscriberId;

    @JsonCreator
    public CreatedSubscriberDto(
            @JsonProperty("subscriberId") @Nonnull String subscriberId) {
        this.subscriberId = Optional.ofNullable(subscriberId)
            .orElseThrow(() -> new IllegalArgumentException("subscriberId cannot be null"));
    }

    /**
     * The ID of the subscriber that was created.
     */
    public String subscriberId() {
        return this.subscriberId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The ID of the subscriber that was created.
     */
    public CreatedSubscriberDto withSubscriberId(@Nonnull String subscriberId) {
        this.subscriberId = Utils.checkNotNull(subscriberId, "subscriberId");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreatedSubscriberDto other = (CreatedSubscriberDto) o;
        return 
            Utils.enhancedDeepEquals(this.subscriberId, other.subscriberId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            subscriberId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreatedSubscriberDto.class,
                "subscriberId", subscriberId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String subscriberId;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The ID of the subscriber that was created.
         */
        public Builder subscriberId(@Nonnull String subscriberId) {
            this.subscriberId = Utils.checkNotNull(subscriberId, "subscriberId");
            return this;
        }

        public CreatedSubscriberDto build() {
            return new CreatedSubscriberDto(
                subscriberId);
        }

    }
}
