/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class DelayScheduledMetadata {

    @JsonProperty("type")
    private DelayScheduledMetadataType type;


    @JsonProperty("delayPath")
    private String delayPath;

    @JsonCreator
    public DelayScheduledMetadata(
            @JsonProperty("type") @Nonnull DelayScheduledMetadataType type,
            @JsonProperty("delayPath") @Nonnull String delayPath) {
        this.type = Optional.ofNullable(type)
            .orElseThrow(() -> new IllegalArgumentException("type cannot be null"));
        this.delayPath = Optional.ofNullable(delayPath)
            .orElseThrow(() -> new IllegalArgumentException("delayPath cannot be null"));
    }

    public DelayScheduledMetadataType type() {
        return this.type;
    }

    public String delayPath() {
        return this.delayPath;
    }

    public static Builder builder() {
        return new Builder();
    }


    public DelayScheduledMetadata withType(@Nonnull DelayScheduledMetadataType type) {
        this.type = Utils.checkNotNull(type, "type");
        return this;
    }


    public DelayScheduledMetadata withDelayPath(@Nonnull String delayPath) {
        this.delayPath = Utils.checkNotNull(delayPath, "delayPath");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DelayScheduledMetadata other = (DelayScheduledMetadata) o;
        return 
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.delayPath, other.delayPath);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            type, delayPath);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DelayScheduledMetadata.class,
                "type", type,
                "delayPath", delayPath);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private DelayScheduledMetadataType type;

        private String delayPath;

        private Builder() {
          // force use of static builder() method
        }

        public Builder type(@Nonnull DelayScheduledMetadataType type) {
            this.type = Utils.checkNotNull(type, "type");
            return this;
        }

        public Builder delayPath(@Nonnull String delayPath) {
            this.delayPath = Utils.checkNotNull(delayPath, "delayPath");
            return this;
        }

        public DelayScheduledMetadata build() {
            return new DelayScheduledMetadata(
                type, delayPath);
        }

    }
}
