/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class DelayRegularMetadata {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("amount")
    private Double amount;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("unit")
    private DelayRegularMetadataUnit unit;


    @JsonProperty("type")
    private DelayRegularMetadataType type;

    @JsonCreator
    public DelayRegularMetadata(
            @JsonProperty("amount") @Nullable Double amount,
            @JsonProperty("unit") @Nullable DelayRegularMetadataUnit unit,
            @JsonProperty("type") @Nonnull DelayRegularMetadataType type) {
        this.amount = amount;
        this.unit = unit;
        this.type = Optional.ofNullable(type)
            .orElseThrow(() -> new IllegalArgumentException("type cannot be null"));
    }
    
    public DelayRegularMetadata(
            @Nonnull DelayRegularMetadataType type) {
        this(null, null, type);
    }

    public Optional<Double> amount() {
        return Optional.ofNullable(this.amount);
    }

    public Optional<DelayRegularMetadataUnit> unit() {
        return Optional.ofNullable(this.unit);
    }

    public DelayRegularMetadataType type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }


    public DelayRegularMetadata withAmount(@Nullable Double amount) {
        this.amount = amount;
        return this;
    }


    public DelayRegularMetadata withUnit(@Nullable DelayRegularMetadataUnit unit) {
        this.unit = unit;
        return this;
    }


    public DelayRegularMetadata withType(@Nonnull DelayRegularMetadataType type) {
        this.type = Utils.checkNotNull(type, "type");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DelayRegularMetadata other = (DelayRegularMetadata) o;
        return 
            Utils.enhancedDeepEquals(this.amount, other.amount) &&
            Utils.enhancedDeepEquals(this.unit, other.unit) &&
            Utils.enhancedDeepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            amount, unit, type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DelayRegularMetadata.class,
                "amount", amount,
                "unit", unit,
                "type", type);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Double amount;

        private DelayRegularMetadataUnit unit;

        private DelayRegularMetadataType type;

        private Builder() {
          // force use of static builder() method
        }

        public Builder amount(@Nullable Double amount) {
            this.amount = amount;
            return this;
        }

        public Builder unit(@Nullable DelayRegularMetadataUnit unit) {
            this.unit = unit;
            return this;
        }

        public Builder type(@Nonnull DelayRegularMetadataType type) {
            this.type = Utils.checkNotNull(type, "type");
            return this;
        }

        public DelayRegularMetadata build() {
            return new DelayRegularMetadata(
                amount, unit, type);
        }

    }
}
