/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * EmailStepResponseDtoEditorType
 * 
 * <p>Type of editor to use for the body.
 */
public class EmailStepResponseDtoEditorType {

    public static final EmailStepResponseDtoEditorType BLOCK = new EmailStepResponseDtoEditorType("block");
    public static final EmailStepResponseDtoEditorType HTML = new EmailStepResponseDtoEditorType("html");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, EmailStepResponseDtoEditorType> values = createValuesMap();
    private static final Map<String, EmailStepResponseDtoEditorTypeEnum> enums = createEnumsMap();

    private final String value;

    private EmailStepResponseDtoEditorType(String value) {
        this.value = value;
    }

    /**
     * Returns a EmailStepResponseDtoEditorType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as EmailStepResponseDtoEditorType
     */ 
    @JsonCreator
    public static EmailStepResponseDtoEditorType of(String value) {
        synchronized (EmailStepResponseDtoEditorType.class) {
            return values.computeIfAbsent(value, v -> new EmailStepResponseDtoEditorType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<EmailStepResponseDtoEditorTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EmailStepResponseDtoEditorType other = (EmailStepResponseDtoEditorType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "EmailStepResponseDtoEditorType [value=" + value + "]";
    }

    // return an array just like an enum
    public static EmailStepResponseDtoEditorType[] values() {
        synchronized (EmailStepResponseDtoEditorType.class) {
            return values.values().toArray(new EmailStepResponseDtoEditorType[] {});
        }
    }

    private static final Map<String, EmailStepResponseDtoEditorType> createValuesMap() {
        Map<String, EmailStepResponseDtoEditorType> map = new LinkedHashMap<>();
        map.put("block", BLOCK);
        map.put("html", HTML);
        return map;
    }

    private static final Map<String, EmailStepResponseDtoEditorTypeEnum> createEnumsMap() {
        Map<String, EmailStepResponseDtoEditorTypeEnum> map = new HashMap<>();
        map.put("block", EmailStepResponseDtoEditorTypeEnum.BLOCK);
        map.put("html", EmailStepResponseDtoEditorTypeEnum.HTML);
        return map;
    }
    
    
    public enum EmailStepResponseDtoEditorTypeEnum {

        BLOCK("block"),
        HTML("html"),;

        private final String value;

        private EmailStepResponseDtoEditorTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

