/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class EmailBlockStyles {
    /**
     * Text alignment for the email block
     */
    @JsonProperty("textAlign")
    private TextAlignEnum textAlign;

    @JsonCreator
    public EmailBlockStyles(
            @JsonProperty("textAlign") @Nonnull TextAlignEnum textAlign) {
        this.textAlign = Optional.ofNullable(textAlign)
            .orElseThrow(() -> new IllegalArgumentException("textAlign cannot be null"));
    }

    /**
     * Text alignment for the email block
     */
    public TextAlignEnum textAlign() {
        return this.textAlign;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Text alignment for the email block
     */
    public EmailBlockStyles withTextAlign(@Nonnull TextAlignEnum textAlign) {
        this.textAlign = Utils.checkNotNull(textAlign, "textAlign");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EmailBlockStyles other = (EmailBlockStyles) o;
        return 
            Utils.enhancedDeepEquals(this.textAlign, other.textAlign);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            textAlign);
    }
    
    @Override
    public String toString() {
        return Utils.toString(EmailBlockStyles.class,
                "textAlign", textAlign);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private TextAlignEnum textAlign;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Text alignment for the email block
         */
        public Builder textAlign(@Nonnull TextAlignEnum textAlign) {
            this.textAlign = Utils.checkNotNull(textAlign, "textAlign");
            return this;
        }

        public EmailBlockStyles build() {
            return new EmailBlockStyles(
                textAlign);
        }

    }
}
