/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class EnvironmentResponseDto {
    /**
     * Unique identifier of the environment
     */
    @JsonProperty("_id")
    private String id;

    /**
     * Name of the environment
     */
    @JsonProperty("name")
    private String name;

    /**
     * Organization ID associated with the environment
     */
    @JsonProperty("_organizationId")
    private String organizationId;

    /**
     * Unique identifier for the environment
     */
    @JsonProperty("identifier")
    private String identifier;

    /**
     * Type of the environment
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private JsonNullable<EnvironmentResponseDtoType> type;

    /**
     * List of API keys associated with the environment
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("apiKeys")
    private List<ApiKeyDto> apiKeys;

    /**
     * Parent environment ID
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("_parentId")
    private String parentId;

    /**
     * URL-friendly slug for the environment
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("slug")
    private String slug;

    @JsonCreator
    public EnvironmentResponseDto(
            @JsonProperty("_id") @Nonnull String id,
            @JsonProperty("name") @Nonnull String name,
            @JsonProperty("_organizationId") @Nonnull String organizationId,
            @JsonProperty("identifier") @Nonnull String identifier,
            @JsonProperty("type") @Nullable JsonNullable<EnvironmentResponseDtoType> type,
            @JsonProperty("apiKeys") @Nullable List<ApiKeyDto> apiKeys,
            @JsonProperty("_parentId") @Nullable String parentId,
            @JsonProperty("slug") @Nullable String slug) {
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.name = Optional.ofNullable(name)
            .orElseThrow(() -> new IllegalArgumentException("name cannot be null"));
        this.organizationId = Optional.ofNullable(organizationId)
            .orElseThrow(() -> new IllegalArgumentException("organizationId cannot be null"));
        this.identifier = Optional.ofNullable(identifier)
            .orElseThrow(() -> new IllegalArgumentException("identifier cannot be null"));
        this.type = Optional.ofNullable(type)
            .orElse(JsonNullable.undefined());
        this.apiKeys = apiKeys;
        this.parentId = parentId;
        this.slug = slug;
    }
    
    public EnvironmentResponseDto(
            @Nonnull String id,
            @Nonnull String name,
            @Nonnull String organizationId,
            @Nonnull String identifier) {
        this(id, name, organizationId,
            identifier, null, null,
            null, null);
    }

    /**
     * Unique identifier of the environment
     */
    public String id() {
        return this.id;
    }

    /**
     * Name of the environment
     */
    public String name() {
        return this.name;
    }

    /**
     * Organization ID associated with the environment
     */
    public String organizationId() {
        return this.organizationId;
    }

    /**
     * Unique identifier for the environment
     */
    public String identifier() {
        return this.identifier;
    }

    /**
     * Type of the environment
     */
    public JsonNullable<EnvironmentResponseDtoType> type() {
        return this.type;
    }

    /**
     * List of API keys associated with the environment
     */
    public Optional<List<ApiKeyDto>> apiKeys() {
        return Optional.ofNullable(this.apiKeys);
    }

    /**
     * Parent environment ID
     */
    public Optional<String> parentId() {
        return Optional.ofNullable(this.parentId);
    }

    /**
     * URL-friendly slug for the environment
     */
    public Optional<String> slug() {
        return Optional.ofNullable(this.slug);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Unique identifier of the environment
     */
    public EnvironmentResponseDto withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    /**
     * Name of the environment
     */
    public EnvironmentResponseDto withName(@Nonnull String name) {
        this.name = Utils.checkNotNull(name, "name");
        return this;
    }


    /**
     * Organization ID associated with the environment
     */
    public EnvironmentResponseDto withOrganizationId(@Nonnull String organizationId) {
        this.organizationId = Utils.checkNotNull(organizationId, "organizationId");
        return this;
    }


    /**
     * Unique identifier for the environment
     */
    public EnvironmentResponseDto withIdentifier(@Nonnull String identifier) {
        this.identifier = Utils.checkNotNull(identifier, "identifier");
        return this;
    }


    /**
     * Type of the environment
     */
    public EnvironmentResponseDto withType(@Nullable EnvironmentResponseDtoType type) {
        this.type = JsonNullable.of(type);
        return this;
    }


    /**
     * List of API keys associated with the environment
     */
    public EnvironmentResponseDto withApiKeys(@Nullable List<ApiKeyDto> apiKeys) {
        this.apiKeys = apiKeys;
        return this;
    }


    /**
     * Parent environment ID
     */
    public EnvironmentResponseDto withParentId(@Nullable String parentId) {
        this.parentId = parentId;
        return this;
    }


    /**
     * URL-friendly slug for the environment
     */
    public EnvironmentResponseDto withSlug(@Nullable String slug) {
        this.slug = slug;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EnvironmentResponseDto other = (EnvironmentResponseDto) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.organizationId, other.organizationId) &&
            Utils.enhancedDeepEquals(this.identifier, other.identifier) &&
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.apiKeys, other.apiKeys) &&
            Utils.enhancedDeepEquals(this.parentId, other.parentId) &&
            Utils.enhancedDeepEquals(this.slug, other.slug);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, name, organizationId,
            identifier, type, apiKeys,
            parentId, slug);
    }
    
    @Override
    public String toString() {
        return Utils.toString(EnvironmentResponseDto.class,
                "id", id,
                "name", name,
                "organizationId", organizationId,
                "identifier", identifier,
                "type", type,
                "apiKeys", apiKeys,
                "parentId", parentId,
                "slug", slug);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String name;

        private String organizationId;

        private String identifier;

        private JsonNullable<EnvironmentResponseDtoType> type;

        private List<ApiKeyDto> apiKeys;

        private String parentId;

        private String slug;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Unique identifier of the environment
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        /**
         * Name of the environment
         */
        public Builder name(@Nonnull String name) {
            this.name = Utils.checkNotNull(name, "name");
            return this;
        }

        /**
         * Organization ID associated with the environment
         */
        public Builder organizationId(@Nonnull String organizationId) {
            this.organizationId = Utils.checkNotNull(organizationId, "organizationId");
            return this;
        }

        /**
         * Unique identifier for the environment
         */
        public Builder identifier(@Nonnull String identifier) {
            this.identifier = Utils.checkNotNull(identifier, "identifier");
            return this;
        }

        /**
         * Type of the environment
         */
        public Builder type(@Nullable EnvironmentResponseDtoType type) {
            this.type = JsonNullable.of(type);
            return this;
        }

        /**
         * List of API keys associated with the environment
         */
        public Builder apiKeys(@Nullable List<ApiKeyDto> apiKeys) {
            this.apiKeys = apiKeys;
            return this;
        }

        /**
         * Parent environment ID
         */
        public Builder parentId(@Nullable String parentId) {
            this.parentId = parentId;
            return this;
        }

        /**
         * URL-friendly slug for the environment
         */
        public Builder slug(@Nullable String slug) {
            this.slug = slug;
            return this;
        }

        public EnvironmentResponseDto build() {
            return new EnvironmentResponseDto(
                id, name, organizationId,
                identifier, type, apiKeys,
                parentId, slug);
        }

    }
}
