/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * EnvironmentResponseDtoType
 * 
 * <p>Type of the environment
 */
public class EnvironmentResponseDtoType {

    public static final EnvironmentResponseDtoType DEV = new EnvironmentResponseDtoType("dev");
    public static final EnvironmentResponseDtoType PROD = new EnvironmentResponseDtoType("prod");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, EnvironmentResponseDtoType> values = createValuesMap();
    private static final Map<String, EnvironmentResponseDtoTypeEnum> enums = createEnumsMap();

    private final String value;

    private EnvironmentResponseDtoType(String value) {
        this.value = value;
    }

    /**
     * Returns a EnvironmentResponseDtoType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as EnvironmentResponseDtoType
     */ 
    @JsonCreator
    public static EnvironmentResponseDtoType of(String value) {
        synchronized (EnvironmentResponseDtoType.class) {
            return values.computeIfAbsent(value, v -> new EnvironmentResponseDtoType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<EnvironmentResponseDtoTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EnvironmentResponseDtoType other = (EnvironmentResponseDtoType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "EnvironmentResponseDtoType [value=" + value + "]";
    }

    // return an array just like an enum
    public static EnvironmentResponseDtoType[] values() {
        synchronized (EnvironmentResponseDtoType.class) {
            return values.values().toArray(new EnvironmentResponseDtoType[] {});
        }
    }

    private static final Map<String, EnvironmentResponseDtoType> createValuesMap() {
        Map<String, EnvironmentResponseDtoType> map = new LinkedHashMap<>();
        map.put("dev", DEV);
        map.put("prod", PROD);
        return map;
    }

    private static final Map<String, EnvironmentResponseDtoTypeEnum> createEnumsMap() {
        Map<String, EnvironmentResponseDtoTypeEnum> map = new HashMap<>();
        map.put("dev", EnvironmentResponseDtoTypeEnum.DEV);
        map.put("prod", EnvironmentResponseDtoTypeEnum.PROD);
        return map;
    }
    
    
    public enum EnvironmentResponseDtoTypeEnum {

        DEV("dev"),
        PROD("prod"),;

        private final String value;

        private EnvironmentResponseDtoTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

