/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class GeneratePreviewResponseDto {
    /**
     * Preview payload example
     */
    @JsonProperty("previewPayloadExample")
    private PreviewPayloadDto previewPayloadExample;

    /**
     * The payload schema that was used to generate the preview payload example
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("schema")
    private JsonNullable<Map<String, Object>> schema;

    /**
     * Sample novu-signature header value for HTTP request steps
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("novuSignature")
    private String novuSignature;

    /**
     * Preview result
     */
    @JsonProperty("result")
    private GeneratePreviewResponseDtoResultUnion result;

    @JsonCreator
    public GeneratePreviewResponseDto(
            @JsonProperty("previewPayloadExample") @Nonnull PreviewPayloadDto previewPayloadExample,
            @JsonProperty("schema") @Nullable JsonNullable<Map<String, Object>> schema,
            @JsonProperty("novuSignature") @Nullable String novuSignature,
            @JsonProperty("result") @Nonnull GeneratePreviewResponseDtoResultUnion result) {
        this.previewPayloadExample = Optional.ofNullable(previewPayloadExample)
            .orElseThrow(() -> new IllegalArgumentException("previewPayloadExample cannot be null"));
        this.schema = Optional.ofNullable(schema)
            .orElse(JsonNullable.undefined());
        this.novuSignature = novuSignature;
        this.result = Optional.ofNullable(result)
            .orElseThrow(() -> new IllegalArgumentException("result cannot be null"));
    }
    
    public GeneratePreviewResponseDto(
            @Nonnull PreviewPayloadDto previewPayloadExample,
            @Nonnull GeneratePreviewResponseDtoResultUnion result) {
        this(previewPayloadExample, null, null,
            result);
    }

    /**
     * Preview payload example
     */
    public PreviewPayloadDto previewPayloadExample() {
        return this.previewPayloadExample;
    }

    /**
     * The payload schema that was used to generate the preview payload example
     */
    public JsonNullable<Map<String, Object>> schema() {
        return this.schema;
    }

    /**
     * Sample novu-signature header value for HTTP request steps
     */
    public Optional<String> novuSignature() {
        return Optional.ofNullable(this.novuSignature);
    }

    /**
     * Preview result
     */
    public GeneratePreviewResponseDtoResultUnion result() {
        return this.result;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Preview payload example
     */
    public GeneratePreviewResponseDto withPreviewPayloadExample(@Nonnull PreviewPayloadDto previewPayloadExample) {
        this.previewPayloadExample = Utils.checkNotNull(previewPayloadExample, "previewPayloadExample");
        return this;
    }


    /**
     * The payload schema that was used to generate the preview payload example
     */
    public GeneratePreviewResponseDto withSchema(@Nullable Map<String, Object> schema) {
        this.schema = JsonNullable.of(schema);
        return this;
    }


    /**
     * Sample novu-signature header value for HTTP request steps
     */
    public GeneratePreviewResponseDto withNovuSignature(@Nullable String novuSignature) {
        this.novuSignature = novuSignature;
        return this;
    }


    /**
     * Preview result
     */
    public GeneratePreviewResponseDto withResult(@Nonnull GeneratePreviewResponseDtoResultUnion result) {
        this.result = Utils.checkNotNull(result, "result");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GeneratePreviewResponseDto other = (GeneratePreviewResponseDto) o;
        return 
            Utils.enhancedDeepEquals(this.previewPayloadExample, other.previewPayloadExample) &&
            Utils.enhancedDeepEquals(this.schema, other.schema) &&
            Utils.enhancedDeepEquals(this.novuSignature, other.novuSignature) &&
            Utils.enhancedDeepEquals(this.result, other.result);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            previewPayloadExample, schema, novuSignature,
            result);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GeneratePreviewResponseDto.class,
                "previewPayloadExample", previewPayloadExample,
                "schema", schema,
                "novuSignature", novuSignature,
                "result", result);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private PreviewPayloadDto previewPayloadExample;

        private JsonNullable<Map<String, Object>> schema;

        private String novuSignature;

        private GeneratePreviewResponseDtoResultUnion result;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Preview payload example
         */
        public Builder previewPayloadExample(@Nonnull PreviewPayloadDto previewPayloadExample) {
            this.previewPayloadExample = Utils.checkNotNull(previewPayloadExample, "previewPayloadExample");
            return this;
        }

        /**
         * The payload schema that was used to generate the preview payload example
         */
        public Builder schema(@Nullable Map<String, Object> schema) {
            this.schema = JsonNullable.of(schema);
            return this;
        }

        /**
         * Sample novu-signature header value for HTTP request steps
         */
        public Builder novuSignature(@Nullable String novuSignature) {
            this.novuSignature = novuSignature;
            return this;
        }

        /**
         * Preview result
         */
        public Builder result(@Nonnull GeneratePreviewResponseDtoResultUnion result) {
            this.result = Utils.checkNotNull(result, "result");
            return this;
        }

        public GeneratePreviewResponseDto build() {
            return new GeneratePreviewResponseDto(
                previewPayloadExample, schema, novuSignature,
                result);
        }

    }
}
