/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.OneOfDeserializer;
import co.novu.utils.TypedObject;
import co.novu.utils.Utils.JsonShape;
import co.novu.utils.Utils.TypeReferenceWithShape;
import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;

/**
 * GetChannelEndpointResponseDtoEndpoint
 * 
 * <p>Endpoint data specific to the channel type
 */
@JsonDeserialize(using = GetChannelEndpointResponseDtoEndpoint._Deserializer.class)
public class GetChannelEndpointResponseDtoEndpoint {

    @JsonValue
    private final TypedObject value;
    
    private GetChannelEndpointResponseDtoEndpoint(TypedObject value) {
        this.value = value;
    }

    public static GetChannelEndpointResponseDtoEndpoint of(SlackChannelEndpointDto value) {
        Utils.checkNotNull(value, "value");
        return new GetChannelEndpointResponseDtoEndpoint(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static GetChannelEndpointResponseDtoEndpoint of(SlackUserEndpointDto value) {
        Utils.checkNotNull(value, "value");
        return new GetChannelEndpointResponseDtoEndpoint(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static GetChannelEndpointResponseDtoEndpoint of(WebhookEndpointDto value) {
        Utils.checkNotNull(value, "value");
        return new GetChannelEndpointResponseDtoEndpoint(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static GetChannelEndpointResponseDtoEndpoint of(PhoneEndpointDto value) {
        Utils.checkNotNull(value, "value");
        return new GetChannelEndpointResponseDtoEndpoint(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static GetChannelEndpointResponseDtoEndpoint of(MsTeamsChannelEndpointDto value) {
        Utils.checkNotNull(value, "value");
        return new GetChannelEndpointResponseDtoEndpoint(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static GetChannelEndpointResponseDtoEndpoint of(MsTeamsUserEndpointDto value) {
        Utils.checkNotNull(value, "value");
        return new GetChannelEndpointResponseDtoEndpoint(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static GetChannelEndpointResponseDtoEndpoint of(TelegramChatEndpointDto value) {
        Utils.checkNotNull(value, "value");
        return new GetChannelEndpointResponseDtoEndpoint(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static GetChannelEndpointResponseDtoEndpoint of(WebexRoomEndpointDto value) {
        Utils.checkNotNull(value, "value");
        return new GetChannelEndpointResponseDtoEndpoint(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static GetChannelEndpointResponseDtoEndpoint of(WebexPersonEndpointDto value) {
        Utils.checkNotNull(value, "value");
        return new GetChannelEndpointResponseDtoEndpoint(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static GetChannelEndpointResponseDtoEndpoint of(LineUserEndpointDto value) {
        Utils.checkNotNull(value, "value");
        return new GetChannelEndpointResponseDtoEndpoint(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static GetChannelEndpointResponseDtoEndpoint of(PagerDutyServiceEndpointDto value) {
        Utils.checkNotNull(value, "value");
        return new GetChannelEndpointResponseDtoEndpoint(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static GetChannelEndpointResponseDtoEndpoint of(OpsgenieIntegrationEndpointDto value) {
        Utils.checkNotNull(value, "value");
        return new GetChannelEndpointResponseDtoEndpoint(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static GetChannelEndpointResponseDtoEndpoint of(GrafanaOnCallIntegrationEndpointDto value) {
        Utils.checkNotNull(value, "value");
        return new GetChannelEndpointResponseDtoEndpoint(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static GetChannelEndpointResponseDtoEndpoint of(ToolWebhookEndpointDto value) {
        Utils.checkNotNull(value, "value");
        return new GetChannelEndpointResponseDtoEndpoint(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code SlackChannelEndpointDto},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code SlackChannelEndpointDto} value, or empty if not of this type
     */
    public Optional<SlackChannelEndpointDto> slackChannelEndpointDto() {
        if (value.value() instanceof SlackChannelEndpointDto) {
            return Optional.of((SlackChannelEndpointDto) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code SlackUserEndpointDto},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code SlackUserEndpointDto} value, or empty if not of this type
     */
    public Optional<SlackUserEndpointDto> slackUserEndpointDto() {
        if (value.value() instanceof SlackUserEndpointDto) {
            return Optional.of((SlackUserEndpointDto) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code WebhookEndpointDto},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code WebhookEndpointDto} value, or empty if not of this type
     */
    public Optional<WebhookEndpointDto> webhookEndpointDto() {
        if (value.value() instanceof WebhookEndpointDto) {
            return Optional.of((WebhookEndpointDto) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code PhoneEndpointDto},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code PhoneEndpointDto} value, or empty if not of this type
     */
    public Optional<PhoneEndpointDto> phoneEndpointDto() {
        if (value.value() instanceof PhoneEndpointDto) {
            return Optional.of((PhoneEndpointDto) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code MsTeamsChannelEndpointDto},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code MsTeamsChannelEndpointDto} value, or empty if not of this type
     */
    public Optional<MsTeamsChannelEndpointDto> msTeamsChannelEndpointDto() {
        if (value.value() instanceof MsTeamsChannelEndpointDto) {
            return Optional.of((MsTeamsChannelEndpointDto) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code MsTeamsUserEndpointDto},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code MsTeamsUserEndpointDto} value, or empty if not of this type
     */
    public Optional<MsTeamsUserEndpointDto> msTeamsUserEndpointDto() {
        if (value.value() instanceof MsTeamsUserEndpointDto) {
            return Optional.of((MsTeamsUserEndpointDto) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code TelegramChatEndpointDto},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code TelegramChatEndpointDto} value, or empty if not of this type
     */
    public Optional<TelegramChatEndpointDto> telegramChatEndpointDto() {
        if (value.value() instanceof TelegramChatEndpointDto) {
            return Optional.of((TelegramChatEndpointDto) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code WebexRoomEndpointDto},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code WebexRoomEndpointDto} value, or empty if not of this type
     */
    public Optional<WebexRoomEndpointDto> webexRoomEndpointDto() {
        if (value.value() instanceof WebexRoomEndpointDto) {
            return Optional.of((WebexRoomEndpointDto) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code WebexPersonEndpointDto},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code WebexPersonEndpointDto} value, or empty if not of this type
     */
    public Optional<WebexPersonEndpointDto> webexPersonEndpointDto() {
        if (value.value() instanceof WebexPersonEndpointDto) {
            return Optional.of((WebexPersonEndpointDto) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code LineUserEndpointDto},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code LineUserEndpointDto} value, or empty if not of this type
     */
    public Optional<LineUserEndpointDto> lineUserEndpointDto() {
        if (value.value() instanceof LineUserEndpointDto) {
            return Optional.of((LineUserEndpointDto) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code PagerDutyServiceEndpointDto},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code PagerDutyServiceEndpointDto} value, or empty if not of this type
     */
    public Optional<PagerDutyServiceEndpointDto> pagerDutyServiceEndpointDto() {
        if (value.value() instanceof PagerDutyServiceEndpointDto) {
            return Optional.of((PagerDutyServiceEndpointDto) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code OpsgenieIntegrationEndpointDto},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code OpsgenieIntegrationEndpointDto} value, or empty if not of this type
     */
    public Optional<OpsgenieIntegrationEndpointDto> opsgenieIntegrationEndpointDto() {
        if (value.value() instanceof OpsgenieIntegrationEndpointDto) {
            return Optional.of((OpsgenieIntegrationEndpointDto) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code GrafanaOnCallIntegrationEndpointDto},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code GrafanaOnCallIntegrationEndpointDto} value, or empty if not of this type
     */
    public Optional<GrafanaOnCallIntegrationEndpointDto> grafanaOnCallIntegrationEndpointDto() {
        if (value.value() instanceof GrafanaOnCallIntegrationEndpointDto) {
            return Optional.of((GrafanaOnCallIntegrationEndpointDto) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code ToolWebhookEndpointDto},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code ToolWebhookEndpointDto} value, or empty if not of this type
     */
    public Optional<ToolWebhookEndpointDto> toolWebhookEndpointDto() {
        if (value.value() instanceof ToolWebhookEndpointDto) {
            return Optional.of((ToolWebhookEndpointDto) value.value());
        }
        return Optional.empty();
    }
   /**
    * Returns an {@link Optional} containing the value as a {@code JsonNode}.
    * This accessor returns the raw JSON when the value doesn't match any of the defined union types.
    *
    * @return an {@link Optional} containing the {@code JsonNode} value, or empty if value matched a known type
    */
   public Optional<JsonNode> asJson() {
       if (value.value() instanceof JsonNode) {
           return Optional.of((JsonNode) value.value());
       }
       return Optional.empty();
   }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetChannelEndpointResponseDtoEndpoint other = (GetChannelEndpointResponseDtoEndpoint) o;
        return Utils.enhancedDeepEquals(this.value.value(), other.value.value());
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<GetChannelEndpointResponseDtoEndpoint> {

        public _Deserializer() {
            super(GetChannelEndpointResponseDtoEndpoint.class, false,
                  TypeReferenceWithShape.of(new TypeReference<SlackChannelEndpointDto>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<SlackUserEndpointDto>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<WebhookEndpointDto>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<PhoneEndpointDto>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<MsTeamsChannelEndpointDto>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<MsTeamsUserEndpointDto>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<TelegramChatEndpointDto>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<WebexRoomEndpointDto>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<WebexPersonEndpointDto>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<LineUserEndpointDto>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<PagerDutyServiceEndpointDto>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<OpsgenieIntegrationEndpointDto>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<GrafanaOnCallIntegrationEndpointDto>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<ToolWebhookEndpointDto>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetChannelEndpointResponseDtoEndpoint.class,
                "value", value);
    }

}

