/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class GetSubscriberNotificationsResponseDto {
    /**
     * Array of notifications
     */
    @JsonProperty("data")
    private List<InboxNotificationDto> data;

    /**
     * Indicates if there are more notifications available
     */
    @JsonProperty("hasMore")
    private boolean hasMore;

    /**
     * The filter applied to the notifications
     */
    @JsonProperty("filter")
    private Filter filter;

    @JsonCreator
    public GetSubscriberNotificationsResponseDto(
            @JsonProperty("data") @Nonnull List<InboxNotificationDto> data,
            @JsonProperty("hasMore") boolean hasMore,
            @JsonProperty("filter") @Nonnull Filter filter) {
        this.data = Optional.ofNullable(data)
            .orElseThrow(() -> new IllegalArgumentException("data cannot be null"));
        this.hasMore = hasMore;
        this.filter = Optional.ofNullable(filter)
            .orElseThrow(() -> new IllegalArgumentException("filter cannot be null"));
    }

    /**
     * Array of notifications
     */
    public List<InboxNotificationDto> data() {
        return this.data;
    }

    /**
     * Indicates if there are more notifications available
     */
    public boolean hasMore() {
        return this.hasMore;
    }

    /**
     * The filter applied to the notifications
     */
    public Filter filter() {
        return this.filter;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Array of notifications
     */
    public GetSubscriberNotificationsResponseDto withData(@Nonnull List<InboxNotificationDto> data) {
        this.data = Utils.checkNotNull(data, "data");
        return this;
    }


    /**
     * Indicates if there are more notifications available
     */
    public GetSubscriberNotificationsResponseDto withHasMore(boolean hasMore) {
        this.hasMore = hasMore;
        return this;
    }


    /**
     * The filter applied to the notifications
     */
    public GetSubscriberNotificationsResponseDto withFilter(@Nonnull Filter filter) {
        this.filter = Utils.checkNotNull(filter, "filter");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetSubscriberNotificationsResponseDto other = (GetSubscriberNotificationsResponseDto) o;
        return 
            Utils.enhancedDeepEquals(this.data, other.data) &&
            Utils.enhancedDeepEquals(this.hasMore, other.hasMore) &&
            Utils.enhancedDeepEquals(this.filter, other.filter);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            data, hasMore, filter);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetSubscriberNotificationsResponseDto.class,
                "data", data,
                "hasMore", hasMore,
                "filter", filter);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<InboxNotificationDto> data;

        private boolean hasMore;

        private Filter filter;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Array of notifications
         */
        public Builder data(@Nonnull List<InboxNotificationDto> data) {
            this.data = Utils.checkNotNull(data, "data");
            return this;
        }

        /**
         * Indicates if there are more notifications available
         */
        public Builder hasMore(boolean hasMore) {
            this.hasMore = hasMore;
            return this;
        }

        /**
         * The filter applied to the notifications
         */
        public Builder filter(@Nonnull Filter filter) {
            this.filter = Utils.checkNotNull(filter, "filter");
            return this;
        }

        public GetSubscriberNotificationsResponseDto build() {
            return new GetSubscriberNotificationsResponseDto(
                data, hasMore, filter);
        }

    }
}
