/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class GrafanaOnCallIntegrationEndpointDto {
    /**
     * Grafana IRM/OnCall incoming-webhook (Formatted Webhook) integration URL. The routing secret is
     * embedded in the URL path. Encrypted at rest on the channel endpoint (`endpoint` field).
     */
    @JsonProperty("url")
    private String url;

    /**
     * Optional Grafana service account bearer token, required when the integration enforces authenticated
     * ingestion. Encrypted at rest on the channel endpoint (`endpoint` field).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("authToken")
    private String authToken;

    @JsonCreator
    public GrafanaOnCallIntegrationEndpointDto(
            @JsonProperty("url") @Nonnull String url,
            @JsonProperty("authToken") @Nullable String authToken) {
        this.url = Optional.ofNullable(url)
            .orElseThrow(() -> new IllegalArgumentException("url cannot be null"));
        this.authToken = authToken;
    }
    
    public GrafanaOnCallIntegrationEndpointDto(
            @Nonnull String url) {
        this(url, null);
    }

    /**
     * Grafana IRM/OnCall incoming-webhook (Formatted Webhook) integration URL. The routing secret is
     * embedded in the URL path. Encrypted at rest on the channel endpoint (`endpoint` field).
     */
    public String url() {
        return this.url;
    }

    /**
     * Optional Grafana service account bearer token, required when the integration enforces authenticated
     * ingestion. Encrypted at rest on the channel endpoint (`endpoint` field).
     */
    public Optional<String> authToken() {
        return Optional.ofNullable(this.authToken);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Grafana IRM/OnCall incoming-webhook (Formatted Webhook) integration URL. The routing secret is
     * embedded in the URL path. Encrypted at rest on the channel endpoint (`endpoint` field).
     */
    public GrafanaOnCallIntegrationEndpointDto withUrl(@Nonnull String url) {
        this.url = Utils.checkNotNull(url, "url");
        return this;
    }


    /**
     * Optional Grafana service account bearer token, required when the integration enforces authenticated
     * ingestion. Encrypted at rest on the channel endpoint (`endpoint` field).
     */
    public GrafanaOnCallIntegrationEndpointDto withAuthToken(@Nullable String authToken) {
        this.authToken = authToken;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GrafanaOnCallIntegrationEndpointDto other = (GrafanaOnCallIntegrationEndpointDto) o;
        return 
            Utils.enhancedDeepEquals(this.url, other.url) &&
            Utils.enhancedDeepEquals(this.authToken, other.authToken);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            url, authToken);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GrafanaOnCallIntegrationEndpointDto.class,
                "url", url,
                "authToken", authToken);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String url;

        private String authToken;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Grafana IRM/OnCall incoming-webhook (Formatted Webhook) integration URL. The routing secret is
         * embedded in the URL path. Encrypted at rest on the channel endpoint (`endpoint` field).
         */
        public Builder url(@Nonnull String url) {
            this.url = Utils.checkNotNull(url, "url");
            return this;
        }

        /**
         * Optional Grafana service account bearer token, required when the integration enforces authenticated
         * ingestion. Encrypted at rest on the channel endpoint (`endpoint` field).
         */
        public Builder authToken(@Nullable String authToken) {
            this.authToken = authToken;
            return this;
        }

        public GrafanaOnCallIntegrationEndpointDto build() {
            return new GrafanaOnCallIntegrationEndpointDto(
                url, authToken);
        }

    }
}
