/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * HttpRequestStepResponseDtoControlValues
 * 
 * <p>Control values for the HTTP request step
 */
public class HttpRequestStepResponseDtoControlValues {
    /**
     * HTTP method
     */
    @JsonProperty("method")
    private HttpMethodEnum method;

    /**
     * Target URL for the HTTP request
     */
    @JsonProperty("url")
    private String url;

    /**
     * Request headers as key-value pairs
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("headers")
    private List<HttpRequestKeyValuePairDto> headers;

    /**
     * Request body as a raw JSON string. Key-value arrays are supported for legacy workflows.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("body")
    private HttpRequestStepResponseDtoBody body;

    /**
     * JSON schema to validate response body against
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("responseBodySchema")
    private Map<String, Object> responseBodySchema;

    /**
     * Whether to enforce response body schema validation
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("enforceSchemaValidation")
    private Boolean enforceSchemaValidation;

    /**
     * Whether to continue workflow execution on failure
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("continueOnFailure")
    private Boolean continueOnFailure;


    @JsonIgnore
    private Map<String, Object> additionalProperties;

    @JsonCreator
    public HttpRequestStepResponseDtoControlValues(
            @JsonProperty("method") @Nonnull HttpMethodEnum method,
            @JsonProperty("url") @Nonnull String url,
            @JsonProperty("headers") @Nullable List<HttpRequestKeyValuePairDto> headers,
            @JsonProperty("body") @Nullable HttpRequestStepResponseDtoBody body,
            @JsonProperty("responseBodySchema") @Nullable Map<String, Object> responseBodySchema,
            @JsonProperty("enforceSchemaValidation") @Nullable Boolean enforceSchemaValidation,
            @JsonProperty("continueOnFailure") @Nullable Boolean continueOnFailure) {
        this.method = Optional.ofNullable(method)
            .orElseThrow(() -> new IllegalArgumentException("method cannot be null"));
        this.url = Optional.ofNullable(url)
            .orElseThrow(() -> new IllegalArgumentException("url cannot be null"));
        this.headers = headers;
        this.body = body;
        this.responseBodySchema = responseBodySchema;
        this.enforceSchemaValidation = enforceSchemaValidation;
        this.continueOnFailure = continueOnFailure;
        this.additionalProperties = new HashMap<>();
    }
    
    public HttpRequestStepResponseDtoControlValues(
            @Nonnull HttpMethodEnum method,
            @Nonnull String url) {
        this(method, url, null,
            null, null, null,
            null);
    }

    /**
     * HTTP method
     */
    public HttpMethodEnum method() {
        return this.method;
    }

    /**
     * Target URL for the HTTP request
     */
    public String url() {
        return this.url;
    }

    /**
     * Request headers as key-value pairs
     */
    public Optional<List<HttpRequestKeyValuePairDto>> headers() {
        return Optional.ofNullable(this.headers);
    }

    /**
     * Request body as a raw JSON string. Key-value arrays are supported for legacy workflows.
     */
    public Optional<HttpRequestStepResponseDtoBody> body() {
        return Optional.ofNullable(this.body);
    }

    /**
     * JSON schema to validate response body against
     */
    public Optional<Map<String, Object>> responseBodySchema() {
        return Optional.ofNullable(this.responseBodySchema);
    }

    /**
     * Whether to enforce response body schema validation
     */
    public Optional<Boolean> enforceSchemaValidation() {
        return Optional.ofNullable(this.enforceSchemaValidation);
    }

    /**
     * Whether to continue workflow execution on failure
     */
    public Optional<Boolean> continueOnFailure() {
        return Optional.ofNullable(this.continueOnFailure);
    }

    @JsonAnyGetter
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP method
     */
    public HttpRequestStepResponseDtoControlValues withMethod(@Nonnull HttpMethodEnum method) {
        this.method = Utils.checkNotNull(method, "method");
        return this;
    }


    /**
     * Target URL for the HTTP request
     */
    public HttpRequestStepResponseDtoControlValues withUrl(@Nonnull String url) {
        this.url = Utils.checkNotNull(url, "url");
        return this;
    }


    /**
     * Request headers as key-value pairs
     */
    public HttpRequestStepResponseDtoControlValues withHeaders(@Nullable List<HttpRequestKeyValuePairDto> headers) {
        this.headers = headers;
        return this;
    }


    /**
     * Request body as a raw JSON string. Key-value arrays are supported for legacy workflows.
     */
    public HttpRequestStepResponseDtoControlValues withBody(@Nullable HttpRequestStepResponseDtoBody body) {
        this.body = body;
        return this;
    }


    /**
     * JSON schema to validate response body against
     */
    public HttpRequestStepResponseDtoControlValues withResponseBodySchema(@Nullable Map<String, Object> responseBodySchema) {
        this.responseBodySchema = responseBodySchema;
        return this;
    }


    /**
     * Whether to enforce response body schema validation
     */
    public HttpRequestStepResponseDtoControlValues withEnforceSchemaValidation(@Nullable Boolean enforceSchemaValidation) {
        this.enforceSchemaValidation = enforceSchemaValidation;
        return this;
    }


    /**
     * Whether to continue workflow execution on failure
     */
    public HttpRequestStepResponseDtoControlValues withContinueOnFailure(@Nullable Boolean continueOnFailure) {
        this.continueOnFailure = continueOnFailure;
        return this;
    }


    @JsonAnySetter
    public HttpRequestStepResponseDtoControlValues withAdditionalProperty(String key, Object value) {
        // note that value can be null because of the way JsonAnySetter works
        Utils.checkNotNull(key, "key");
        additionalProperties.put(key, value);
        return this;
    }

    public HttpRequestStepResponseDtoControlValues withAdditionalProperties(@Nullable Map<String, Object> additionalProperties) {
        this.additionalProperties = additionalProperties;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        HttpRequestStepResponseDtoControlValues other = (HttpRequestStepResponseDtoControlValues) o;
        return 
            Utils.enhancedDeepEquals(this.method, other.method) &&
            Utils.enhancedDeepEquals(this.url, other.url) &&
            Utils.enhancedDeepEquals(this.headers, other.headers) &&
            Utils.enhancedDeepEquals(this.body, other.body) &&
            Utils.enhancedDeepEquals(this.responseBodySchema, other.responseBodySchema) &&
            Utils.enhancedDeepEquals(this.enforceSchemaValidation, other.enforceSchemaValidation) &&
            Utils.enhancedDeepEquals(this.continueOnFailure, other.continueOnFailure) &&
            Utils.enhancedDeepEquals(this.additionalProperties, other.additionalProperties);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            method, url, headers,
            body, responseBodySchema, enforceSchemaValidation,
            continueOnFailure, additionalProperties);
    }
    
    @Override
    public String toString() {
        return Utils.toString(HttpRequestStepResponseDtoControlValues.class,
                "method", method,
                "url", url,
                "headers", headers,
                "body", body,
                "responseBodySchema", responseBodySchema,
                "enforceSchemaValidation", enforceSchemaValidation,
                "continueOnFailure", continueOnFailure,
                "additionalProperties", additionalProperties);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private HttpMethodEnum method;

        private String url;

        private List<HttpRequestKeyValuePairDto> headers;

        private HttpRequestStepResponseDtoBody body;

        private Map<String, Object> responseBodySchema;

        private Boolean enforceSchemaValidation;

        private Boolean continueOnFailure;

        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP method
         */
        public Builder method(@Nonnull HttpMethodEnum method) {
            this.method = Utils.checkNotNull(method, "method");
            return this;
        }

        /**
         * Target URL for the HTTP request
         */
        public Builder url(@Nonnull String url) {
            this.url = Utils.checkNotNull(url, "url");
            return this;
        }

        /**
         * Request headers as key-value pairs
         */
        public Builder headers(@Nullable List<HttpRequestKeyValuePairDto> headers) {
            this.headers = headers;
            return this;
        }

        /**
         * Request body as a raw JSON string. Key-value arrays are supported for legacy workflows.
         */
        public Builder body(@Nullable HttpRequestStepResponseDtoBody body) {
            this.body = body;
            return this;
        }

        /**
         * JSON schema to validate response body against
         */
        public Builder responseBodySchema(@Nullable Map<String, Object> responseBodySchema) {
            this.responseBodySchema = responseBodySchema;
            return this;
        }

        /**
         * Whether to enforce response body schema validation
         */
        public Builder enforceSchemaValidation(@Nullable Boolean enforceSchemaValidation) {
            this.enforceSchemaValidation = enforceSchemaValidation;
            return this;
        }

        /**
         * Whether to continue workflow execution on failure
         */
        public Builder continueOnFailure(@Nullable Boolean continueOnFailure) {
            this.continueOnFailure = continueOnFailure;
            return this;
        }

        public Builder additionalProperty(String key, Object value) {
            Utils.checkNotNull(key, "key");
            // we could be strict about null values (force the user
            // to pass `JsonNullable.of(null)`) but likely to be a bit 
            // annoying for additional properties building so we'll 
            // relax preconditions.
            this.additionalProperties.put(key, value);
            return this;
        }
        public Builder additionalProperties(@Nullable Map<String, Object> additionalProperties) {
            this.additionalProperties = additionalProperties;
            return this;
        }

        public HttpRequestStepResponseDtoControlValues build() {
            return new HttpRequestStepResponseDtoControlValues(
                method, url, headers,
                body, responseBodySchema, enforceSchemaValidation,
                continueOnFailure)
                .withAdditionalProperties(additionalProperties);
        }

    }
}
