/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.OneOfDeserializer;
import co.novu.utils.TypedObject;
import co.novu.utils.Utils.JsonShape;
import co.novu.utils.Utils.TypeReferenceWithShape;
import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;

/**
 * HumanSignalDtoTo
 * 
 * <p>Novu subscriberId(s) allowed to settle this interaction (max 50). First valid answer wins. When
 * omitted, the conversation subscriber is used.
 * 
 * <p>Subscriber ids only — not workflow topic recipients.
 */
@JsonDeserialize(using = HumanSignalDtoTo._Deserializer.class)
public class HumanSignalDtoTo {

    @JsonValue
    private final TypedObject value;
    
    private HumanSignalDtoTo(TypedObject value) {
        this.value = value;
    }

    public static HumanSignalDtoTo of(String value) {
        Utils.checkNotNull(value, "value");
        return new HumanSignalDtoTo(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static HumanSignalDtoTo of(List<String> value) {
        Utils.checkNotNull(value, "value");
        return new HumanSignalDtoTo(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code String},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code String} value, or empty if not of this type
     */
    public Optional<String> string() {
        if (value.value() instanceof String) {
            return Optional.of((String) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code List<String>},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code List<String>} value, or empty if not of this type
     */
    @SuppressWarnings("unchecked")
    public Optional<List<String>> arrayOfString() {
        if (value.value() instanceof List) {
            return Optional.of((List<String>) value.value());
        }
        return Optional.empty();
    }
   /**
    * Returns an {@link Optional} containing the value as a {@code JsonNode}.
    * This accessor returns the raw JSON when the value doesn't match any of the defined union types.
    *
    * @return an {@link Optional} containing the {@code JsonNode} value, or empty if value matched a known type
    */
   public Optional<JsonNode> asJson() {
       if (value.value() instanceof JsonNode) {
           return Optional.of((JsonNode) value.value());
       }
       return Optional.empty();
   }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        HumanSignalDtoTo other = (HumanSignalDtoTo) o;
        return Utils.enhancedDeepEquals(this.value.value(), other.value.value());
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<HumanSignalDtoTo> {

        public _Deserializer() {
            super(HumanSignalDtoTo.class, false,
                  TypeReferenceWithShape.of(new TypeReference<String>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<List<String>>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(HumanSignalDtoTo.class,
                "value", value);
    }

}

