/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum HumanSignalDtoType {
    HUMAN("human");

    @JsonValue
    private final String value;

    HumanSignalDtoType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<HumanSignalDtoType> fromValue(String value) {
        for (HumanSignalDtoType o: HumanSignalDtoType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

