/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class IssueType {

    public static final IssueType MISSING_VALUE = new IssueType("MISSING_VALUE");
    public static final IssueType MAX_LENGTH_ACCESSED = new IssueType("MAX_LENGTH_ACCESSED");
    public static final IssueType WORKFLOW_ID_ALREADY_EXISTS = new IssueType("WORKFLOW_ID_ALREADY_EXISTS");
    public static final IssueType DUPLICATED_VALUE = new IssueType("DUPLICATED_VALUE");
    public static final IssueType LIMIT_REACHED = new IssueType("LIMIT_REACHED");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, IssueType> values = createValuesMap();
    private static final Map<String, IssueTypeEnum> enums = createEnumsMap();

    private final String value;

    private IssueType(String value) {
        this.value = value;
    }

    /**
     * Returns a IssueType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as IssueType
     */ 
    @JsonCreator
    public static IssueType of(String value) {
        synchronized (IssueType.class) {
            return values.computeIfAbsent(value, v -> new IssueType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<IssueTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        IssueType other = (IssueType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "IssueType [value=" + value + "]";
    }

    // return an array just like an enum
    public static IssueType[] values() {
        synchronized (IssueType.class) {
            return values.values().toArray(new IssueType[] {});
        }
    }

    private static final Map<String, IssueType> createValuesMap() {
        Map<String, IssueType> map = new LinkedHashMap<>();
        map.put("MISSING_VALUE", MISSING_VALUE);
        map.put("MAX_LENGTH_ACCESSED", MAX_LENGTH_ACCESSED);
        map.put("WORKFLOW_ID_ALREADY_EXISTS", WORKFLOW_ID_ALREADY_EXISTS);
        map.put("DUPLICATED_VALUE", DUPLICATED_VALUE);
        map.put("LIMIT_REACHED", LIMIT_REACHED);
        return map;
    }

    private static final Map<String, IssueTypeEnum> createEnumsMap() {
        Map<String, IssueTypeEnum> map = new HashMap<>();
        map.put("MISSING_VALUE", IssueTypeEnum.MISSING_VALUE);
        map.put("MAX_LENGTH_ACCESSED", IssueTypeEnum.MAX_LENGTH_ACCESSED);
        map.put("WORKFLOW_ID_ALREADY_EXISTS", IssueTypeEnum.WORKFLOW_ID_ALREADY_EXISTS);
        map.put("DUPLICATED_VALUE", IssueTypeEnum.DUPLICATED_VALUE);
        map.put("LIMIT_REACHED", IssueTypeEnum.LIMIT_REACHED);
        return map;
    }
    
    
    public enum IssueTypeEnum {

        MISSING_VALUE("MISSING_VALUE"),
        MAX_LENGTH_ACCESSED("MAX_LENGTH_ACCESSED"),
        WORKFLOW_ID_ALREADY_EXISTS("WORKFLOW_ID_ALREADY_EXISTS"),
        DUPLICATED_VALUE("DUPLICATED_VALUE"),
        LIMIT_REACHED("LIMIT_REACHED"),;

        private final String value;

        private IssueTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

