/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * LayoutCreationSourceEnum
 * 
 * <p>Source of layout creation
 */
public enum LayoutCreationSourceEnum {
    DASHBOARD("dashboard");

    @JsonValue
    private final String value;

    LayoutCreationSourceEnum(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<LayoutCreationSourceEnum> fromValue(String value) {
        for (LayoutCreationSourceEnum o: LayoutCreationSourceEnum.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

