/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;


public class MetaDto {
    /**
     * The total count of subscriber IDs provided
     */
    @JsonProperty("totalCount")
    private double totalCount;

    /**
     * The count of successfully created subscriptions
     */
    @JsonProperty("successful")
    private double successful;

    /**
     * The count of failed subscription attempts
     */
    @JsonProperty("failed")
    private double failed;

    @JsonCreator
    public MetaDto(
            @JsonProperty("totalCount") double totalCount,
            @JsonProperty("successful") double successful,
            @JsonProperty("failed") double failed) {
        this.totalCount = totalCount;
        this.successful = successful;
        this.failed = failed;
    }

    /**
     * The total count of subscriber IDs provided
     */
    public double totalCount() {
        return this.totalCount;
    }

    /**
     * The count of successfully created subscriptions
     */
    public double successful() {
        return this.successful;
    }

    /**
     * The count of failed subscription attempts
     */
    public double failed() {
        return this.failed;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The total count of subscriber IDs provided
     */
    public MetaDto withTotalCount(double totalCount) {
        this.totalCount = totalCount;
        return this;
    }


    /**
     * The count of successfully created subscriptions
     */
    public MetaDto withSuccessful(double successful) {
        this.successful = successful;
        return this;
    }


    /**
     * The count of failed subscription attempts
     */
    public MetaDto withFailed(double failed) {
        this.failed = failed;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MetaDto other = (MetaDto) o;
        return 
            Utils.enhancedDeepEquals(this.totalCount, other.totalCount) &&
            Utils.enhancedDeepEquals(this.successful, other.successful) &&
            Utils.enhancedDeepEquals(this.failed, other.failed);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            totalCount, successful, failed);
    }
    
    @Override
    public String toString() {
        return Utils.toString(MetaDto.class,
                "totalCount", totalCount,
                "successful", successful,
                "failed", failed);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private double totalCount;

        private double successful;

        private double failed;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The total count of subscriber IDs provided
         */
        public Builder totalCount(double totalCount) {
            this.totalCount = totalCount;
            return this;
        }

        /**
         * The count of successfully created subscriptions
         */
        public Builder successful(double successful) {
            this.successful = successful;
            return this;
        }

        /**
         * The count of failed subscription attempts
         */
        public Builder failed(double failed) {
            this.failed = failed;
            return this;
        }

        public MetaDto build() {
            return new MetaDto(
                totalCount, successful, failed);
        }

    }
}
