/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class MsTeamsUserEndpointDto {
    /**
     * MS Teams user ID
     */
    @JsonProperty("userId")
    private String userId;

    @JsonCreator
    public MsTeamsUserEndpointDto(
            @JsonProperty("userId") @Nonnull String userId) {
        this.userId = Optional.ofNullable(userId)
            .orElseThrow(() -> new IllegalArgumentException("userId cannot be null"));
    }

    /**
     * MS Teams user ID
     */
    public String userId() {
        return this.userId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * MS Teams user ID
     */
    public MsTeamsUserEndpointDto withUserId(@Nonnull String userId) {
        this.userId = Utils.checkNotNull(userId, "userId");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MsTeamsUserEndpointDto other = (MsTeamsUserEndpointDto) o;
        return 
            Utils.enhancedDeepEquals(this.userId, other.userId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            userId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(MsTeamsUserEndpointDto.class,
                "userId", userId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String userId;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * MS Teams user ID
         */
        public Builder userId(@Nonnull String userId) {
            this.userId = Utils.checkNotNull(userId, "userId");
            return this;
        }

        public MsTeamsUserEndpointDto build() {
            return new MsTeamsUserEndpointDto(
                userId);
        }

    }
}
