/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * NotificationTriggerDtoType
 * 
 * <p>Type of the trigger
 */
public class NotificationTriggerDtoType {

    public static final NotificationTriggerDtoType EVENT = new NotificationTriggerDtoType("event");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, NotificationTriggerDtoType> values = createValuesMap();
    private static final Map<String, NotificationTriggerDtoTypeEnum> enums = createEnumsMap();

    private final String value;

    private NotificationTriggerDtoType(String value) {
        this.value = value;
    }

    /**
     * Returns a NotificationTriggerDtoType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as NotificationTriggerDtoType
     */ 
    @JsonCreator
    public static NotificationTriggerDtoType of(String value) {
        synchronized (NotificationTriggerDtoType.class) {
            return values.computeIfAbsent(value, v -> new NotificationTriggerDtoType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<NotificationTriggerDtoTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        NotificationTriggerDtoType other = (NotificationTriggerDtoType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "NotificationTriggerDtoType [value=" + value + "]";
    }

    // return an array just like an enum
    public static NotificationTriggerDtoType[] values() {
        synchronized (NotificationTriggerDtoType.class) {
            return values.values().toArray(new NotificationTriggerDtoType[] {});
        }
    }

    private static final Map<String, NotificationTriggerDtoType> createValuesMap() {
        Map<String, NotificationTriggerDtoType> map = new LinkedHashMap<>();
        map.put("event", EVENT);
        return map;
    }

    private static final Map<String, NotificationTriggerDtoTypeEnum> createEnumsMap() {
        Map<String, NotificationTriggerDtoTypeEnum> map = new HashMap<>();
        map.put("event", NotificationTriggerDtoTypeEnum.EVENT);
        return map;
    }
    
    
    public enum NotificationTriggerDtoTypeEnum {

        EVENT("event"),;

        private final String value;

        private NotificationTriggerDtoTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

