/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Map;
import java.util.Optional;


public class PatchSubscriberPreferencesDto {
    /**
     * Channel-specific preference settings
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("channels")
    private PatchPreferenceChannelsDto channels;

    /**
     * Workflow internal _id, identifier or slug. If provided, update workflow specific preferences,
     * otherwise update global preferences
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("workflowId")
    private String workflowId;

    /**
     * Subscriber schedule
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("schedule")
    private ScheduleDto schedule;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("context")
    private Map<String, PatchSubscriberPreferencesDtoContextUnion> context;

    @JsonCreator
    public PatchSubscriberPreferencesDto(
            @JsonProperty("channels") @Nullable PatchPreferenceChannelsDto channels,
            @JsonProperty("workflowId") @Nullable String workflowId,
            @JsonProperty("schedule") @Nullable ScheduleDto schedule,
            @JsonProperty("context") @Nullable Map<String, PatchSubscriberPreferencesDtoContextUnion> context) {
        this.channels = channels;
        this.workflowId = workflowId;
        this.schedule = schedule;
        this.context = context;
    }
    
    public PatchSubscriberPreferencesDto() {
        this(null, null, null,
            null);
    }

    /**
     * Channel-specific preference settings
     */
    public Optional<PatchPreferenceChannelsDto> channels() {
        return Optional.ofNullable(this.channels);
    }

    /**
     * Workflow internal _id, identifier or slug. If provided, update workflow specific preferences,
     * otherwise update global preferences
     */
    public Optional<String> workflowId() {
        return Optional.ofNullable(this.workflowId);
    }

    /**
     * Subscriber schedule
     */
    public Optional<ScheduleDto> schedule() {
        return Optional.ofNullable(this.schedule);
    }

    public Optional<Map<String, PatchSubscriberPreferencesDtoContextUnion>> context() {
        return Optional.ofNullable(this.context);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Channel-specific preference settings
     */
    public PatchSubscriberPreferencesDto withChannels(@Nullable PatchPreferenceChannelsDto channels) {
        this.channels = channels;
        return this;
    }


    /**
     * Workflow internal _id, identifier or slug. If provided, update workflow specific preferences,
     * otherwise update global preferences
     */
    public PatchSubscriberPreferencesDto withWorkflowId(@Nullable String workflowId) {
        this.workflowId = workflowId;
        return this;
    }


    /**
     * Subscriber schedule
     */
    public PatchSubscriberPreferencesDto withSchedule(@Nullable ScheduleDto schedule) {
        this.schedule = schedule;
        return this;
    }


    public PatchSubscriberPreferencesDto withContext(@Nullable Map<String, PatchSubscriberPreferencesDtoContextUnion> context) {
        this.context = context;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PatchSubscriberPreferencesDto other = (PatchSubscriberPreferencesDto) o;
        return 
            Utils.enhancedDeepEquals(this.channels, other.channels) &&
            Utils.enhancedDeepEquals(this.workflowId, other.workflowId) &&
            Utils.enhancedDeepEquals(this.schedule, other.schedule) &&
            Utils.enhancedDeepEquals(this.context, other.context);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            channels, workflowId, schedule,
            context);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PatchSubscriberPreferencesDto.class,
                "channels", channels,
                "workflowId", workflowId,
                "schedule", schedule,
                "context", context);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private PatchPreferenceChannelsDto channels;

        private String workflowId;

        private ScheduleDto schedule;

        private Map<String, PatchSubscriberPreferencesDtoContextUnion> context;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Channel-specific preference settings
         */
        public Builder channels(@Nullable PatchPreferenceChannelsDto channels) {
            this.channels = channels;
            return this;
        }

        /**
         * Workflow internal _id, identifier or slug. If provided, update workflow specific preferences,
         * otherwise update global preferences
         */
        public Builder workflowId(@Nullable String workflowId) {
            this.workflowId = workflowId;
            return this;
        }

        /**
         * Subscriber schedule
         */
        public Builder schedule(@Nullable ScheduleDto schedule) {
            this.schedule = schedule;
            return this;
        }

        public Builder context(@Nullable Map<String, PatchSubscriberPreferencesDtoContextUnion> context) {
            this.context = context;
            return this;
        }

        public PatchSubscriberPreferencesDto build() {
            return new PatchSubscriberPreferencesDto(
                channels, workflowId, schedule,
                context);
        }

    }
}
