/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.OneOfDeserializer;
import co.novu.utils.TypedObject;
import co.novu.utils.Utils.JsonShape;
import co.novu.utils.Utils.TypeReferenceWithShape;
import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;

/**
 * PayloadValidationErrorDtoValueUnion2
 * 
 * <p>The actual value that failed validation
 */
@JsonDeserialize(using = PayloadValidationErrorDtoValueUnion2._Deserializer.class)
public class PayloadValidationErrorDtoValueUnion2 {

    @JsonValue
    private final TypedObject value;
    
    private PayloadValidationErrorDtoValueUnion2(TypedObject value) {
        this.value = value;
    }

    public static PayloadValidationErrorDtoValueUnion2 of(String value) {
        Utils.checkNotNull(value, "value");
        return new PayloadValidationErrorDtoValueUnion2(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static PayloadValidationErrorDtoValueUnion2 of(double value) {
        return new PayloadValidationErrorDtoValueUnion2(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static PayloadValidationErrorDtoValueUnion2 of(boolean value) {
        return new PayloadValidationErrorDtoValueUnion2(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static PayloadValidationErrorDtoValueUnion2 of(PayloadValidationErrorDtoValue value) {
        Utils.checkNotNull(value, "value");
        return new PayloadValidationErrorDtoValueUnion2(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static PayloadValidationErrorDtoValueUnion2 of(List<PayloadValidationErrorDtoValueUnion1> value) {
        Utils.checkNotNull(value, "value");
        return new PayloadValidationErrorDtoValueUnion2(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code String},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code String} value, or empty if not of this type
     */
    public Optional<String> string() {
        if (value.value() instanceof String) {
            return Optional.of((String) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code double},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code double} value, or empty if not of this type
     */
    public Optional<java.lang.Double> asDouble() {
        if (value.value() instanceof java.lang.Double) {
            return Optional.of((java.lang.Double) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code boolean},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code boolean} value, or empty if not of this type
     */
    public Optional<java.lang.Boolean> asBoolean() {
        if (value.value() instanceof java.lang.Boolean) {
            return Optional.of((java.lang.Boolean) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code PayloadValidationErrorDtoValue},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code PayloadValidationErrorDtoValue} value, or empty if not of this type
     */
    public Optional<PayloadValidationErrorDtoValue> payloadValidationErrorDtoValue() {
        if (value.value() instanceof PayloadValidationErrorDtoValue) {
            return Optional.of((PayloadValidationErrorDtoValue) value.value());
        }
        return Optional.empty();
    }
    
    /**
     * Returns an {@link Optional} containing the value if it is of type {@code List<PayloadValidationErrorDtoValueUnion1>},
     * otherwise returns an empty {@link Optional}.
     *
     * @return an {@link Optional} containing the {@code List<PayloadValidationErrorDtoValueUnion1>} value, or empty if not of this type
     */
    @SuppressWarnings("unchecked")
    public Optional<List<PayloadValidationErrorDtoValueUnion1>> arrayOfPayloadValidationErrorDtoValueUnion1() {
        if (value.value() instanceof List) {
            return Optional.of((List<PayloadValidationErrorDtoValueUnion1>) value.value());
        }
        return Optional.empty();
    }
   /**
    * Returns an {@link Optional} containing the value as a {@code JsonNode}.
    * This accessor returns the raw JSON when the value doesn't match any of the defined union types.
    *
    * @return an {@link Optional} containing the {@code JsonNode} value, or empty if value matched a known type
    */
   public Optional<JsonNode> asJson() {
       if (value.value() instanceof JsonNode) {
           return Optional.of((JsonNode) value.value());
       }
       return Optional.empty();
   }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PayloadValidationErrorDtoValueUnion2 other = (PayloadValidationErrorDtoValueUnion2) o;
        return Utils.enhancedDeepEquals(this.value.value(), other.value.value());
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<PayloadValidationErrorDtoValueUnion2> {

        public _Deserializer() {
            super(PayloadValidationErrorDtoValueUnion2.class, false,
                  TypeReferenceWithShape.of(new TypeReference<String>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<Double>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<Boolean>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<PayloadValidationErrorDtoValue>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<List<PayloadValidationErrorDtoValueUnion1>>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(PayloadValidationErrorDtoValueUnion2.class,
                "value", value);
    }

}

