/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Map;
import java.util.Optional;

/**
 * PreferencesRequestDtoWorkflow
 * 
 * <p>Workflow-specific preferences
 */
public class PreferencesRequestDtoWorkflow {
    /**
     * A preference for the workflow. The values specified here will be used if no preference is specified
     * for a channel.
     */
    @JsonProperty("all")
    private WorkflowAll all;

    /**
     * Preferences for different communication channels
     */
    @JsonProperty("channels")
    private Map<String, ChannelPreferenceDto> channels;

    @JsonCreator
    public PreferencesRequestDtoWorkflow(
            @JsonProperty("all") @Nonnull WorkflowAll all,
            @JsonProperty("channels") @Nonnull Map<String, ChannelPreferenceDto> channels) {
        channels = Utils.emptyMapIfNull(channels);
        this.all = Optional.ofNullable(all)
            .orElseThrow(() -> new IllegalArgumentException("all cannot be null"));
        this.channels = Optional.ofNullable(channels)
            .orElseThrow(() -> new IllegalArgumentException("channels cannot be null"));
    }

    /**
     * A preference for the workflow. The values specified here will be used if no preference is specified
     * for a channel.
     */
    public WorkflowAll all() {
        return this.all;
    }

    /**
     * Preferences for different communication channels
     */
    public Map<String, ChannelPreferenceDto> channels() {
        return this.channels;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A preference for the workflow. The values specified here will be used if no preference is specified
     * for a channel.
     */
    public PreferencesRequestDtoWorkflow withAll(@Nonnull WorkflowAll all) {
        this.all = Utils.checkNotNull(all, "all");
        return this;
    }


    /**
     * Preferences for different communication channels
     */
    public PreferencesRequestDtoWorkflow withChannels(@Nonnull Map<String, ChannelPreferenceDto> channels) {
        this.channels = Utils.checkNotNull(channels, "channels");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PreferencesRequestDtoWorkflow other = (PreferencesRequestDtoWorkflow) o;
        return 
            Utils.enhancedDeepEquals(this.all, other.all) &&
            Utils.enhancedDeepEquals(this.channels, other.channels);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            all, channels);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PreferencesRequestDtoWorkflow.class,
                "all", all,
                "channels", channels);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private WorkflowAll all;

        private Map<String, ChannelPreferenceDto> channels;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * A preference for the workflow. The values specified here will be used if no preference is specified
         * for a channel.
         */
        public Builder all(@Nonnull WorkflowAll all) {
            this.all = Utils.checkNotNull(all, "all");
            return this;
        }

        /**
         * Preferences for different communication channels
         */
        public Builder channels(@Nonnull Map<String, ChannelPreferenceDto> channels) {
            this.channels = Utils.checkNotNull(channels, "channels");
            return this;
        }

        public PreferencesRequestDtoWorkflow build() {
            return new PreferencesRequestDtoWorkflow(
                all, channels);
        }

    }
}
