/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
/**
 * ProvidersIdEnum
 * 
 * <p>Provider ID of the job
 */
public class ProvidersIdEnum {

    public static final ProvidersIdEnum EMAILJS = new ProvidersIdEnum("emailjs");
    public static final ProvidersIdEnum MAILGUN = new ProvidersIdEnum("mailgun");
    public static final ProvidersIdEnum MAILJET = new ProvidersIdEnum("mailjet");
    public static final ProvidersIdEnum MANDRILL = new ProvidersIdEnum("mandrill");
    public static final ProvidersIdEnum NODEMAILER = new ProvidersIdEnum("nodemailer");
    public static final ProvidersIdEnum POSTMARK = new ProvidersIdEnum("postmark");
    public static final ProvidersIdEnum SENDGRID = new ProvidersIdEnum("sendgrid");
    public static final ProvidersIdEnum SENDINBLUE = new ProvidersIdEnum("sendinblue");
    public static final ProvidersIdEnum SES = new ProvidersIdEnum("ses");
    public static final ProvidersIdEnum NETCORE = new ProvidersIdEnum("netcore");
    public static final ProvidersIdEnum INFOBIP_EMAIL = new ProvidersIdEnum("infobip-email");
    public static final ProvidersIdEnum RESEND = new ProvidersIdEnum("resend");
    public static final ProvidersIdEnum PLUNK = new ProvidersIdEnum("plunk");
    public static final ProvidersIdEnum MAILERSEND = new ProvidersIdEnum("mailersend");
    public static final ProvidersIdEnum MAILTRAP = new ProvidersIdEnum("mailtrap");
    public static final ProvidersIdEnum CLICKATELL = new ProvidersIdEnum("clickatell");
    public static final ProvidersIdEnum OUTLOOK365 = new ProvidersIdEnum("outlook365");
    public static final ProvidersIdEnum NOVU_EMAIL = new ProvidersIdEnum("novu-email");
    public static final ProvidersIdEnum SPARKPOST = new ProvidersIdEnum("sparkpost");
    public static final ProvidersIdEnum EMAIL_WEBHOOK = new ProvidersIdEnum("email-webhook");
    public static final ProvidersIdEnum BRAZE = new ProvidersIdEnum("braze");
    public static final ProvidersIdEnum NOVU_EMAIL_AGENT = new ProvidersIdEnum("novu-email-agent");
    public static final ProvidersIdEnum NEXMO = new ProvidersIdEnum("nexmo");
    public static final ProvidersIdEnum PLIVO = new ProvidersIdEnum("plivo");
    public static final ProvidersIdEnum SMS77 = new ProvidersIdEnum("sms77");
    public static final ProvidersIdEnum SMS_CENTRAL = new ProvidersIdEnum("sms-central");
    public static final ProvidersIdEnum SNS = new ProvidersIdEnum("sns");
    public static final ProvidersIdEnum TELNYX = new ProvidersIdEnum("telnyx");
    public static final ProvidersIdEnum TWILIO = new ProvidersIdEnum("twilio");
    public static final ProvidersIdEnum GUPSHUP = new ProvidersIdEnum("gupshup");
    public static final ProvidersIdEnum FIRETEXT = new ProvidersIdEnum("firetext");
    public static final ProvidersIdEnum INFOBIP_SMS = new ProvidersIdEnum("infobip-sms");
    public static final ProvidersIdEnum BURST_SMS = new ProvidersIdEnum("burst-sms");
    public static final ProvidersIdEnum BULK_SMS = new ProvidersIdEnum("bulk-sms");
    public static final ProvidersIdEnum ISEND_SMS = new ProvidersIdEnum("isend-sms");
    public static final ProvidersIdEnum FORTY_SIX_ELKS = new ProvidersIdEnum("forty-six-elks");
    public static final ProvidersIdEnum KANNEL = new ProvidersIdEnum("kannel");
    public static final ProvidersIdEnum MAQSAM = new ProvidersIdEnum("maqsam");
    public static final ProvidersIdEnum TERMII = new ProvidersIdEnum("termii");
    public static final ProvidersIdEnum AFRICAS_TALKING = new ProvidersIdEnum("africas-talking");
    public static final ProvidersIdEnum NOVU_SMS = new ProvidersIdEnum("novu-sms");
    public static final ProvidersIdEnum SENDCHAMP = new ProvidersIdEnum("sendchamp");
    public static final ProvidersIdEnum GENERIC_SMS = new ProvidersIdEnum("generic-sms");
    public static final ProvidersIdEnum CLICKSEND = new ProvidersIdEnum("clicksend");
    public static final ProvidersIdEnum BANDWIDTH = new ProvidersIdEnum("bandwidth");
    public static final ProvidersIdEnum MESSAGEBIRD = new ProvidersIdEnum("messagebird");
    public static final ProvidersIdEnum SIMPLETEXTING = new ProvidersIdEnum("simpletexting");
    public static final ProvidersIdEnum AZURE_SMS = new ProvidersIdEnum("azure-sms");
    public static final ProvidersIdEnum RING_CENTRAL = new ProvidersIdEnum("ring-central");
    public static final ProvidersIdEnum BREVO_SMS = new ProvidersIdEnum("brevo-sms");
    public static final ProvidersIdEnum EAZY_SMS = new ProvidersIdEnum("eazy-sms");
    public static final ProvidersIdEnum MOBISHASTRA = new ProvidersIdEnum("mobishastra");
    public static final ProvidersIdEnum AFRO_MESSAGE = new ProvidersIdEnum("afro-message");
    public static final ProvidersIdEnum UNIFONIC = new ProvidersIdEnum("unifonic");
    public static final ProvidersIdEnum SMSMODE = new ProvidersIdEnum("smsmode");
    public static final ProvidersIdEnum IMEDIA = new ProvidersIdEnum("imedia");
    public static final ProvidersIdEnum SINCH = new ProvidersIdEnum("sinch");
    public static final ProvidersIdEnum ISENDPRO_SMS = new ProvidersIdEnum("isendpro-sms");
    public static final ProvidersIdEnum CM_TELECOM = new ProvidersIdEnum("cm-telecom");
    public static final ProvidersIdEnum FCM = new ProvidersIdEnum("fcm");
    public static final ProvidersIdEnum APNS = new ProvidersIdEnum("apns");
    public static final ProvidersIdEnum EXPO = new ProvidersIdEnum("expo");
    public static final ProvidersIdEnum ONE_SIGNAL = new ProvidersIdEnum("one-signal");
    public static final ProvidersIdEnum PUSHPAD = new ProvidersIdEnum("pushpad");
    public static final ProvidersIdEnum PUSH_WEBHOOK = new ProvidersIdEnum("push-webhook");
    public static final ProvidersIdEnum PUSHER_BEAMS = new ProvidersIdEnum("pusher-beams");
    public static final ProvidersIdEnum APPIO = new ProvidersIdEnum("appio");
    public static final ProvidersIdEnum NOVU = new ProvidersIdEnum("novu");
    public static final ProvidersIdEnum SLACK = new ProvidersIdEnum("slack");
    public static final ProvidersIdEnum DISCORD = new ProvidersIdEnum("discord");
    public static final ProvidersIdEnum MSTEAMS = new ProvidersIdEnum("msteams");
    public static final ProvidersIdEnum MATTERMOST = new ProvidersIdEnum("mattermost");
    public static final ProvidersIdEnum RYVER = new ProvidersIdEnum("ryver");
    public static final ProvidersIdEnum ZULIP = new ProvidersIdEnum("zulip");
    public static final ProvidersIdEnum GRAFANA_ON_CALL = new ProvidersIdEnum("grafana-on-call");
    public static final ProvidersIdEnum GETSTREAM = new ProvidersIdEnum("getstream");
    public static final ProvidersIdEnum ROCKET_CHAT = new ProvidersIdEnum("rocket-chat");
    public static final ProvidersIdEnum WHATSAPP_BUSINESS = new ProvidersIdEnum("whatsapp-business");
    public static final ProvidersIdEnum CHAT_WEBHOOK = new ProvidersIdEnum("chat-webhook");
    public static final ProvidersIdEnum NOVU_SLACK = new ProvidersIdEnum("novu-slack");
    public static final ProvidersIdEnum ANTHROPIC = new ProvidersIdEnum("anthropic");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, ProvidersIdEnum> values = createValuesMap();
    private static final Map<String, ProvidersIdEnumEnum> enums = createEnumsMap();

    private final String value;

    private ProvidersIdEnum(String value) {
        this.value = value;
    }

    /**
     * Returns a ProvidersIdEnum with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as ProvidersIdEnum
     */ 
    @JsonCreator
    public static ProvidersIdEnum of(String value) {
        synchronized (ProvidersIdEnum.class) {
            return values.computeIfAbsent(value, v -> new ProvidersIdEnum(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<ProvidersIdEnumEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        ProvidersIdEnum other = (ProvidersIdEnum) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "ProvidersIdEnum [value=" + value + "]";
    }

    // return an array just like an enum
    public static ProvidersIdEnum[] values() {
        synchronized (ProvidersIdEnum.class) {
            return values.values().toArray(new ProvidersIdEnum[] {});
        }
    }

    private static final Map<String, ProvidersIdEnum> createValuesMap() {
        Map<String, ProvidersIdEnum> map = new LinkedHashMap<>();
        map.put("emailjs", EMAILJS);
        map.put("mailgun", MAILGUN);
        map.put("mailjet", MAILJET);
        map.put("mandrill", MANDRILL);
        map.put("nodemailer", NODEMAILER);
        map.put("postmark", POSTMARK);
        map.put("sendgrid", SENDGRID);
        map.put("sendinblue", SENDINBLUE);
        map.put("ses", SES);
        map.put("netcore", NETCORE);
        map.put("infobip-email", INFOBIP_EMAIL);
        map.put("resend", RESEND);
        map.put("plunk", PLUNK);
        map.put("mailersend", MAILERSEND);
        map.put("mailtrap", MAILTRAP);
        map.put("clickatell", CLICKATELL);
        map.put("outlook365", OUTLOOK365);
        map.put("novu-email", NOVU_EMAIL);
        map.put("sparkpost", SPARKPOST);
        map.put("email-webhook", EMAIL_WEBHOOK);
        map.put("braze", BRAZE);
        map.put("novu-email-agent", NOVU_EMAIL_AGENT);
        map.put("nexmo", NEXMO);
        map.put("plivo", PLIVO);
        map.put("sms77", SMS77);
        map.put("sms-central", SMS_CENTRAL);
        map.put("sns", SNS);
        map.put("telnyx", TELNYX);
        map.put("twilio", TWILIO);
        map.put("gupshup", GUPSHUP);
        map.put("firetext", FIRETEXT);
        map.put("infobip-sms", INFOBIP_SMS);
        map.put("burst-sms", BURST_SMS);
        map.put("bulk-sms", BULK_SMS);
        map.put("isend-sms", ISEND_SMS);
        map.put("forty-six-elks", FORTY_SIX_ELKS);
        map.put("kannel", KANNEL);
        map.put("maqsam", MAQSAM);
        map.put("termii", TERMII);
        map.put("africas-talking", AFRICAS_TALKING);
        map.put("novu-sms", NOVU_SMS);
        map.put("sendchamp", SENDCHAMP);
        map.put("generic-sms", GENERIC_SMS);
        map.put("clicksend", CLICKSEND);
        map.put("bandwidth", BANDWIDTH);
        map.put("messagebird", MESSAGEBIRD);
        map.put("simpletexting", SIMPLETEXTING);
        map.put("azure-sms", AZURE_SMS);
        map.put("ring-central", RING_CENTRAL);
        map.put("brevo-sms", BREVO_SMS);
        map.put("eazy-sms", EAZY_SMS);
        map.put("mobishastra", MOBISHASTRA);
        map.put("afro-message", AFRO_MESSAGE);
        map.put("unifonic", UNIFONIC);
        map.put("smsmode", SMSMODE);
        map.put("imedia", IMEDIA);
        map.put("sinch", SINCH);
        map.put("isendpro-sms", ISENDPRO_SMS);
        map.put("cm-telecom", CM_TELECOM);
        map.put("fcm", FCM);
        map.put("apns", APNS);
        map.put("expo", EXPO);
        map.put("one-signal", ONE_SIGNAL);
        map.put("pushpad", PUSHPAD);
        map.put("push-webhook", PUSH_WEBHOOK);
        map.put("pusher-beams", PUSHER_BEAMS);
        map.put("appio", APPIO);
        map.put("novu", NOVU);
        map.put("slack", SLACK);
        map.put("discord", DISCORD);
        map.put("msteams", MSTEAMS);
        map.put("mattermost", MATTERMOST);
        map.put("ryver", RYVER);
        map.put("zulip", ZULIP);
        map.put("grafana-on-call", GRAFANA_ON_CALL);
        map.put("getstream", GETSTREAM);
        map.put("rocket-chat", ROCKET_CHAT);
        map.put("whatsapp-business", WHATSAPP_BUSINESS);
        map.put("chat-webhook", CHAT_WEBHOOK);
        map.put("novu-slack", NOVU_SLACK);
        map.put("anthropic", ANTHROPIC);
        return map;
    }

    private static final Map<String, ProvidersIdEnumEnum> createEnumsMap() {
        Map<String, ProvidersIdEnumEnum> map = new HashMap<>();
        map.put("emailjs", ProvidersIdEnumEnum.EMAILJS);
        map.put("mailgun", ProvidersIdEnumEnum.MAILGUN);
        map.put("mailjet", ProvidersIdEnumEnum.MAILJET);
        map.put("mandrill", ProvidersIdEnumEnum.MANDRILL);
        map.put("nodemailer", ProvidersIdEnumEnum.NODEMAILER);
        map.put("postmark", ProvidersIdEnumEnum.POSTMARK);
        map.put("sendgrid", ProvidersIdEnumEnum.SENDGRID);
        map.put("sendinblue", ProvidersIdEnumEnum.SENDINBLUE);
        map.put("ses", ProvidersIdEnumEnum.SES);
        map.put("netcore", ProvidersIdEnumEnum.NETCORE);
        map.put("infobip-email", ProvidersIdEnumEnum.INFOBIP_EMAIL);
        map.put("resend", ProvidersIdEnumEnum.RESEND);
        map.put("plunk", ProvidersIdEnumEnum.PLUNK);
        map.put("mailersend", ProvidersIdEnumEnum.MAILERSEND);
        map.put("mailtrap", ProvidersIdEnumEnum.MAILTRAP);
        map.put("clickatell", ProvidersIdEnumEnum.CLICKATELL);
        map.put("outlook365", ProvidersIdEnumEnum.OUTLOOK365);
        map.put("novu-email", ProvidersIdEnumEnum.NOVU_EMAIL);
        map.put("sparkpost", ProvidersIdEnumEnum.SPARKPOST);
        map.put("email-webhook", ProvidersIdEnumEnum.EMAIL_WEBHOOK);
        map.put("braze", ProvidersIdEnumEnum.BRAZE);
        map.put("novu-email-agent", ProvidersIdEnumEnum.NOVU_EMAIL_AGENT);
        map.put("nexmo", ProvidersIdEnumEnum.NEXMO);
        map.put("plivo", ProvidersIdEnumEnum.PLIVO);
        map.put("sms77", ProvidersIdEnumEnum.SMS77);
        map.put("sms-central", ProvidersIdEnumEnum.SMS_CENTRAL);
        map.put("sns", ProvidersIdEnumEnum.SNS);
        map.put("telnyx", ProvidersIdEnumEnum.TELNYX);
        map.put("twilio", ProvidersIdEnumEnum.TWILIO);
        map.put("gupshup", ProvidersIdEnumEnum.GUPSHUP);
        map.put("firetext", ProvidersIdEnumEnum.FIRETEXT);
        map.put("infobip-sms", ProvidersIdEnumEnum.INFOBIP_SMS);
        map.put("burst-sms", ProvidersIdEnumEnum.BURST_SMS);
        map.put("bulk-sms", ProvidersIdEnumEnum.BULK_SMS);
        map.put("isend-sms", ProvidersIdEnumEnum.ISEND_SMS);
        map.put("forty-six-elks", ProvidersIdEnumEnum.FORTY_SIX_ELKS);
        map.put("kannel", ProvidersIdEnumEnum.KANNEL);
        map.put("maqsam", ProvidersIdEnumEnum.MAQSAM);
        map.put("termii", ProvidersIdEnumEnum.TERMII);
        map.put("africas-talking", ProvidersIdEnumEnum.AFRICAS_TALKING);
        map.put("novu-sms", ProvidersIdEnumEnum.NOVU_SMS);
        map.put("sendchamp", ProvidersIdEnumEnum.SENDCHAMP);
        map.put("generic-sms", ProvidersIdEnumEnum.GENERIC_SMS);
        map.put("clicksend", ProvidersIdEnumEnum.CLICKSEND);
        map.put("bandwidth", ProvidersIdEnumEnum.BANDWIDTH);
        map.put("messagebird", ProvidersIdEnumEnum.MESSAGEBIRD);
        map.put("simpletexting", ProvidersIdEnumEnum.SIMPLETEXTING);
        map.put("azure-sms", ProvidersIdEnumEnum.AZURE_SMS);
        map.put("ring-central", ProvidersIdEnumEnum.RING_CENTRAL);
        map.put("brevo-sms", ProvidersIdEnumEnum.BREVO_SMS);
        map.put("eazy-sms", ProvidersIdEnumEnum.EAZY_SMS);
        map.put("mobishastra", ProvidersIdEnumEnum.MOBISHASTRA);
        map.put("afro-message", ProvidersIdEnumEnum.AFRO_MESSAGE);
        map.put("unifonic", ProvidersIdEnumEnum.UNIFONIC);
        map.put("smsmode", ProvidersIdEnumEnum.SMSMODE);
        map.put("imedia", ProvidersIdEnumEnum.IMEDIA);
        map.put("sinch", ProvidersIdEnumEnum.SINCH);
        map.put("isendpro-sms", ProvidersIdEnumEnum.ISENDPRO_SMS);
        map.put("cm-telecom", ProvidersIdEnumEnum.CM_TELECOM);
        map.put("fcm", ProvidersIdEnumEnum.FCM);
        map.put("apns", ProvidersIdEnumEnum.APNS);
        map.put("expo", ProvidersIdEnumEnum.EXPO);
        map.put("one-signal", ProvidersIdEnumEnum.ONE_SIGNAL);
        map.put("pushpad", ProvidersIdEnumEnum.PUSHPAD);
        map.put("push-webhook", ProvidersIdEnumEnum.PUSH_WEBHOOK);
        map.put("pusher-beams", ProvidersIdEnumEnum.PUSHER_BEAMS);
        map.put("appio", ProvidersIdEnumEnum.APPIO);
        map.put("novu", ProvidersIdEnumEnum.NOVU);
        map.put("slack", ProvidersIdEnumEnum.SLACK);
        map.put("discord", ProvidersIdEnumEnum.DISCORD);
        map.put("msteams", ProvidersIdEnumEnum.MSTEAMS);
        map.put("mattermost", ProvidersIdEnumEnum.MATTERMOST);
        map.put("ryver", ProvidersIdEnumEnum.RYVER);
        map.put("zulip", ProvidersIdEnumEnum.ZULIP);
        map.put("grafana-on-call", ProvidersIdEnumEnum.GRAFANA_ON_CALL);
        map.put("getstream", ProvidersIdEnumEnum.GETSTREAM);
        map.put("rocket-chat", ProvidersIdEnumEnum.ROCKET_CHAT);
        map.put("whatsapp-business", ProvidersIdEnumEnum.WHATSAPP_BUSINESS);
        map.put("chat-webhook", ProvidersIdEnumEnum.CHAT_WEBHOOK);
        map.put("novu-slack", ProvidersIdEnumEnum.NOVU_SLACK);
        map.put("anthropic", ProvidersIdEnumEnum.ANTHROPIC);
        return map;
    }
    
    
    public enum ProvidersIdEnumEnum {

        EMAILJS("emailjs"),
        MAILGUN("mailgun"),
        MAILJET("mailjet"),
        MANDRILL("mandrill"),
        NODEMAILER("nodemailer"),
        POSTMARK("postmark"),
        SENDGRID("sendgrid"),
        SENDINBLUE("sendinblue"),
        SES("ses"),
        NETCORE("netcore"),
        INFOBIP_EMAIL("infobip-email"),
        RESEND("resend"),
        PLUNK("plunk"),
        MAILERSEND("mailersend"),
        MAILTRAP("mailtrap"),
        CLICKATELL("clickatell"),
        OUTLOOK365("outlook365"),
        NOVU_EMAIL("novu-email"),
        SPARKPOST("sparkpost"),
        EMAIL_WEBHOOK("email-webhook"),
        BRAZE("braze"),
        NOVU_EMAIL_AGENT("novu-email-agent"),
        NEXMO("nexmo"),
        PLIVO("plivo"),
        SMS77("sms77"),
        SMS_CENTRAL("sms-central"),
        SNS("sns"),
        TELNYX("telnyx"),
        TWILIO("twilio"),
        GUPSHUP("gupshup"),
        FIRETEXT("firetext"),
        INFOBIP_SMS("infobip-sms"),
        BURST_SMS("burst-sms"),
        BULK_SMS("bulk-sms"),
        ISEND_SMS("isend-sms"),
        FORTY_SIX_ELKS("forty-six-elks"),
        KANNEL("kannel"),
        MAQSAM("maqsam"),
        TERMII("termii"),
        AFRICAS_TALKING("africas-talking"),
        NOVU_SMS("novu-sms"),
        SENDCHAMP("sendchamp"),
        GENERIC_SMS("generic-sms"),
        CLICKSEND("clicksend"),
        BANDWIDTH("bandwidth"),
        MESSAGEBIRD("messagebird"),
        SIMPLETEXTING("simpletexting"),
        AZURE_SMS("azure-sms"),
        RING_CENTRAL("ring-central"),
        BREVO_SMS("brevo-sms"),
        EAZY_SMS("eazy-sms"),
        MOBISHASTRA("mobishastra"),
        AFRO_MESSAGE("afro-message"),
        UNIFONIC("unifonic"),
        SMSMODE("smsmode"),
        IMEDIA("imedia"),
        SINCH("sinch"),
        ISENDPRO_SMS("isendpro-sms"),
        CM_TELECOM("cm-telecom"),
        FCM("fcm"),
        APNS("apns"),
        EXPO("expo"),
        ONE_SIGNAL("one-signal"),
        PUSHPAD("pushpad"),
        PUSH_WEBHOOK("push-webhook"),
        PUSHER_BEAMS("pusher-beams"),
        APPIO("appio"),
        NOVU("novu"),
        SLACK("slack"),
        DISCORD("discord"),
        MSTEAMS("msteams"),
        MATTERMOST("mattermost"),
        RYVER("ryver"),
        ZULIP("zulip"),
        GRAFANA_ON_CALL("grafana-on-call"),
        GETSTREAM("getstream"),
        ROCKET_CHAT("rocket-chat"),
        WHATSAPP_BUSINESS("whatsapp-business"),
        CHAT_WEBHOOK("chat-webhook"),
        NOVU_SLACK("novu-slack"),
        ANTHROPIC("anthropic"),;

        private final String value;

        private ProvidersIdEnumEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

