/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class PushRenderOutput {
    /**
     * Subject of the push notification
     */
    @JsonProperty("subject")
    private String subject;

    /**
     * Body of the push notification
     */
    @JsonProperty("body")
    private String body;

    @JsonCreator
    public PushRenderOutput(
            @JsonProperty("subject") @Nonnull String subject,
            @JsonProperty("body") @Nonnull String body) {
        this.subject = Optional.ofNullable(subject)
            .orElseThrow(() -> new IllegalArgumentException("subject cannot be null"));
        this.body = Optional.ofNullable(body)
            .orElseThrow(() -> new IllegalArgumentException("body cannot be null"));
    }

    /**
     * Subject of the push notification
     */
    public String subject() {
        return this.subject;
    }

    /**
     * Body of the push notification
     */
    public String body() {
        return this.body;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Subject of the push notification
     */
    public PushRenderOutput withSubject(@Nonnull String subject) {
        this.subject = Utils.checkNotNull(subject, "subject");
        return this;
    }


    /**
     * Body of the push notification
     */
    public PushRenderOutput withBody(@Nonnull String body) {
        this.body = Utils.checkNotNull(body, "body");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PushRenderOutput other = (PushRenderOutput) o;
        return 
            Utils.enhancedDeepEquals(this.subject, other.subject) &&
            Utils.enhancedDeepEquals(this.body, other.body);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            subject, body);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PushRenderOutput.class,
                "subject", subject,
                "body", body);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String subject;

        private String body;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Subject of the push notification
         */
        public Builder subject(@Nonnull String subject) {
            this.subject = Utils.checkNotNull(subject, "subject");
            return this;
        }

        /**
         * Body of the push notification
         */
        public Builder body(@Nonnull String body) {
            this.body = Utils.checkNotNull(body, "body");
            return this;
        }

        public PushRenderOutput build() {
            return new PushRenderOutput(
                subject, body);
        }

    }
}
