/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.LazySingletonValue;
import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class RedirectDto {
    /**
     * URL for redirection. Must be a valid URL or start with / or &lbrace;&lbrace; variable &rbrace;&rbrace;.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("url")
    private String url;

    /**
     * Target window for the redirection.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("target")
    private Target target;

    @JsonCreator
    public RedirectDto(
            @JsonProperty("url") @Nullable String url,
            @JsonProperty("target") @Nullable Target target) {
        this.url = url;
        this.target = Optional.ofNullable(target)
            .orElse(Builder._SINGLETON_VALUE_Target.value());
    }
    
    public RedirectDto() {
        this(null, null);
    }

    /**
     * URL for redirection. Must be a valid URL or start with / or &lbrace;&lbrace; variable &rbrace;&rbrace;.
     */
    public Optional<String> url() {
        return Optional.ofNullable(this.url);
    }

    /**
     * Target window for the redirection.
     */
    public Optional<Target> target() {
        return Optional.ofNullable(this.target);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * URL for redirection. Must be a valid URL or start with / or &lbrace;&lbrace; variable &rbrace;&rbrace;.
     */
    public RedirectDto withUrl(@Nullable String url) {
        this.url = url;
        return this;
    }


    /**
     * Target window for the redirection.
     */
    public RedirectDto withTarget(@Nullable Target target) {
        this.target = target;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RedirectDto other = (RedirectDto) o;
        return 
            Utils.enhancedDeepEquals(this.url, other.url) &&
            Utils.enhancedDeepEquals(this.target, other.target);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            url, target);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RedirectDto.class,
                "url", url,
                "target", target);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String url;

        private Target target;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * URL for redirection. Must be a valid URL or start with / or &lbrace;&lbrace; variable &rbrace;&rbrace;.
         */
        public Builder url(@Nullable String url) {
            this.url = url;
            return this;
        }

        /**
         * Target window for the redirection.
         */
        public Builder target(@Nullable Target target) {
            this.target = target;
            return this;
        }

        public RedirectDto build() {
            return new RedirectDto(
                url, target);
        }


        private static final LazySingletonValue<Target> _SINGLETON_VALUE_Target =
                new LazySingletonValue<>(
                        "target",
                        "\"_self\"",
                        new TypeReference<Target>() {});
    }
}
