/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * ResourceDiffDtoTargetResource
 * 
 * <p>Target resource information
 */
public class ResourceDiffDtoTargetResource {
    /**
     * Resource ID (workflow ID or step ID)
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private JsonNullable<String> id;

    /**
     * Resource name (workflow name or step name)
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private JsonNullable<String> name;

    /**
     * User who last updated the resource
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("updatedBy")
    private JsonNullable<ResourceDiffDtoTargetResourceUpdatedBy> updatedBy;

    /**
     * When the resource was last updated
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("updatedAt")
    private JsonNullable<OffsetDateTime> updatedAt;

    @JsonCreator
    public ResourceDiffDtoTargetResource(
            @JsonProperty("id") @Nullable JsonNullable<String> id,
            @JsonProperty("name") @Nullable JsonNullable<String> name,
            @JsonProperty("updatedBy") @Nullable JsonNullable<ResourceDiffDtoTargetResourceUpdatedBy> updatedBy,
            @JsonProperty("updatedAt") @Nullable JsonNullable<OffsetDateTime> updatedAt) {
        this.id = Optional.ofNullable(id)
            .orElse(JsonNullable.undefined());
        this.name = Optional.ofNullable(name)
            .orElse(JsonNullable.undefined());
        this.updatedBy = Optional.ofNullable(updatedBy)
            .orElse(JsonNullable.undefined());
        this.updatedAt = Optional.ofNullable(updatedAt)
            .orElse(JsonNullable.undefined());
    }
    
    public ResourceDiffDtoTargetResource() {
        this(null, null, null,
            null);
    }

    /**
     * Resource ID (workflow ID or step ID)
     */
    public JsonNullable<String> id() {
        return this.id;
    }

    /**
     * Resource name (workflow name or step name)
     */
    public JsonNullable<String> name() {
        return this.name;
    }

    /**
     * User who last updated the resource
     */
    public JsonNullable<ResourceDiffDtoTargetResourceUpdatedBy> updatedBy() {
        return this.updatedBy;
    }

    /**
     * When the resource was last updated
     */
    public JsonNullable<OffsetDateTime> updatedAt() {
        return this.updatedAt;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Resource ID (workflow ID or step ID)
     */
    public ResourceDiffDtoTargetResource withId(@Nullable String id) {
        this.id = JsonNullable.of(id);
        return this;
    }


    /**
     * Resource name (workflow name or step name)
     */
    public ResourceDiffDtoTargetResource withName(@Nullable String name) {
        this.name = JsonNullable.of(name);
        return this;
    }


    /**
     * User who last updated the resource
     */
    public ResourceDiffDtoTargetResource withUpdatedBy(@Nullable ResourceDiffDtoTargetResourceUpdatedBy updatedBy) {
        this.updatedBy = JsonNullable.of(updatedBy);
        return this;
    }


    /**
     * When the resource was last updated
     */
    public ResourceDiffDtoTargetResource withUpdatedAt(@Nullable OffsetDateTime updatedAt) {
        this.updatedAt = JsonNullable.of(updatedAt);
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResourceDiffDtoTargetResource other = (ResourceDiffDtoTargetResource) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.updatedBy, other.updatedBy) &&
            Utils.enhancedDeepEquals(this.updatedAt, other.updatedAt);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, name, updatedBy,
            updatedAt);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ResourceDiffDtoTargetResource.class,
                "id", id,
                "name", name,
                "updatedBy", updatedBy,
                "updatedAt", updatedAt);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private JsonNullable<String> id;

        private JsonNullable<String> name;

        private JsonNullable<ResourceDiffDtoTargetResourceUpdatedBy> updatedBy;

        private JsonNullable<OffsetDateTime> updatedAt;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Resource ID (workflow ID or step ID)
         */
        public Builder id(@Nullable String id) {
            this.id = JsonNullable.of(id);
            return this;
        }

        /**
         * Resource name (workflow name or step name)
         */
        public Builder name(@Nullable String name) {
            this.name = JsonNullable.of(name);
            return this;
        }

        /**
         * User who last updated the resource
         */
        public Builder updatedBy(@Nullable ResourceDiffDtoTargetResourceUpdatedBy updatedBy) {
            this.updatedBy = JsonNullable.of(updatedBy);
            return this;
        }

        /**
         * When the resource was last updated
         */
        public Builder updatedAt(@Nullable OffsetDateTime updatedAt) {
            this.updatedAt = JsonNullable.of(updatedAt);
            return this;
        }

        public ResourceDiffDtoTargetResource build() {
            return new ResourceDiffDtoTargetResource(
                id, name, updatedBy,
                updatedAt);
        }

    }
}
