/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;


public class StepIssuesDto {
    /**
     * Controls-related issues
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("controls")
    private Map<String, List<StepContentIssueDto>> controls;

    /**
     * Integration-related issues
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("integration")
    private Map<String, List<StepIntegrationIssue>> integration;

    @JsonCreator
    public StepIssuesDto(
            @JsonProperty("controls") @Nullable Map<String, List<StepContentIssueDto>> controls,
            @JsonProperty("integration") @Nullable Map<String, List<StepIntegrationIssue>> integration) {
        this.controls = controls;
        this.integration = integration;
    }
    
    public StepIssuesDto() {
        this(null, null);
    }

    /**
     * Controls-related issues
     */
    public Optional<Map<String, List<StepContentIssueDto>>> controls() {
        return Optional.ofNullable(this.controls);
    }

    /**
     * Integration-related issues
     */
    public Optional<Map<String, List<StepIntegrationIssue>>> integration() {
        return Optional.ofNullable(this.integration);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Controls-related issues
     */
    public StepIssuesDto withControls(@Nullable Map<String, List<StepContentIssueDto>> controls) {
        this.controls = controls;
        return this;
    }


    /**
     * Integration-related issues
     */
    public StepIssuesDto withIntegration(@Nullable Map<String, List<StepIntegrationIssue>> integration) {
        this.integration = integration;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StepIssuesDto other = (StepIssuesDto) o;
        return 
            Utils.enhancedDeepEquals(this.controls, other.controls) &&
            Utils.enhancedDeepEquals(this.integration, other.integration);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            controls, integration);
    }
    
    @Override
    public String toString() {
        return Utils.toString(StepIssuesDto.class,
                "controls", controls,
                "integration", integration);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Map<String, List<StepContentIssueDto>> controls;

        private Map<String, List<StepIntegrationIssue>> integration;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Controls-related issues
         */
        public Builder controls(@Nullable Map<String, List<StepContentIssueDto>> controls) {
            this.controls = controls;
            return this;
        }

        /**
         * Integration-related issues
         */
        public Builder integration(@Nullable Map<String, List<StepIntegrationIssue>> integration) {
            this.integration = integration;
            return this;
        }

        public StepIssuesDto build() {
            return new StepIssuesDto(
                controls, integration);
        }

    }
}
