/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class SubscriptionResponseDto {
    /**
     * The unique identifier of the subscription
     */
    @JsonProperty("_id")
    private String id;

    /**
     * The identifier of the subscription
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("identifier")
    private String identifier;

    /**
     * The name of the subscription
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private String name;

    /**
     * The topic information
     */
    @JsonProperty("topic")
    private TopicDto topic;

    /**
     * The subscriber information
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("subscriber")
    private JsonNullable<SubscriptionResponseDtoSubscriber> subscriber;

    /**
     * The preferences for workflows in this subscription
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("preferences")
    private List<SubscriptionPreferenceDto> preferences;

    /**
     * Context keys that scope this subscription (e.g., tenant:org-a, project:proj-123)
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contextKeys")
    private List<String> contextKeys;

    /**
     * The creation date of the subscription
     */
    @JsonProperty("createdAt")
    private String createdAt;

    /**
     * The last update date of the subscription
     */
    @JsonProperty("updatedAt")
    private String updatedAt;

    @JsonCreator
    public SubscriptionResponseDto(
            @JsonProperty("_id") @Nonnull String id,
            @JsonProperty("identifier") @Nullable String identifier,
            @JsonProperty("name") @Nullable String name,
            @JsonProperty("topic") @Nonnull TopicDto topic,
            @JsonProperty("subscriber") @Nullable SubscriptionResponseDtoSubscriber subscriber,
            @JsonProperty("preferences") @Nullable List<SubscriptionPreferenceDto> preferences,
            @JsonProperty("contextKeys") @Nullable List<String> contextKeys,
            @JsonProperty("createdAt") @Nonnull String createdAt,
            @JsonProperty("updatedAt") @Nonnull String updatedAt) {
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.identifier = identifier;
        this.name = name;
        this.topic = Optional.ofNullable(topic)
            .orElseThrow(() -> new IllegalArgumentException("topic cannot be null"));
        this.subscriber = JsonNullable.of(subscriber);
        this.preferences = preferences;
        this.contextKeys = contextKeys;
        this.createdAt = Optional.ofNullable(createdAt)
            .orElseThrow(() -> new IllegalArgumentException("createdAt cannot be null"));
        this.updatedAt = Optional.ofNullable(updatedAt)
            .orElseThrow(() -> new IllegalArgumentException("updatedAt cannot be null"));
    }
    
    public SubscriptionResponseDto(
            @Nonnull String id,
            @Nonnull TopicDto topic,
            @Nonnull String createdAt,
            @Nonnull String updatedAt) {
        this(id, null, null,
            topic, null, null,
            null, createdAt, updatedAt);
    }

    /**
     * The unique identifier of the subscription
     */
    public String id() {
        return this.id;
    }

    /**
     * The identifier of the subscription
     */
    public Optional<String> identifier() {
        return Optional.ofNullable(this.identifier);
    }

    /**
     * The name of the subscription
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The topic information
     */
    public TopicDto topic() {
        return this.topic;
    }

    /**
     * The subscriber information
     */
    public JsonNullable<SubscriptionResponseDtoSubscriber> subscriber() {
        return this.subscriber;
    }

    /**
     * The preferences for workflows in this subscription
     */
    public Optional<List<SubscriptionPreferenceDto>> preferences() {
        return Optional.ofNullable(this.preferences);
    }

    /**
     * Context keys that scope this subscription (e.g., tenant:org-a, project:proj-123)
     */
    public Optional<List<String>> contextKeys() {
        return Optional.ofNullable(this.contextKeys);
    }

    /**
     * The creation date of the subscription
     */
    public String createdAt() {
        return this.createdAt;
    }

    /**
     * The last update date of the subscription
     */
    public String updatedAt() {
        return this.updatedAt;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The unique identifier of the subscription
     */
    public SubscriptionResponseDto withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    /**
     * The identifier of the subscription
     */
    public SubscriptionResponseDto withIdentifier(@Nullable String identifier) {
        this.identifier = identifier;
        return this;
    }


    /**
     * The name of the subscription
     */
    public SubscriptionResponseDto withName(@Nullable String name) {
        this.name = name;
        return this;
    }


    /**
     * The topic information
     */
    public SubscriptionResponseDto withTopic(@Nonnull TopicDto topic) {
        this.topic = Utils.checkNotNull(topic, "topic");
        return this;
    }


    /**
     * The subscriber information
     */
    public SubscriptionResponseDto withSubscriber(@Nullable SubscriptionResponseDtoSubscriber subscriber) {
        this.subscriber = JsonNullable.of(subscriber);
        return this;
    }


    /**
     * The preferences for workflows in this subscription
     */
    public SubscriptionResponseDto withPreferences(@Nullable List<SubscriptionPreferenceDto> preferences) {
        this.preferences = preferences;
        return this;
    }


    /**
     * Context keys that scope this subscription (e.g., tenant:org-a, project:proj-123)
     */
    public SubscriptionResponseDto withContextKeys(@Nullable List<String> contextKeys) {
        this.contextKeys = contextKeys;
        return this;
    }


    /**
     * The creation date of the subscription
     */
    public SubscriptionResponseDto withCreatedAt(@Nonnull String createdAt) {
        this.createdAt = Utils.checkNotNull(createdAt, "createdAt");
        return this;
    }


    /**
     * The last update date of the subscription
     */
    public SubscriptionResponseDto withUpdatedAt(@Nonnull String updatedAt) {
        this.updatedAt = Utils.checkNotNull(updatedAt, "updatedAt");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubscriptionResponseDto other = (SubscriptionResponseDto) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.identifier, other.identifier) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.topic, other.topic) &&
            Utils.enhancedDeepEquals(this.subscriber, other.subscriber) &&
            Utils.enhancedDeepEquals(this.preferences, other.preferences) &&
            Utils.enhancedDeepEquals(this.contextKeys, other.contextKeys) &&
            Utils.enhancedDeepEquals(this.createdAt, other.createdAt) &&
            Utils.enhancedDeepEquals(this.updatedAt, other.updatedAt);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, identifier, name,
            topic, subscriber, preferences,
            contextKeys, createdAt, updatedAt);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubscriptionResponseDto.class,
                "id", id,
                "identifier", identifier,
                "name", name,
                "topic", topic,
                "subscriber", subscriber,
                "preferences", preferences,
                "contextKeys", contextKeys,
                "createdAt", createdAt,
                "updatedAt", updatedAt);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String identifier;

        private String name;

        private TopicDto topic;

        private SubscriptionResponseDtoSubscriber subscriber;

        private List<SubscriptionPreferenceDto> preferences;

        private List<String> contextKeys;

        private String createdAt;

        private String updatedAt;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The unique identifier of the subscription
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        /**
         * The identifier of the subscription
         */
        public Builder identifier(@Nullable String identifier) {
            this.identifier = identifier;
            return this;
        }

        /**
         * The name of the subscription
         */
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        /**
         * The topic information
         */
        public Builder topic(@Nonnull TopicDto topic) {
            this.topic = Utils.checkNotNull(topic, "topic");
            return this;
        }

        /**
         * The subscriber information
         */
        public Builder subscriber(@Nullable SubscriptionResponseDtoSubscriber subscriber) {
            this.subscriber = subscriber;
            return this;
        }

        /**
         * The preferences for workflows in this subscription
         */
        public Builder preferences(@Nullable List<SubscriptionPreferenceDto> preferences) {
            this.preferences = preferences;
            return this;
        }

        /**
         * Context keys that scope this subscription (e.g., tenant:org-a, project:proj-123)
         */
        public Builder contextKeys(@Nullable List<String> contextKeys) {
            this.contextKeys = contextKeys;
            return this;
        }

        /**
         * The creation date of the subscription
         */
        public Builder createdAt(@Nonnull String createdAt) {
            this.createdAt = Utils.checkNotNull(createdAt, "createdAt");
            return this;
        }

        /**
         * The last update date of the subscription
         */
        public Builder updatedAt(@Nonnull String updatedAt) {
            this.updatedAt = Utils.checkNotNull(updatedAt, "updatedAt");
            return this;
        }

        public SubscriptionResponseDto build() {
            return new SubscriptionResponseDto(
                id, identifier, name,
                topic, subscriber, preferences,
                contextKeys, createdAt, updatedAt);
        }

    }
}
