/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.lang.Override;
import java.lang.String;

/**
 * SubscriptionPreferenceDtoData
 * 
 * <p>Custom data associated with the workflow
 */
public class SubscriptionPreferenceDtoData {
    @JsonCreator
    public SubscriptionPreferenceDtoData() {
    }

    public static Builder builder() {
        return new Builder();
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        return true;
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            );
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubscriptionPreferenceDtoData.class);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Builder() {
          // force use of static builder() method
        }

        public SubscriptionPreferenceDtoData build() {
            return new SubscriptionPreferenceDtoData(
                );
        }

    }
}
