/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class SubscriptionDetailsResponseDto {
    /**
     * The unique identifier of the subscription
     */
    @JsonProperty("id")
    private String id;

    /**
     * The identifier of the subscription
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("identifier")
    private String identifier;

    /**
     * The name of the subscription
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private String name;

    /**
     * The preferences/rules for the subscription
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("preferences")
    private List<SubscriptionPreferenceDto> preferences;

    /**
     * Context keys that scope this subscription (e.g., tenant:org-a, project:proj-123)
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contextKeys")
    private List<String> contextKeys;

    @JsonCreator
    public SubscriptionDetailsResponseDto(
            @JsonProperty("id") @Nonnull String id,
            @JsonProperty("identifier") @Nullable String identifier,
            @JsonProperty("name") @Nullable String name,
            @JsonProperty("preferences") @Nullable List<SubscriptionPreferenceDto> preferences,
            @JsonProperty("contextKeys") @Nullable List<String> contextKeys) {
        this.id = Optional.ofNullable(id)
            .orElseThrow(() -> new IllegalArgumentException("id cannot be null"));
        this.identifier = identifier;
        this.name = name;
        this.preferences = preferences;
        this.contextKeys = contextKeys;
    }
    
    public SubscriptionDetailsResponseDto(
            @Nonnull String id) {
        this(id, null, null,
            null, null);
    }

    /**
     * The unique identifier of the subscription
     */
    public String id() {
        return this.id;
    }

    /**
     * The identifier of the subscription
     */
    public Optional<String> identifier() {
        return Optional.ofNullable(this.identifier);
    }

    /**
     * The name of the subscription
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The preferences/rules for the subscription
     */
    public Optional<List<SubscriptionPreferenceDto>> preferences() {
        return Optional.ofNullable(this.preferences);
    }

    /**
     * Context keys that scope this subscription (e.g., tenant:org-a, project:proj-123)
     */
    public Optional<List<String>> contextKeys() {
        return Optional.ofNullable(this.contextKeys);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The unique identifier of the subscription
     */
    public SubscriptionDetailsResponseDto withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }


    /**
     * The identifier of the subscription
     */
    public SubscriptionDetailsResponseDto withIdentifier(@Nullable String identifier) {
        this.identifier = identifier;
        return this;
    }


    /**
     * The name of the subscription
     */
    public SubscriptionDetailsResponseDto withName(@Nullable String name) {
        this.name = name;
        return this;
    }


    /**
     * The preferences/rules for the subscription
     */
    public SubscriptionDetailsResponseDto withPreferences(@Nullable List<SubscriptionPreferenceDto> preferences) {
        this.preferences = preferences;
        return this;
    }


    /**
     * Context keys that scope this subscription (e.g., tenant:org-a, project:proj-123)
     */
    public SubscriptionDetailsResponseDto withContextKeys(@Nullable List<String> contextKeys) {
        this.contextKeys = contextKeys;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubscriptionDetailsResponseDto other = (SubscriptionDetailsResponseDto) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.identifier, other.identifier) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.preferences, other.preferences) &&
            Utils.enhancedDeepEquals(this.contextKeys, other.contextKeys);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, identifier, name,
            preferences, contextKeys);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubscriptionDetailsResponseDto.class,
                "id", id,
                "identifier", identifier,
                "name", name,
                "preferences", preferences,
                "contextKeys", contextKeys);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String identifier;

        private String name;

        private List<SubscriptionPreferenceDto> preferences;

        private List<String> contextKeys;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The unique identifier of the subscription
         */
        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        /**
         * The identifier of the subscription
         */
        public Builder identifier(@Nullable String identifier) {
            this.identifier = identifier;
            return this;
        }

        /**
         * The name of the subscription
         */
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }

        /**
         * The preferences/rules for the subscription
         */
        public Builder preferences(@Nullable List<SubscriptionPreferenceDto> preferences) {
            this.preferences = preferences;
            return this;
        }

        /**
         * Context keys that scope this subscription (e.g., tenant:org-a, project:proj-123)
         */
        public Builder contextKeys(@Nullable List<String> contextKeys) {
            this.contextKeys = contextKeys;
            return this;
        }

        public SubscriptionDetailsResponseDto build() {
            return new SubscriptionDetailsResponseDto(
                id, identifier, name,
                preferences, contextKeys);
        }

    }
}
