/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class SubscriptionErrorDto {
    /**
     * The subscriber ID that failed
     */
    @JsonProperty("subscriberId")
    private String subscriberId;

    /**
     * The error code
     */
    @JsonProperty("code")
    private String code;

    /**
     * The error message
     */
    @JsonProperty("message")
    private String message;

    @JsonCreator
    public SubscriptionErrorDto(
            @JsonProperty("subscriberId") @Nonnull String subscriberId,
            @JsonProperty("code") @Nonnull String code,
            @JsonProperty("message") @Nonnull String message) {
        this.subscriberId = Optional.ofNullable(subscriberId)
            .orElseThrow(() -> new IllegalArgumentException("subscriberId cannot be null"));
        this.code = Optional.ofNullable(code)
            .orElseThrow(() -> new IllegalArgumentException("code cannot be null"));
        this.message = Optional.ofNullable(message)
            .orElseThrow(() -> new IllegalArgumentException("message cannot be null"));
    }

    /**
     * The subscriber ID that failed
     */
    public String subscriberId() {
        return this.subscriberId;
    }

    /**
     * The error code
     */
    public String code() {
        return this.code;
    }

    /**
     * The error message
     */
    public String message() {
        return this.message;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The subscriber ID that failed
     */
    public SubscriptionErrorDto withSubscriberId(@Nonnull String subscriberId) {
        this.subscriberId = Utils.checkNotNull(subscriberId, "subscriberId");
        return this;
    }


    /**
     * The error code
     */
    public SubscriptionErrorDto withCode(@Nonnull String code) {
        this.code = Utils.checkNotNull(code, "code");
        return this;
    }


    /**
     * The error message
     */
    public SubscriptionErrorDto withMessage(@Nonnull String message) {
        this.message = Utils.checkNotNull(message, "message");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubscriptionErrorDto other = (SubscriptionErrorDto) o;
        return 
            Utils.enhancedDeepEquals(this.subscriberId, other.subscriberId) &&
            Utils.enhancedDeepEquals(this.code, other.code) &&
            Utils.enhancedDeepEquals(this.message, other.message);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            subscriberId, code, message);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubscriptionErrorDto.class,
                "subscriberId", subscriberId,
                "code", code,
                "message", message);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String subscriberId;

        private String code;

        private String message;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The subscriber ID that failed
         */
        public Builder subscriberId(@Nonnull String subscriberId) {
            this.subscriberId = Utils.checkNotNull(subscriberId, "subscriberId");
            return this;
        }

        /**
         * The error code
         */
        public Builder code(@Nonnull String code) {
            this.code = Utils.checkNotNull(code, "code");
            return this;
        }

        /**
         * The error message
         */
        public Builder message(@Nonnull String message) {
            this.message = Utils.checkNotNull(message, "message");
            return this;
        }

        public SubscriptionErrorDto build() {
            return new SubscriptionErrorDto(
                subscriberId, code, message);
        }

    }
}
