/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Override;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Wrapper for an "open" enum that can handle unknown values from API responses
 * without runtime errors. Instances are immutable singletons with reference equality.
 * Use {@code asEnum()} for switch expressions.
 */
public class TestDomainRouteResponseDtoType {

    public static final TestDomainRouteResponseDtoType AGENT = new TestDomainRouteResponseDtoType("agent");
    public static final TestDomainRouteResponseDtoType WEBHOOK = new TestDomainRouteResponseDtoType("webhook");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, TestDomainRouteResponseDtoType> values = createValuesMap();
    private static final Map<String, TestDomainRouteResponseDtoTypeEnum> enums = createEnumsMap();

    private final String value;

    private TestDomainRouteResponseDtoType(String value) {
        this.value = value;
    }

    /**
     * Returns a TestDomainRouteResponseDtoType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as TestDomainRouteResponseDtoType
     */ 
    @JsonCreator
    public static TestDomainRouteResponseDtoType of(String value) {
        synchronized (TestDomainRouteResponseDtoType.class) {
            return values.computeIfAbsent(value, v -> new TestDomainRouteResponseDtoType(v));
        }
    }

    @JsonValue
    public String value() {
        return value;
    }

    public Optional<TestDomainRouteResponseDtoTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        TestDomainRouteResponseDtoType other = (TestDomainRouteResponseDtoType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "TestDomainRouteResponseDtoType [value=" + value + "]";
    }

    // return an array just like an enum
    public static TestDomainRouteResponseDtoType[] values() {
        synchronized (TestDomainRouteResponseDtoType.class) {
            return values.values().toArray(new TestDomainRouteResponseDtoType[] {});
        }
    }

    private static final Map<String, TestDomainRouteResponseDtoType> createValuesMap() {
        Map<String, TestDomainRouteResponseDtoType> map = new LinkedHashMap<>();
        map.put("agent", AGENT);
        map.put("webhook", WEBHOOK);
        return map;
    }

    private static final Map<String, TestDomainRouteResponseDtoTypeEnum> createEnumsMap() {
        Map<String, TestDomainRouteResponseDtoTypeEnum> map = new HashMap<>();
        map.put("agent", TestDomainRouteResponseDtoTypeEnum.AGENT);
        map.put("webhook", TestDomainRouteResponseDtoTypeEnum.WEBHOOK);
        return map;
    }
    
    
    public enum TestDomainRouteResponseDtoTypeEnum {

        AGENT("agent"),
        WEBHOOK("webhook"),;

        private final String value;

        private TestDomainRouteResponseDtoTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

