/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class WebexRoomEndpointDto {
    /**
     * Webex room ID
     */
    @JsonProperty("roomId")
    private String roomId;

    /**
     * Optional Webex parent message ID for threaded replies
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("parentId")
    private String parentId;

    @JsonCreator
    public WebexRoomEndpointDto(
            @JsonProperty("roomId") @Nonnull String roomId,
            @JsonProperty("parentId") @Nullable String parentId) {
        this.roomId = Optional.ofNullable(roomId)
            .orElseThrow(() -> new IllegalArgumentException("roomId cannot be null"));
        this.parentId = parentId;
    }
    
    public WebexRoomEndpointDto(
            @Nonnull String roomId) {
        this(roomId, null);
    }

    /**
     * Webex room ID
     */
    public String roomId() {
        return this.roomId;
    }

    /**
     * Optional Webex parent message ID for threaded replies
     */
    public Optional<String> parentId() {
        return Optional.ofNullable(this.parentId);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Webex room ID
     */
    public WebexRoomEndpointDto withRoomId(@Nonnull String roomId) {
        this.roomId = Utils.checkNotNull(roomId, "roomId");
        return this;
    }


    /**
     * Optional Webex parent message ID for threaded replies
     */
    public WebexRoomEndpointDto withParentId(@Nullable String parentId) {
        this.parentId = parentId;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WebexRoomEndpointDto other = (WebexRoomEndpointDto) o;
        return 
            Utils.enhancedDeepEquals(this.roomId, other.roomId) &&
            Utils.enhancedDeepEquals(this.parentId, other.parentId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            roomId, parentId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(WebexRoomEndpointDto.class,
                "roomId", roomId,
                "parentId", parentId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String roomId;

        private String parentId;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Webex room ID
         */
        public Builder roomId(@Nonnull String roomId) {
            this.roomId = Utils.checkNotNull(roomId, "roomId");
            return this;
        }

        /**
         * Optional Webex parent message ID for threaded replies
         */
        public Builder parentId(@Nullable String parentId) {
            this.parentId = parentId;
            return this;
        }

        public WebexRoomEndpointDto build() {
            return new WebexRoomEndpointDto(
                roomId, parentId);
        }

    }
}
