/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class WorkflowPreferencesResponseDto {
    /**
     * User-specific workflow preferences
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("user")
    private JsonNullable<WorkflowPreferencesResponseDtoUser> user;

    /**
     * Default workflow preferences
     */
    @JsonProperty("default")
    private WorkflowPreferencesDto default_;

    @JsonCreator
    public WorkflowPreferencesResponseDto(
            @JsonProperty("user") @Nullable JsonNullable<WorkflowPreferencesResponseDtoUser> user,
            @JsonProperty("default") @Nonnull WorkflowPreferencesDto default_) {
        this.user = Optional.ofNullable(user)
            .orElse(JsonNullable.undefined());
        this.default_ = Optional.ofNullable(default_)
            .orElseThrow(() -> new IllegalArgumentException("default_ cannot be null"));
    }
    
    public WorkflowPreferencesResponseDto(
            @Nonnull WorkflowPreferencesDto default_) {
        this(null, default_);
    }

    /**
     * User-specific workflow preferences
     */
    public JsonNullable<WorkflowPreferencesResponseDtoUser> user() {
        return this.user;
    }

    /**
     * Default workflow preferences
     */
    public WorkflowPreferencesDto default_() {
        return this.default_;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * User-specific workflow preferences
     */
    public WorkflowPreferencesResponseDto withUser(@Nullable WorkflowPreferencesResponseDtoUser user) {
        this.user = JsonNullable.of(user);
        return this;
    }


    /**
     * Default workflow preferences
     */
    public WorkflowPreferencesResponseDto withDefault(@Nonnull WorkflowPreferencesDto default_) {
        this.default_ = Utils.checkNotNull(default_, "default_");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WorkflowPreferencesResponseDto other = (WorkflowPreferencesResponseDto) o;
        return 
            Utils.enhancedDeepEquals(this.user, other.user) &&
            Utils.enhancedDeepEquals(this.default_, other.default_);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            user, default_);
    }
    
    @Override
    public String toString() {
        return Utils.toString(WorkflowPreferencesResponseDto.class,
                "user", user,
                "default_", default_);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private JsonNullable<WorkflowPreferencesResponseDtoUser> user;

        private WorkflowPreferencesDto default_;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * User-specific workflow preferences
         */
        public Builder user(@Nullable WorkflowPreferencesResponseDtoUser user) {
            this.user = JsonNullable.of(user);
            return this;
        }

        /**
         * Default workflow preferences
         */
        public Builder default_(@Nonnull WorkflowPreferencesDto default_) {
            this.default_ = Utils.checkNotNull(default_, "default_");
            return this;
        }

        public WorkflowPreferencesResponseDto build() {
            return new WorkflowPreferencesResponseDto(
                user, default_);
        }

    }
}
