/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.components;

import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class WorkflowResponseDtoProviders {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("replyTo")
    private String replyTo;

    @JsonCreator
    public WorkflowResponseDtoProviders(
            @JsonProperty("replyTo") @Nullable String replyTo) {
        this.replyTo = replyTo;
    }
    
    public WorkflowResponseDtoProviders() {
        this(null);
    }

    public Optional<String> replyTo() {
        return Optional.ofNullable(this.replyTo);
    }

    public static Builder builder() {
        return new Builder();
    }


    public WorkflowResponseDtoProviders withReplyTo(@Nullable String replyTo) {
        this.replyTo = replyTo;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WorkflowResponseDtoProviders other = (WorkflowResponseDtoProviders) o;
        return 
            Utils.enhancedDeepEquals(this.replyTo, other.replyTo);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            replyTo);
    }
    
    @Override
    public String toString() {
        return Utils.toString(WorkflowResponseDtoProviders.class,
                "replyTo", replyTo);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String replyTo;

        private Builder() {
          // force use of static builder() method
        }

        public Builder replyTo(@Nullable String replyTo) {
            this.replyTo = replyTo;
            return this;
        }

        public WorkflowResponseDtoProviders build() {
            return new WorkflowResponseDtoProviders(
                replyTo);
        }

    }
}
