/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations;

import co.novu.models.components.CreateAgentRequestDto;
import co.novu.utils.SpeakeasyMetadata;
import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class AgentsControllerCreateAgentRequest {

    @SpeakeasyMetadata("header:style=simple,explode=false,name=Novu-Analytics-Source")
    private String novuAnalyticsSource;

    /**
     * A header for idempotency purposes
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")
    private String idempotencyKey;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private CreateAgentRequestDto body;

    @JsonCreator
    public AgentsControllerCreateAgentRequest(
            @Nonnull String novuAnalyticsSource,
            @Nullable String idempotencyKey,
            @Nonnull CreateAgentRequestDto body) {
        this.novuAnalyticsSource = Optional.ofNullable(novuAnalyticsSource)
            .orElseThrow(() -> new IllegalArgumentException("novuAnalyticsSource cannot be null"));
        this.idempotencyKey = idempotencyKey;
        this.body = Optional.ofNullable(body)
            .orElseThrow(() -> new IllegalArgumentException("body cannot be null"));
    }
    
    public AgentsControllerCreateAgentRequest(
            @Nonnull String novuAnalyticsSource,
            @Nonnull CreateAgentRequestDto body) {
        this(novuAnalyticsSource, null, body);
    }

    public String novuAnalyticsSource() {
        return this.novuAnalyticsSource;
    }

    /**
     * A header for idempotency purposes
     */
    public Optional<String> idempotencyKey() {
        return Optional.ofNullable(this.idempotencyKey);
    }

    public CreateAgentRequestDto body() {
        return this.body;
    }

    public static Builder builder() {
        return new Builder();
    }


    public AgentsControllerCreateAgentRequest withNovuAnalyticsSource(@Nonnull String novuAnalyticsSource) {
        this.novuAnalyticsSource = Utils.checkNotNull(novuAnalyticsSource, "novuAnalyticsSource");
        return this;
    }


    /**
     * A header for idempotency purposes
     */
    public AgentsControllerCreateAgentRequest withIdempotencyKey(@Nullable String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
    }


    public AgentsControllerCreateAgentRequest withBody(@Nonnull CreateAgentRequestDto body) {
        this.body = Utils.checkNotNull(body, "body");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AgentsControllerCreateAgentRequest other = (AgentsControllerCreateAgentRequest) o;
        return 
            Utils.enhancedDeepEquals(this.novuAnalyticsSource, other.novuAnalyticsSource) &&
            Utils.enhancedDeepEquals(this.idempotencyKey, other.idempotencyKey) &&
            Utils.enhancedDeepEquals(this.body, other.body);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            novuAnalyticsSource, idempotencyKey, body);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AgentsControllerCreateAgentRequest.class,
                "novuAnalyticsSource", novuAnalyticsSource,
                "idempotencyKey", idempotencyKey,
                "body", body);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String novuAnalyticsSource;

        private String idempotencyKey;

        private CreateAgentRequestDto body;

        private Builder() {
          // force use of static builder() method
        }

        public Builder novuAnalyticsSource(@Nonnull String novuAnalyticsSource) {
            this.novuAnalyticsSource = Utils.checkNotNull(novuAnalyticsSource, "novuAnalyticsSource");
            return this;
        }

        /**
         * A header for idempotency purposes
         */
        public Builder idempotencyKey(@Nullable String idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }

        public Builder body(@Nonnull CreateAgentRequestDto body) {
            this.body = Utils.checkNotNull(body, "body");
            return this;
        }

        public AgentsControllerCreateAgentRequest build() {
            return new AgentsControllerCreateAgentRequest(
                novuAnalyticsSource, idempotencyKey, body);
        }

    }
}
