/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations;

import co.novu.utils.SpeakeasyMetadata;
import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class DomainsControllerGetDomainRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=domain")
    private String domain;

    /**
     * A header for idempotency purposes
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")
    private String idempotencyKey;

    @JsonCreator
    public DomainsControllerGetDomainRequest(
            @Nonnull String domain,
            @Nullable String idempotencyKey) {
        this.domain = Optional.ofNullable(domain)
            .orElseThrow(() -> new IllegalArgumentException("domain cannot be null"));
        this.idempotencyKey = idempotencyKey;
    }
    
    public DomainsControllerGetDomainRequest(
            @Nonnull String domain) {
        this(domain, null);
    }

    public String domain() {
        return this.domain;
    }

    /**
     * A header for idempotency purposes
     */
    public Optional<String> idempotencyKey() {
        return Optional.ofNullable(this.idempotencyKey);
    }

    public static Builder builder() {
        return new Builder();
    }


    public DomainsControllerGetDomainRequest withDomain(@Nonnull String domain) {
        this.domain = Utils.checkNotNull(domain, "domain");
        return this;
    }


    /**
     * A header for idempotency purposes
     */
    public DomainsControllerGetDomainRequest withIdempotencyKey(@Nullable String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DomainsControllerGetDomainRequest other = (DomainsControllerGetDomainRequest) o;
        return 
            Utils.enhancedDeepEquals(this.domain, other.domain) &&
            Utils.enhancedDeepEquals(this.idempotencyKey, other.idempotencyKey);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            domain, idempotencyKey);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DomainsControllerGetDomainRequest.class,
                "domain", domain,
                "idempotencyKey", idempotencyKey);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String domain;

        private String idempotencyKey;

        private Builder() {
          // force use of static builder() method
        }

        public Builder domain(@Nonnull String domain) {
            this.domain = Utils.checkNotNull(domain, "domain");
            return this;
        }

        /**
         * A header for idempotency purposes
         */
        public Builder idempotencyKey(@Nullable String idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }

        public DomainsControllerGetDomainRequest build() {
            return new DomainsControllerGetDomainRequest(
                domain, idempotencyKey);
        }

    }
}
