/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations;

import static co.novu.operations.Operations.RequestOperation;

import co.novu.SDKConfiguration;
import co.novu.operations.DomainsControllerVerifyDomain;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import co.novu.utils.RetryConfig;
import co.novu.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;

public class DomainsControllerVerifyDomainRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final DomainsControllerVerifyDomainRequest.Builder pojoBuilder;
    private DomainsControllerVerifyDomainRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public DomainsControllerVerifyDomainRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = DomainsControllerVerifyDomainRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public DomainsControllerVerifyDomainRequestBuilder domain(@Nonnull String domain) {
        this.pojoBuilder.domain(domain);
        this._setterCalled = true;
        return this;
    }

    public DomainsControllerVerifyDomainRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public DomainsControllerVerifyDomainRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private DomainsControllerVerifyDomainRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public DomainsControllerVerifyDomainRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public DomainsControllerVerifyDomainResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<DomainsControllerVerifyDomainRequest, DomainsControllerVerifyDomainResponse> operation
              = new DomainsControllerVerifyDomain.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
