/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations;

import co.novu.utils.SpeakeasyMetadata;
import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class EnvironmentVariablesControllerDeleteEnvironmentVariableRequest {
    /**
     * The unique key of the environment variable (e.g. BASE_URL)
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=variableKey")
    private String variableKey;

    /**
     * A header for idempotency purposes
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")
    private String idempotencyKey;

    @JsonCreator
    public EnvironmentVariablesControllerDeleteEnvironmentVariableRequest(
            @Nonnull String variableKey,
            @Nullable String idempotencyKey) {
        this.variableKey = Optional.ofNullable(variableKey)
            .orElseThrow(() -> new IllegalArgumentException("variableKey cannot be null"));
        this.idempotencyKey = idempotencyKey;
    }
    
    public EnvironmentVariablesControllerDeleteEnvironmentVariableRequest(
            @Nonnull String variableKey) {
        this(variableKey, null);
    }

    /**
     * The unique key of the environment variable (e.g. BASE_URL)
     */
    public String variableKey() {
        return this.variableKey;
    }

    /**
     * A header for idempotency purposes
     */
    public Optional<String> idempotencyKey() {
        return Optional.ofNullable(this.idempotencyKey);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The unique key of the environment variable (e.g. BASE_URL)
     */
    public EnvironmentVariablesControllerDeleteEnvironmentVariableRequest withVariableKey(@Nonnull String variableKey) {
        this.variableKey = Utils.checkNotNull(variableKey, "variableKey");
        return this;
    }


    /**
     * A header for idempotency purposes
     */
    public EnvironmentVariablesControllerDeleteEnvironmentVariableRequest withIdempotencyKey(@Nullable String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EnvironmentVariablesControllerDeleteEnvironmentVariableRequest other = (EnvironmentVariablesControllerDeleteEnvironmentVariableRequest) o;
        return 
            Utils.enhancedDeepEquals(this.variableKey, other.variableKey) &&
            Utils.enhancedDeepEquals(this.idempotencyKey, other.idempotencyKey);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            variableKey, idempotencyKey);
    }
    
    @Override
    public String toString() {
        return Utils.toString(EnvironmentVariablesControllerDeleteEnvironmentVariableRequest.class,
                "variableKey", variableKey,
                "idempotencyKey", idempotencyKey);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String variableKey;

        private String idempotencyKey;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The unique key of the environment variable (e.g. BASE_URL)
         */
        public Builder variableKey(@Nonnull String variableKey) {
            this.variableKey = Utils.checkNotNull(variableKey, "variableKey");
            return this;
        }

        /**
         * A header for idempotency purposes
         */
        public Builder idempotencyKey(@Nullable String idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }

        public EnvironmentVariablesControllerDeleteEnvironmentVariableRequest build() {
            return new EnvironmentVariablesControllerDeleteEnvironmentVariableRequest(
                variableKey, idempotencyKey);
        }

    }
}
