/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations;

import static co.novu.operations.Operations.RequestOperation;

import co.novu.SDKConfiguration;
import co.novu.models.components.UpdateIntegrationRequestDto;
import co.novu.operations.IntegrationsControllerUpdateIntegrationById;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import co.novu.utils.RetryConfig;
import co.novu.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;

public class IntegrationsControllerUpdateIntegrationByIdRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final IntegrationsControllerUpdateIntegrationByIdRequest.Builder pojoBuilder;
    private IntegrationsControllerUpdateIntegrationByIdRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public IntegrationsControllerUpdateIntegrationByIdRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = IntegrationsControllerUpdateIntegrationByIdRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public IntegrationsControllerUpdateIntegrationByIdRequestBuilder integrationId(@Nonnull String integrationId) {
        this.pojoBuilder.integrationId(integrationId);
        this._setterCalled = true;
        return this;
    }

    public IntegrationsControllerUpdateIntegrationByIdRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public IntegrationsControllerUpdateIntegrationByIdRequestBuilder body(@Nonnull UpdateIntegrationRequestDto body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public IntegrationsControllerUpdateIntegrationByIdRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private IntegrationsControllerUpdateIntegrationByIdRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public IntegrationsControllerUpdateIntegrationByIdRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public IntegrationsControllerUpdateIntegrationByIdResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<IntegrationsControllerUpdateIntegrationByIdRequest, IntegrationsControllerUpdateIntegrationByIdResponse> operation
              = new IntegrationsControllerUpdateIntegrationById.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
