/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations;

import static co.novu.operations.Operations.RequestOperation;

import co.novu.SDKConfiguration;
import co.novu.models.components.PatchSubscriberRequestDto;
import co.novu.operations.SubscribersControllerPatchSubscriber;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import co.novu.utils.RetryConfig;
import co.novu.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;

public class SubscribersControllerPatchSubscriberRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final SubscribersControllerPatchSubscriberRequest.Builder pojoBuilder;
    private SubscribersControllerPatchSubscriberRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public SubscribersControllerPatchSubscriberRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = SubscribersControllerPatchSubscriberRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public SubscribersControllerPatchSubscriberRequestBuilder subscriberId(@Nonnull String subscriberId) {
        this.pojoBuilder.subscriberId(subscriberId);
        this._setterCalled = true;
        return this;
    }

    public SubscribersControllerPatchSubscriberRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public SubscribersControllerPatchSubscriberRequestBuilder body(@Nonnull PatchSubscriberRequestDto body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public SubscribersControllerPatchSubscriberRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private SubscribersControllerPatchSubscriberRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public SubscribersControllerPatchSubscriberRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public SubscribersControllerPatchSubscriberResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<SubscribersControllerPatchSubscriberRequest, SubscribersControllerPatchSubscriberResponse> operation
              = new SubscribersControllerPatchSubscriber.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
