/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations;

import co.novu.utils.SpeakeasyMetadata;
import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class SubscribersV1ControllerDeleteSubscriberCredentialsRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=subscriberId")
    private String subscriberId;


    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=providerId")
    private String providerId;

    /**
     * A header for idempotency purposes
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")
    private String idempotencyKey;

    @JsonCreator
    public SubscribersV1ControllerDeleteSubscriberCredentialsRequest(
            @Nonnull String subscriberId,
            @Nonnull String providerId,
            @Nullable String idempotencyKey) {
        this.subscriberId = Optional.ofNullable(subscriberId)
            .orElseThrow(() -> new IllegalArgumentException("subscriberId cannot be null"));
        this.providerId = Optional.ofNullable(providerId)
            .orElseThrow(() -> new IllegalArgumentException("providerId cannot be null"));
        this.idempotencyKey = idempotencyKey;
    }
    
    public SubscribersV1ControllerDeleteSubscriberCredentialsRequest(
            @Nonnull String subscriberId,
            @Nonnull String providerId) {
        this(subscriberId, providerId, null);
    }

    public String subscriberId() {
        return this.subscriberId;
    }

    public String providerId() {
        return this.providerId;
    }

    /**
     * A header for idempotency purposes
     */
    public Optional<String> idempotencyKey() {
        return Optional.ofNullable(this.idempotencyKey);
    }

    public static Builder builder() {
        return new Builder();
    }


    public SubscribersV1ControllerDeleteSubscriberCredentialsRequest withSubscriberId(@Nonnull String subscriberId) {
        this.subscriberId = Utils.checkNotNull(subscriberId, "subscriberId");
        return this;
    }


    public SubscribersV1ControllerDeleteSubscriberCredentialsRequest withProviderId(@Nonnull String providerId) {
        this.providerId = Utils.checkNotNull(providerId, "providerId");
        return this;
    }


    /**
     * A header for idempotency purposes
     */
    public SubscribersV1ControllerDeleteSubscriberCredentialsRequest withIdempotencyKey(@Nullable String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubscribersV1ControllerDeleteSubscriberCredentialsRequest other = (SubscribersV1ControllerDeleteSubscriberCredentialsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.subscriberId, other.subscriberId) &&
            Utils.enhancedDeepEquals(this.providerId, other.providerId) &&
            Utils.enhancedDeepEquals(this.idempotencyKey, other.idempotencyKey);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            subscriberId, providerId, idempotencyKey);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubscribersV1ControllerDeleteSubscriberCredentialsRequest.class,
                "subscriberId", subscriberId,
                "providerId", providerId,
                "idempotencyKey", idempotencyKey);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String subscriberId;

        private String providerId;

        private String idempotencyKey;

        private Builder() {
          // force use of static builder() method
        }

        public Builder subscriberId(@Nonnull String subscriberId) {
            this.subscriberId = Utils.checkNotNull(subscriberId, "subscriberId");
            return this;
        }

        public Builder providerId(@Nonnull String providerId) {
            this.providerId = Utils.checkNotNull(providerId, "providerId");
            return this;
        }

        /**
         * A header for idempotency purposes
         */
        public Builder idempotencyKey(@Nullable String idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }

        public SubscribersV1ControllerDeleteSubscriberCredentialsRequest build() {
            return new SubscribersV1ControllerDeleteSubscriberCredentialsRequest(
                subscriberId, providerId, idempotencyKey);
        }

    }
}
