/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations;

import static co.novu.operations.Operations.RequestOperation;

import co.novu.SDKConfiguration;
import co.novu.models.components.UpdateSubscriberChannelRequestDto;
import co.novu.operations.SubscribersV1ControllerModifySubscriberChannel;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import co.novu.utils.RetryConfig;
import co.novu.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;

public class SubscribersV1ControllerModifySubscriberChannelRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final SubscribersV1ControllerModifySubscriberChannelRequest.Builder pojoBuilder;
    private SubscribersV1ControllerModifySubscriberChannelRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public SubscribersV1ControllerModifySubscriberChannelRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = SubscribersV1ControllerModifySubscriberChannelRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public SubscribersV1ControllerModifySubscriberChannelRequestBuilder subscriberId(@Nonnull String subscriberId) {
        this.pojoBuilder.subscriberId(subscriberId);
        this._setterCalled = true;
        return this;
    }

    public SubscribersV1ControllerModifySubscriberChannelRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public SubscribersV1ControllerModifySubscriberChannelRequestBuilder body(@Nonnull UpdateSubscriberChannelRequestDto body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public SubscribersV1ControllerModifySubscriberChannelRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private SubscribersV1ControllerModifySubscriberChannelRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public SubscribersV1ControllerModifySubscriberChannelRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public SubscribersV1ControllerModifySubscriberChannelResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<SubscribersV1ControllerModifySubscriberChannelRequest, SubscribersV1ControllerModifySubscriberChannelResponse> operation
              = new SubscribersV1ControllerModifySubscriberChannel.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
