/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations;

import co.novu.utils.SpeakeasyMetadata;
import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class SubscribersControllerUnarchiveNotificationRequest {
    /**
     * The identifier of the subscriber
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=subscriberId")
    private String subscriberId;

    /**
     * The identifier of the notification
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=notificationId")
    private String notificationId;

    /**
     * Context keys for filtering
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=contextKeys")
    private List<String> contextKeys;

    /**
     * A header for idempotency purposes
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")
    private String idempotencyKey;

    @JsonCreator
    public SubscribersControllerUnarchiveNotificationRequest(
            @Nonnull String subscriberId,
            @Nonnull String notificationId,
            @Nullable List<String> contextKeys,
            @Nullable String idempotencyKey) {
        this.subscriberId = Optional.ofNullable(subscriberId)
            .orElseThrow(() -> new IllegalArgumentException("subscriberId cannot be null"));
        this.notificationId = Optional.ofNullable(notificationId)
            .orElseThrow(() -> new IllegalArgumentException("notificationId cannot be null"));
        this.contextKeys = contextKeys;
        this.idempotencyKey = idempotencyKey;
    }
    
    public SubscribersControllerUnarchiveNotificationRequest(
            @Nonnull String subscriberId,
            @Nonnull String notificationId) {
        this(subscriberId, notificationId, null,
            null);
    }

    /**
     * The identifier of the subscriber
     */
    public String subscriberId() {
        return this.subscriberId;
    }

    /**
     * The identifier of the notification
     */
    public String notificationId() {
        return this.notificationId;
    }

    /**
     * Context keys for filtering
     */
    public Optional<List<String>> contextKeys() {
        return Optional.ofNullable(this.contextKeys);
    }

    /**
     * A header for idempotency purposes
     */
    public Optional<String> idempotencyKey() {
        return Optional.ofNullable(this.idempotencyKey);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The identifier of the subscriber
     */
    public SubscribersControllerUnarchiveNotificationRequest withSubscriberId(@Nonnull String subscriberId) {
        this.subscriberId = Utils.checkNotNull(subscriberId, "subscriberId");
        return this;
    }


    /**
     * The identifier of the notification
     */
    public SubscribersControllerUnarchiveNotificationRequest withNotificationId(@Nonnull String notificationId) {
        this.notificationId = Utils.checkNotNull(notificationId, "notificationId");
        return this;
    }


    /**
     * Context keys for filtering
     */
    public SubscribersControllerUnarchiveNotificationRequest withContextKeys(@Nullable List<String> contextKeys) {
        this.contextKeys = contextKeys;
        return this;
    }


    /**
     * A header for idempotency purposes
     */
    public SubscribersControllerUnarchiveNotificationRequest withIdempotencyKey(@Nullable String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubscribersControllerUnarchiveNotificationRequest other = (SubscribersControllerUnarchiveNotificationRequest) o;
        return 
            Utils.enhancedDeepEquals(this.subscriberId, other.subscriberId) &&
            Utils.enhancedDeepEquals(this.notificationId, other.notificationId) &&
            Utils.enhancedDeepEquals(this.contextKeys, other.contextKeys) &&
            Utils.enhancedDeepEquals(this.idempotencyKey, other.idempotencyKey);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            subscriberId, notificationId, contextKeys,
            idempotencyKey);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubscribersControllerUnarchiveNotificationRequest.class,
                "subscriberId", subscriberId,
                "notificationId", notificationId,
                "contextKeys", contextKeys,
                "idempotencyKey", idempotencyKey);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String subscriberId;

        private String notificationId;

        private List<String> contextKeys;

        private String idempotencyKey;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The identifier of the subscriber
         */
        public Builder subscriberId(@Nonnull String subscriberId) {
            this.subscriberId = Utils.checkNotNull(subscriberId, "subscriberId");
            return this;
        }

        /**
         * The identifier of the notification
         */
        public Builder notificationId(@Nonnull String notificationId) {
            this.notificationId = Utils.checkNotNull(notificationId, "notificationId");
            return this;
        }

        /**
         * Context keys for filtering
         */
        public Builder contextKeys(@Nullable List<String> contextKeys) {
            this.contextKeys = contextKeys;
            return this;
        }

        /**
         * A header for idempotency purposes
         */
        public Builder idempotencyKey(@Nullable String idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }

        public SubscribersControllerUnarchiveNotificationRequest build() {
            return new SubscribersControllerUnarchiveNotificationRequest(
                subscriberId, notificationId, contextKeys,
                idempotencyKey);
        }

    }
}
