/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations;

import static co.novu.operations.Operations.RequestOperation;

import co.novu.SDKConfiguration;
import co.novu.models.components.BulkUpdateSubscriberPreferencesDto;
import co.novu.operations.SubscribersControllerBulkUpdateSubscriberPreferences;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import co.novu.utils.RetryConfig;
import co.novu.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;

public class SubscribersControllerBulkUpdateSubscriberPreferencesRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final SubscribersControllerBulkUpdateSubscriberPreferencesRequest.Builder pojoBuilder;
    private SubscribersControllerBulkUpdateSubscriberPreferencesRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public SubscribersControllerBulkUpdateSubscriberPreferencesRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = SubscribersControllerBulkUpdateSubscriberPreferencesRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public SubscribersControllerBulkUpdateSubscriberPreferencesRequestBuilder subscriberId(@Nonnull String subscriberId) {
        this.pojoBuilder.subscriberId(subscriberId);
        this._setterCalled = true;
        return this;
    }

    public SubscribersControllerBulkUpdateSubscriberPreferencesRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public SubscribersControllerBulkUpdateSubscriberPreferencesRequestBuilder body(@Nonnull BulkUpdateSubscriberPreferencesDto body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public SubscribersControllerBulkUpdateSubscriberPreferencesRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private SubscribersControllerBulkUpdateSubscriberPreferencesRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public SubscribersControllerBulkUpdateSubscriberPreferencesRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public SubscribersControllerBulkUpdateSubscriberPreferencesResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<SubscribersControllerBulkUpdateSubscriberPreferencesRequest, SubscribersControllerBulkUpdateSubscriberPreferencesResponse> operation
              = new SubscribersControllerBulkUpdateSubscriberPreferences.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
