/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations;

import co.novu.utils.SpeakeasyMetadata;
import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class SubscribersControllerListSubscriberTopicsRequest {
    /**
     * The identifier of the subscriber
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=subscriberId")
    private String subscriberId;

    /**
     * Cursor for pagination indicating the starting point after which to fetch results.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=after")
    private String after;

    /**
     * Cursor for pagination indicating the ending point before which to fetch results.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=before")
    private String before;

    /**
     * Limit the number of items to return (max 100)
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    private Double limit;

    /**
     * Direction of sorting
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=orderDirection")
    private SubscribersControllerListSubscriberTopicsOrderDirection orderDirection;

    /**
     * Field to order by
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=orderBy")
    private String orderBy;

    /**
     * Include cursor item in response
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=includeCursor")
    private Boolean includeCursor;

    /**
     * Filter by topic key
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=key")
    private String key;

    /**
     * Filter by exact context keys, order insensitive (format: "type:id")
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=contextKeys")
    private List<String> contextKeys;

    /**
     * A header for idempotency purposes
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")
    private String idempotencyKey;

    @JsonCreator
    public SubscribersControllerListSubscriberTopicsRequest(
            @Nonnull String subscriberId,
            @Nullable String after,
            @Nullable String before,
            @Nullable Double limit,
            @Nullable SubscribersControllerListSubscriberTopicsOrderDirection orderDirection,
            @Nullable String orderBy,
            @Nullable Boolean includeCursor,
            @Nullable String key,
            @Nullable List<String> contextKeys,
            @Nullable String idempotencyKey) {
        this.subscriberId = Optional.ofNullable(subscriberId)
            .orElseThrow(() -> new IllegalArgumentException("subscriberId cannot be null"));
        this.after = after;
        this.before = before;
        this.limit = limit;
        this.orderDirection = orderDirection;
        this.orderBy = orderBy;
        this.includeCursor = includeCursor;
        this.key = key;
        this.contextKeys = contextKeys;
        this.idempotencyKey = idempotencyKey;
    }
    
    public SubscribersControllerListSubscriberTopicsRequest(
            @Nonnull String subscriberId) {
        this(subscriberId, null, null,
            null, null, null,
            null, null, null,
            null);
    }

    /**
     * The identifier of the subscriber
     */
    public String subscriberId() {
        return this.subscriberId;
    }

    /**
     * Cursor for pagination indicating the starting point after which to fetch results.
     */
    public Optional<String> after() {
        return Optional.ofNullable(this.after);
    }

    /**
     * Cursor for pagination indicating the ending point before which to fetch results.
     */
    public Optional<String> before() {
        return Optional.ofNullable(this.before);
    }

    /**
     * Limit the number of items to return (max 100)
     */
    public Optional<Double> limit() {
        return Optional.ofNullable(this.limit);
    }

    /**
     * Direction of sorting
     */
    public Optional<SubscribersControllerListSubscriberTopicsOrderDirection> orderDirection() {
        return Optional.ofNullable(this.orderDirection);
    }

    /**
     * Field to order by
     */
    public Optional<String> orderBy() {
        return Optional.ofNullable(this.orderBy);
    }

    /**
     * Include cursor item in response
     */
    public Optional<Boolean> includeCursor() {
        return Optional.ofNullable(this.includeCursor);
    }

    /**
     * Filter by topic key
     */
    public Optional<String> key() {
        return Optional.ofNullable(this.key);
    }

    /**
     * Filter by exact context keys, order insensitive (format: "type:id")
     */
    public Optional<List<String>> contextKeys() {
        return Optional.ofNullable(this.contextKeys);
    }

    /**
     * A header for idempotency purposes
     */
    public Optional<String> idempotencyKey() {
        return Optional.ofNullable(this.idempotencyKey);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The identifier of the subscriber
     */
    public SubscribersControllerListSubscriberTopicsRequest withSubscriberId(@Nonnull String subscriberId) {
        this.subscriberId = Utils.checkNotNull(subscriberId, "subscriberId");
        return this;
    }


    /**
     * Cursor for pagination indicating the starting point after which to fetch results.
     */
    public SubscribersControllerListSubscriberTopicsRequest withAfter(@Nullable String after) {
        this.after = after;
        return this;
    }


    /**
     * Cursor for pagination indicating the ending point before which to fetch results.
     */
    public SubscribersControllerListSubscriberTopicsRequest withBefore(@Nullable String before) {
        this.before = before;
        return this;
    }


    /**
     * Limit the number of items to return (max 100)
     */
    public SubscribersControllerListSubscriberTopicsRequest withLimit(@Nullable Double limit) {
        this.limit = limit;
        return this;
    }


    /**
     * Direction of sorting
     */
    public SubscribersControllerListSubscriberTopicsRequest withOrderDirection(@Nullable SubscribersControllerListSubscriberTopicsOrderDirection orderDirection) {
        this.orderDirection = orderDirection;
        return this;
    }


    /**
     * Field to order by
     */
    public SubscribersControllerListSubscriberTopicsRequest withOrderBy(@Nullable String orderBy) {
        this.orderBy = orderBy;
        return this;
    }


    /**
     * Include cursor item in response
     */
    public SubscribersControllerListSubscriberTopicsRequest withIncludeCursor(@Nullable Boolean includeCursor) {
        this.includeCursor = includeCursor;
        return this;
    }


    /**
     * Filter by topic key
     */
    public SubscribersControllerListSubscriberTopicsRequest withKey(@Nullable String key) {
        this.key = key;
        return this;
    }


    /**
     * Filter by exact context keys, order insensitive (format: "type:id")
     */
    public SubscribersControllerListSubscriberTopicsRequest withContextKeys(@Nullable List<String> contextKeys) {
        this.contextKeys = contextKeys;
        return this;
    }


    /**
     * A header for idempotency purposes
     */
    public SubscribersControllerListSubscriberTopicsRequest withIdempotencyKey(@Nullable String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubscribersControllerListSubscriberTopicsRequest other = (SubscribersControllerListSubscriberTopicsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.subscriberId, other.subscriberId) &&
            Utils.enhancedDeepEquals(this.after, other.after) &&
            Utils.enhancedDeepEquals(this.before, other.before) &&
            Utils.enhancedDeepEquals(this.limit, other.limit) &&
            Utils.enhancedDeepEquals(this.orderDirection, other.orderDirection) &&
            Utils.enhancedDeepEquals(this.orderBy, other.orderBy) &&
            Utils.enhancedDeepEquals(this.includeCursor, other.includeCursor) &&
            Utils.enhancedDeepEquals(this.key, other.key) &&
            Utils.enhancedDeepEquals(this.contextKeys, other.contextKeys) &&
            Utils.enhancedDeepEquals(this.idempotencyKey, other.idempotencyKey);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            subscriberId, after, before,
            limit, orderDirection, orderBy,
            includeCursor, key, contextKeys,
            idempotencyKey);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SubscribersControllerListSubscriberTopicsRequest.class,
                "subscriberId", subscriberId,
                "after", after,
                "before", before,
                "limit", limit,
                "orderDirection", orderDirection,
                "orderBy", orderBy,
                "includeCursor", includeCursor,
                "key", key,
                "contextKeys", contextKeys,
                "idempotencyKey", idempotencyKey);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String subscriberId;

        private String after;

        private String before;

        private Double limit;

        private SubscribersControllerListSubscriberTopicsOrderDirection orderDirection;

        private String orderBy;

        private Boolean includeCursor;

        private String key;

        private List<String> contextKeys;

        private String idempotencyKey;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The identifier of the subscriber
         */
        public Builder subscriberId(@Nonnull String subscriberId) {
            this.subscriberId = Utils.checkNotNull(subscriberId, "subscriberId");
            return this;
        }

        /**
         * Cursor for pagination indicating the starting point after which to fetch results.
         */
        public Builder after(@Nullable String after) {
            this.after = after;
            return this;
        }

        /**
         * Cursor for pagination indicating the ending point before which to fetch results.
         */
        public Builder before(@Nullable String before) {
            this.before = before;
            return this;
        }

        /**
         * Limit the number of items to return (max 100)
         */
        public Builder limit(@Nullable Double limit) {
            this.limit = limit;
            return this;
        }

        /**
         * Direction of sorting
         */
        public Builder orderDirection(@Nullable SubscribersControllerListSubscriberTopicsOrderDirection orderDirection) {
            this.orderDirection = orderDirection;
            return this;
        }

        /**
         * Field to order by
         */
        public Builder orderBy(@Nullable String orderBy) {
            this.orderBy = orderBy;
            return this;
        }

        /**
         * Include cursor item in response
         */
        public Builder includeCursor(@Nullable Boolean includeCursor) {
            this.includeCursor = includeCursor;
            return this;
        }

        /**
         * Filter by topic key
         */
        public Builder key(@Nullable String key) {
            this.key = key;
            return this;
        }

        /**
         * Filter by exact context keys, order insensitive (format: "type:id")
         */
        public Builder contextKeys(@Nullable List<String> contextKeys) {
            this.contextKeys = contextKeys;
            return this;
        }

        /**
         * A header for idempotency purposes
         */
        public Builder idempotencyKey(@Nullable String idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }

        public SubscribersControllerListSubscriberTopicsRequest build() {
            return new SubscribersControllerListSubscriberTopicsRequest(
                subscriberId, after, before,
                limit, orderDirection, orderBy,
                includeCursor, key, contextKeys,
                idempotencyKey);
        }

    }
}
