/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations;

import co.novu.models.components.CreateUpdateTopicRequestDto;
import co.novu.utils.SpeakeasyMetadata;
import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class TopicsControllerUpsertTopicRequest {
    /**
     * If true, the request will fail if a topic with the same key already exists
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=failIfExists")
    private Boolean failIfExists;

    /**
     * A header for idempotency purposes
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")
    private String idempotencyKey;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private CreateUpdateTopicRequestDto body;

    @JsonCreator
    public TopicsControllerUpsertTopicRequest(
            @Nullable Boolean failIfExists,
            @Nullable String idempotencyKey,
            @Nonnull CreateUpdateTopicRequestDto body) {
        this.failIfExists = failIfExists;
        this.idempotencyKey = idempotencyKey;
        this.body = Optional.ofNullable(body)
            .orElseThrow(() -> new IllegalArgumentException("body cannot be null"));
    }
    
    public TopicsControllerUpsertTopicRequest(
            @Nonnull CreateUpdateTopicRequestDto body) {
        this(null, null, body);
    }

    /**
     * If true, the request will fail if a topic with the same key already exists
     */
    public Optional<Boolean> failIfExists() {
        return Optional.ofNullable(this.failIfExists);
    }

    /**
     * A header for idempotency purposes
     */
    public Optional<String> idempotencyKey() {
        return Optional.ofNullable(this.idempotencyKey);
    }

    public CreateUpdateTopicRequestDto body() {
        return this.body;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * If true, the request will fail if a topic with the same key already exists
     */
    public TopicsControllerUpsertTopicRequest withFailIfExists(@Nullable Boolean failIfExists) {
        this.failIfExists = failIfExists;
        return this;
    }


    /**
     * A header for idempotency purposes
     */
    public TopicsControllerUpsertTopicRequest withIdempotencyKey(@Nullable String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
    }


    public TopicsControllerUpsertTopicRequest withBody(@Nonnull CreateUpdateTopicRequestDto body) {
        this.body = Utils.checkNotNull(body, "body");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TopicsControllerUpsertTopicRequest other = (TopicsControllerUpsertTopicRequest) o;
        return 
            Utils.enhancedDeepEquals(this.failIfExists, other.failIfExists) &&
            Utils.enhancedDeepEquals(this.idempotencyKey, other.idempotencyKey) &&
            Utils.enhancedDeepEquals(this.body, other.body);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            failIfExists, idempotencyKey, body);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TopicsControllerUpsertTopicRequest.class,
                "failIfExists", failIfExists,
                "idempotencyKey", idempotencyKey,
                "body", body);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Boolean failIfExists;

        private String idempotencyKey;

        private CreateUpdateTopicRequestDto body;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * If true, the request will fail if a topic with the same key already exists
         */
        public Builder failIfExists(@Nullable Boolean failIfExists) {
            this.failIfExists = failIfExists;
            return this;
        }

        /**
         * A header for idempotency purposes
         */
        public Builder idempotencyKey(@Nullable String idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }

        public Builder body(@Nonnull CreateUpdateTopicRequestDto body) {
            this.body = Utils.checkNotNull(body, "body");
            return this;
        }

        public TopicsControllerUpsertTopicRequest build() {
            return new TopicsControllerUpsertTopicRequest(
                failIfExists, idempotencyKey, body);
        }

    }
}
