/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations;

import static co.novu.operations.Operations.RequestOperation;

import co.novu.SDKConfiguration;
import co.novu.operations.TopicsControllerListTopics;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import co.novu.utils.RetryConfig;
import co.novu.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;

public class TopicsControllerListTopicsRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private TopicsControllerListTopicsRequest request;
    private final Options.Builder optionsBuilder;

    public TopicsControllerListTopicsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.optionsBuilder = Options.builder();
    }

    public TopicsControllerListTopicsRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    public TopicsControllerListTopicsRequestBuilder request(@Nonnull TopicsControllerListTopicsRequest request) {
        this.request = Utils.checkNotNull(request, "request");
        return this;
    }

    private TopicsControllerListTopicsRequest _buildRequest() {
        return this.request;
    }
    
    public TopicsControllerListTopicsRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public TopicsControllerListTopicsResponse call() {
        Options options = optionsBuilder.build();
        RequestOperation<TopicsControllerListTopicsRequest, TopicsControllerListTopicsResponse> operation
              = new TopicsControllerListTopics.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
