/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations;

import co.novu.models.components.TranslationGroupDto;
import co.novu.utils.Response;
import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Override;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.Optional;


public class TranslationControllerGetTranslationGroupEndpointResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Translation group details
     */
    private TranslationGroupDto translationGroupDto;

    @JsonCreator
    public TranslationControllerGetTranslationGroupEndpointResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse,
            @Nullable TranslationGroupDto translationGroupDto) {
        this.contentType = Optional.ofNullable(contentType)
            .orElseThrow(() -> new IllegalArgumentException("contentType cannot be null"));
        this.statusCode = statusCode;
        this.rawResponse = Optional.ofNullable(rawResponse)
            .orElseThrow(() -> new IllegalArgumentException("rawResponse cannot be null"));
        this.translationGroupDto = translationGroupDto;
    }
    
    public TranslationControllerGetTranslationGroupEndpointResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse,
            null);
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<InputStream> rawResponse() {
        return this.rawResponse;
    }

    /**
     * Translation group details
     */
    public Optional<TranslationGroupDto> translationGroupDto() {
        return Optional.ofNullable(this.translationGroupDto);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public TranslationControllerGetTranslationGroupEndpointResponse withContentType(@Nonnull String contentType) {
        this.contentType = Utils.checkNotNull(contentType, "contentType");
        return this;
    }


    /**
     * HTTP response status code for this operation
     */
    public TranslationControllerGetTranslationGroupEndpointResponse withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public TranslationControllerGetTranslationGroupEndpointResponse withRawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
        this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
        return this;
    }


    /**
     * Translation group details
     */
    public TranslationControllerGetTranslationGroupEndpointResponse withTranslationGroupDto(@Nullable TranslationGroupDto translationGroupDto) {
        this.translationGroupDto = translationGroupDto;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TranslationControllerGetTranslationGroupEndpointResponse other = (TranslationControllerGetTranslationGroupEndpointResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.translationGroupDto, other.translationGroupDto);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            translationGroupDto);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TranslationControllerGetTranslationGroupEndpointResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "translationGroupDto", translationGroupDto);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private int statusCode;

        private HttpResponse<InputStream> rawResponse;

        private TranslationGroupDto translationGroupDto;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(@Nonnull String contentType) {
            this.contentType = Utils.checkNotNull(contentType, "contentType");
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nonnull HttpResponse<InputStream> rawResponse) {
            this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
            return this;
        }

        /**
         * Translation group details
         */
        public Builder translationGroupDto(@Nullable TranslationGroupDto translationGroupDto) {
            this.translationGroupDto = translationGroupDto;
            return this;
        }

        public TranslationControllerGetTranslationGroupEndpointResponse build() {
            return new TranslationControllerGetTranslationGroupEndpointResponse(
                contentType, statusCode, rawResponse,
                translationGroupDto);
        }

    }
}
