/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations;

import co.novu.models.components.PatchWorkflowDto;
import co.novu.utils.SpeakeasyMetadata;
import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class WorkflowControllerPatchWorkflowRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=workflowId")
    private String workflowId;

    /**
     * A header for idempotency purposes
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=idempotency-key")
    private String idempotencyKey;

    /**
     * Workflow patch details
     */
    @SpeakeasyMetadata("request:mediaType=application/json")
    private PatchWorkflowDto body;

    @JsonCreator
    public WorkflowControllerPatchWorkflowRequest(
            @Nonnull String workflowId,
            @Nullable String idempotencyKey,
            @Nonnull PatchWorkflowDto body) {
        this.workflowId = Optional.ofNullable(workflowId)
            .orElseThrow(() -> new IllegalArgumentException("workflowId cannot be null"));
        this.idempotencyKey = idempotencyKey;
        this.body = Optional.ofNullable(body)
            .orElseThrow(() -> new IllegalArgumentException("body cannot be null"));
    }
    
    public WorkflowControllerPatchWorkflowRequest(
            @Nonnull String workflowId,
            @Nonnull PatchWorkflowDto body) {
        this(workflowId, null, body);
    }

    public String workflowId() {
        return this.workflowId;
    }

    /**
     * A header for idempotency purposes
     */
    public Optional<String> idempotencyKey() {
        return Optional.ofNullable(this.idempotencyKey);
    }

    /**
     * Workflow patch details
     */
    public PatchWorkflowDto body() {
        return this.body;
    }

    public static Builder builder() {
        return new Builder();
    }


    public WorkflowControllerPatchWorkflowRequest withWorkflowId(@Nonnull String workflowId) {
        this.workflowId = Utils.checkNotNull(workflowId, "workflowId");
        return this;
    }


    /**
     * A header for idempotency purposes
     */
    public WorkflowControllerPatchWorkflowRequest withIdempotencyKey(@Nullable String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
    }


    /**
     * Workflow patch details
     */
    public WorkflowControllerPatchWorkflowRequest withBody(@Nonnull PatchWorkflowDto body) {
        this.body = Utils.checkNotNull(body, "body");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WorkflowControllerPatchWorkflowRequest other = (WorkflowControllerPatchWorkflowRequest) o;
        return 
            Utils.enhancedDeepEquals(this.workflowId, other.workflowId) &&
            Utils.enhancedDeepEquals(this.idempotencyKey, other.idempotencyKey) &&
            Utils.enhancedDeepEquals(this.body, other.body);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            workflowId, idempotencyKey, body);
    }
    
    @Override
    public String toString() {
        return Utils.toString(WorkflowControllerPatchWorkflowRequest.class,
                "workflowId", workflowId,
                "idempotencyKey", idempotencyKey,
                "body", body);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String workflowId;

        private String idempotencyKey;

        private PatchWorkflowDto body;

        private Builder() {
          // force use of static builder() method
        }

        public Builder workflowId(@Nonnull String workflowId) {
            this.workflowId = Utils.checkNotNull(workflowId, "workflowId");
            return this;
        }

        /**
         * A header for idempotency purposes
         */
        public Builder idempotencyKey(@Nullable String idempotencyKey) {
            this.idempotencyKey = idempotencyKey;
            return this;
        }

        /**
         * Workflow patch details
         */
        public Builder body(@Nonnull PatchWorkflowDto body) {
            this.body = Utils.checkNotNull(body, "body");
            return this;
        }

        public WorkflowControllerPatchWorkflowRequest build() {
            return new WorkflowControllerPatchWorkflowRequest(
                workflowId, idempotencyKey, body);
        }

    }
}
