/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu;

import static co.novu.operations.Operations.AsyncRequestOperation;

import co.novu.models.components.GeneratePreviewRequestDto;
import co.novu.models.operations.WorkflowControllerGeneratePreviewRequest;
import co.novu.models.operations.async.WorkflowControllerGeneratePreviewRequestBuilder;
import co.novu.models.operations.async.WorkflowControllerGeneratePreviewResponse;
import co.novu.operations.WorkflowControllerGeneratePreview;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;


public class AsyncWorkflowsSteps {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final WorkflowsSteps syncSDK;

    AsyncWorkflowsSteps(WorkflowsSteps syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public WorkflowsSteps sync() {
        return syncSDK;
    }


    /**
     * Generate a step preview
     * 
     * <p>Generates a preview for a specific workflow step by its unique identifier **stepId**
     * 
     * @return The async call builder
     */
    public WorkflowControllerGeneratePreviewRequestBuilder generatePreview() {
        return new WorkflowControllerGeneratePreviewRequestBuilder(sdkConfiguration);
    }

    /**
     * Generate a step preview
     * 
     * <p>Generates a preview for a specific workflow step by its unique identifier **stepId**
     * 
     * @param workflowId 
     * @param stepId 
     * @param body 
     * @return {@code CompletableFuture<WorkflowControllerGeneratePreviewResponse>} - The async response
     */
    public CompletableFuture<WorkflowControllerGeneratePreviewResponse> generatePreview(
            @Nonnull String workflowId, @Nonnull String stepId,
            @Nonnull GeneratePreviewRequestDto body) {
        return generatePreview(
                workflowId, stepId, null,
                body, null);
    }

    /**
     * Generate a step preview
     * 
     * <p>Generates a preview for a specific workflow step by its unique identifier **stepId**
     * 
     * @param workflowId 
     * @param stepId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return {@code CompletableFuture<WorkflowControllerGeneratePreviewResponse>} - The async response
     */
    public CompletableFuture<WorkflowControllerGeneratePreviewResponse> generatePreview(
            @Nonnull String workflowId, @Nonnull String stepId,
            @Nullable String idempotencyKey, @Nonnull GeneratePreviewRequestDto body,
            @Nullable Options options) {
        WorkflowControllerGeneratePreviewRequest request = new WorkflowControllerGeneratePreviewRequest(
                workflowId, stepId, idempotencyKey,
                body);
        AsyncRequestOperation<WorkflowControllerGeneratePreviewRequest, WorkflowControllerGeneratePreviewResponse> operation
              = new WorkflowControllerGeneratePreview.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
