/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu;

import static co.novu.operations.Operations.AsyncRequestOperation;

import co.novu.models.components.CreateChannelConnectionRequestDto;
import co.novu.models.components.UpdateChannelConnectionRequestDto;
import co.novu.models.operations.ChannelConnectionsControllerCreateChannelConnectionRequest;
import co.novu.models.operations.ChannelConnectionsControllerDeleteChannelConnectionRequest;
import co.novu.models.operations.ChannelConnectionsControllerGetChannelConnectionByIdentifierRequest;
import co.novu.models.operations.ChannelConnectionsControllerListChannelConnectionsRequest;
import co.novu.models.operations.ChannelConnectionsControllerUpdateChannelConnectionRequest;
import co.novu.models.operations.async.ChannelConnectionsControllerCreateChannelConnectionRequestBuilder;
import co.novu.models.operations.async.ChannelConnectionsControllerCreateChannelConnectionResponse;
import co.novu.models.operations.async.ChannelConnectionsControllerDeleteChannelConnectionRequestBuilder;
import co.novu.models.operations.async.ChannelConnectionsControllerDeleteChannelConnectionResponse;
import co.novu.models.operations.async.ChannelConnectionsControllerGetChannelConnectionByIdentifierRequestBuilder;
import co.novu.models.operations.async.ChannelConnectionsControllerGetChannelConnectionByIdentifierResponse;
import co.novu.models.operations.async.ChannelConnectionsControllerListChannelConnectionsRequestBuilder;
import co.novu.models.operations.async.ChannelConnectionsControllerListChannelConnectionsResponse;
import co.novu.models.operations.async.ChannelConnectionsControllerUpdateChannelConnectionRequestBuilder;
import co.novu.models.operations.async.ChannelConnectionsControllerUpdateChannelConnectionResponse;
import co.novu.operations.ChannelConnectionsControllerCreateChannelConnection;
import co.novu.operations.ChannelConnectionsControllerDeleteChannelConnection;
import co.novu.operations.ChannelConnectionsControllerGetChannelConnectionByIdentifier;
import co.novu.operations.ChannelConnectionsControllerListChannelConnections;
import co.novu.operations.ChannelConnectionsControllerUpdateChannelConnection;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;


public class AsyncChannelConnections {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final ChannelConnections syncSDK;

    AsyncChannelConnections(ChannelConnections syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public ChannelConnections sync() {
        return syncSDK;
    }


    /**
     * List all channel connections
     * 
     * <p>List all channel connections for a resource.
     * 
     * @return The async call builder
     */
    public ChannelConnectionsControllerListChannelConnectionsRequestBuilder list() {
        return new ChannelConnectionsControllerListChannelConnectionsRequestBuilder(sdkConfiguration);
    }

    /**
     * List all channel connections
     * 
     * <p>List all channel connections for a resource.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<ChannelConnectionsControllerListChannelConnectionsResponse>} - The async response
     */
    public CompletableFuture<ChannelConnectionsControllerListChannelConnectionsResponse> list(@Nonnull ChannelConnectionsControllerListChannelConnectionsRequest request) {
        return list(request, null);
    }

    /**
     * List all channel connections
     * 
     * <p>List all channel connections for a resource.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<ChannelConnectionsControllerListChannelConnectionsResponse>} - The async response
     */
    public CompletableFuture<ChannelConnectionsControllerListChannelConnectionsResponse> list(@Nonnull ChannelConnectionsControllerListChannelConnectionsRequest request, @Nullable Options options) {
        AsyncRequestOperation<ChannelConnectionsControllerListChannelConnectionsRequest, ChannelConnectionsControllerListChannelConnectionsResponse> operation
              = new ChannelConnectionsControllerListChannelConnections.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Create a channel connection
     * 
     * <p>Create a new channel connection for a resource for given integration. Only one channel connection is
     * allowed per resource and integration.
     * 
     * @return The async call builder
     */
    public ChannelConnectionsControllerCreateChannelConnectionRequestBuilder create() {
        return new ChannelConnectionsControllerCreateChannelConnectionRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a channel connection
     * 
     * <p>Create a new channel connection for a resource for given integration. Only one channel connection is
     * allowed per resource and integration.
     * 
     * @param body 
     * @return {@code CompletableFuture<ChannelConnectionsControllerCreateChannelConnectionResponse>} - The async response
     */
    public CompletableFuture<ChannelConnectionsControllerCreateChannelConnectionResponse> create(@Nonnull CreateChannelConnectionRequestDto body) {
        return create(null, body, null);
    }

    /**
     * Create a channel connection
     * 
     * <p>Create a new channel connection for a resource for given integration. Only one channel connection is
     * allowed per resource and integration.
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return {@code CompletableFuture<ChannelConnectionsControllerCreateChannelConnectionResponse>} - The async response
     */
    public CompletableFuture<ChannelConnectionsControllerCreateChannelConnectionResponse> create(
            @Nullable String idempotencyKey, @Nonnull CreateChannelConnectionRequestDto body,
            @Nullable Options options) {
        ChannelConnectionsControllerCreateChannelConnectionRequest request = new ChannelConnectionsControllerCreateChannelConnectionRequest(idempotencyKey, body);
        AsyncRequestOperation<ChannelConnectionsControllerCreateChannelConnectionRequest, ChannelConnectionsControllerCreateChannelConnectionResponse> operation
              = new ChannelConnectionsControllerCreateChannelConnection.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Retrieve a channel connection
     * 
     * <p>Retrieve a specific channel connection by its unique identifier.
     * 
     * @return The async call builder
     */
    public ChannelConnectionsControllerGetChannelConnectionByIdentifierRequestBuilder retrieve() {
        return new ChannelConnectionsControllerGetChannelConnectionByIdentifierRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a channel connection
     * 
     * <p>Retrieve a specific channel connection by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel connection
     * @return {@code CompletableFuture<ChannelConnectionsControllerGetChannelConnectionByIdentifierResponse>} - The async response
     */
    public CompletableFuture<ChannelConnectionsControllerGetChannelConnectionByIdentifierResponse> retrieve(@Nonnull String identifier) {
        return retrieve(identifier, null, null);
    }

    /**
     * Retrieve a channel connection
     * 
     * <p>Retrieve a specific channel connection by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel connection
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return {@code CompletableFuture<ChannelConnectionsControllerGetChannelConnectionByIdentifierResponse>} - The async response
     */
    public CompletableFuture<ChannelConnectionsControllerGetChannelConnectionByIdentifierResponse> retrieve(
            @Nonnull String identifier, @Nullable String idempotencyKey,
            @Nullable Options options) {
        ChannelConnectionsControllerGetChannelConnectionByIdentifierRequest request = new ChannelConnectionsControllerGetChannelConnectionByIdentifierRequest(identifier, idempotencyKey);
        AsyncRequestOperation<ChannelConnectionsControllerGetChannelConnectionByIdentifierRequest, ChannelConnectionsControllerGetChannelConnectionByIdentifierResponse> operation
              = new ChannelConnectionsControllerGetChannelConnectionByIdentifier.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Update a channel connection
     * 
     * <p>Update an existing channel connection by its unique identifier.
     * 
     * @return The async call builder
     */
    public ChannelConnectionsControllerUpdateChannelConnectionRequestBuilder update() {
        return new ChannelConnectionsControllerUpdateChannelConnectionRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a channel connection
     * 
     * <p>Update an existing channel connection by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel connection
     * @param body 
     * @return {@code CompletableFuture<ChannelConnectionsControllerUpdateChannelConnectionResponse>} - The async response
     */
    public CompletableFuture<ChannelConnectionsControllerUpdateChannelConnectionResponse> update(@Nonnull String identifier, @Nonnull UpdateChannelConnectionRequestDto body) {
        return update(
                identifier, null, body,
                null);
    }

    /**
     * Update a channel connection
     * 
     * <p>Update an existing channel connection by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel connection
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return {@code CompletableFuture<ChannelConnectionsControllerUpdateChannelConnectionResponse>} - The async response
     */
    public CompletableFuture<ChannelConnectionsControllerUpdateChannelConnectionResponse> update(
            @Nonnull String identifier, @Nullable String idempotencyKey,
            @Nonnull UpdateChannelConnectionRequestDto body, @Nullable Options options) {
        ChannelConnectionsControllerUpdateChannelConnectionRequest request = new ChannelConnectionsControllerUpdateChannelConnectionRequest(identifier, idempotencyKey, body);
        AsyncRequestOperation<ChannelConnectionsControllerUpdateChannelConnectionRequest, ChannelConnectionsControllerUpdateChannelConnectionResponse> operation
              = new ChannelConnectionsControllerUpdateChannelConnection.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Delete a channel connection
     * 
     * <p>Delete a specific channel connection by its unique identifier.
     * 
     * @return The async call builder
     */
    public ChannelConnectionsControllerDeleteChannelConnectionRequestBuilder delete() {
        return new ChannelConnectionsControllerDeleteChannelConnectionRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a channel connection
     * 
     * <p>Delete a specific channel connection by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel connection
     * @return {@code CompletableFuture<ChannelConnectionsControllerDeleteChannelConnectionResponse>} - The async response
     */
    public CompletableFuture<ChannelConnectionsControllerDeleteChannelConnectionResponse> delete(@Nonnull String identifier) {
        return delete(identifier, null, null);
    }

    /**
     * Delete a channel connection
     * 
     * <p>Delete a specific channel connection by its unique identifier.
     * 
     * @param identifier The unique identifier of the channel connection
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return {@code CompletableFuture<ChannelConnectionsControllerDeleteChannelConnectionResponse>} - The async response
     */
    public CompletableFuture<ChannelConnectionsControllerDeleteChannelConnectionResponse> delete(
            @Nonnull String identifier, @Nullable String idempotencyKey,
            @Nullable Options options) {
        ChannelConnectionsControllerDeleteChannelConnectionRequest request = new ChannelConnectionsControllerDeleteChannelConnectionRequest(identifier, idempotencyKey);
        AsyncRequestOperation<ChannelConnectionsControllerDeleteChannelConnectionRequest, ChannelConnectionsControllerDeleteChannelConnectionResponse> operation
              = new ChannelConnectionsControllerDeleteChannelConnection.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
