/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu;

import static co.novu.operations.Operations.AsyncRequestOperation;

import co.novu.models.operations.SubscribersV1ControllerMarkActionAsSeenRequest;
import co.novu.models.operations.async.SubscribersV1ControllerMarkActionAsSeenRequestBuilder;
import co.novu.models.operations.async.SubscribersV1ControllerMarkActionAsSeenResponse;
import co.novu.operations.SubscribersV1ControllerMarkActionAsSeen;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;


public class AsyncSubscribersMessages1 {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final SubscribersMessages1 syncSDK;

    AsyncSubscribersMessages1(SubscribersMessages1 syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public SubscribersMessages1 sync() {
        return syncSDK;
    }


    /**
     * Update notification action status
     * 
     * <p>Update in-app (inbox) notification's action status by its unique key identifier **messageId** and
     * type field **type**.
     * **type** field can be **primary** or **secondary**
     * 
     * @return The async call builder
     */
    public SubscribersV1ControllerMarkActionAsSeenRequestBuilder updateActionStatus() {
        return new SubscribersV1ControllerMarkActionAsSeenRequestBuilder(sdkConfiguration);
    }

    /**
     * Update notification action status
     * 
     * <p>Update in-app (inbox) notification's action status by its unique key identifier **messageId** and
     * type field **type**.
     * **type** field can be **primary** or **secondary**
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<SubscribersV1ControllerMarkActionAsSeenResponse>} - The async response
     */
    public CompletableFuture<SubscribersV1ControllerMarkActionAsSeenResponse> updateActionStatus(@Nonnull SubscribersV1ControllerMarkActionAsSeenRequest request) {
        return updateActionStatus(request, null);
    }

    /**
     * Update notification action status
     * 
     * <p>Update in-app (inbox) notification's action status by its unique key identifier **messageId** and
     * type field **type**.
     * **type** field can be **primary** or **secondary**
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<SubscribersV1ControllerMarkActionAsSeenResponse>} - The async response
     */
    public CompletableFuture<SubscribersV1ControllerMarkActionAsSeenResponse> updateActionStatus(@Nonnull SubscribersV1ControllerMarkActionAsSeenRequest request, @Nullable Options options) {
        AsyncRequestOperation<SubscribersV1ControllerMarkActionAsSeenRequest, SubscribersV1ControllerMarkActionAsSeenResponse> operation
              = new SubscribersV1ControllerMarkActionAsSeen.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
