/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu;

import static co.novu.operations.Operations.AsyncRequestOperation;

import co.novu.models.operations.SubscribersV1ControllerGetNotificationsFeedRequest;
import co.novu.models.operations.async.SubscribersV1ControllerGetNotificationsFeedRequestBuilder;
import co.novu.models.operations.async.SubscribersV1ControllerGetNotificationsFeedResponse;
import co.novu.operations.SubscribersV1ControllerGetNotificationsFeed;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Deprecated;
import java.util.concurrent.CompletableFuture;


public class AsyncSubscribersNotifications2 {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final SubscribersNotifications2 syncSDK;

    AsyncSubscribersNotifications2(SubscribersNotifications2 syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public SubscribersNotifications2 sync() {
        return syncSDK;
    }


    /**
     * Retrieve subscriber notifications
     * 
     * <p>This API is deprecated, use v2 API instead. Retrieve subscriber in-app notifications by its unique
     * key identifier **subscriberId**.
     * 
     * @return The async call builder
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public SubscribersV1ControllerGetNotificationsFeedRequestBuilder getFeed() {
        return new SubscribersV1ControllerGetNotificationsFeedRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve subscriber notifications
     * 
     * <p>This API is deprecated, use v2 API instead. Retrieve subscriber in-app notifications by its unique
     * key identifier **subscriberId**.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<SubscribersV1ControllerGetNotificationsFeedResponse>} - The async response
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public CompletableFuture<SubscribersV1ControllerGetNotificationsFeedResponse> getFeed(@Nonnull SubscribersV1ControllerGetNotificationsFeedRequest request) {
        return getFeed(request, null);
    }

    /**
     * Retrieve subscriber notifications
     * 
     * <p>This API is deprecated, use v2 API instead. Retrieve subscriber in-app notifications by its unique
     * key identifier **subscriberId**.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return {@code CompletableFuture<SubscribersV1ControllerGetNotificationsFeedResponse>} - The async response
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public CompletableFuture<SubscribersV1ControllerGetNotificationsFeedResponse> getFeed(@Nonnull SubscribersV1ControllerGetNotificationsFeedRequest request, @Nullable Options options) {
        AsyncRequestOperation<SubscribersV1ControllerGetNotificationsFeedRequest, SubscribersV1ControllerGetNotificationsFeedResponse> operation
              = new SubscribersV1ControllerGetNotificationsFeed.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
