/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu;

import static co.novu.operations.Operations.RequestOperation;

import co.novu.models.components.CreateLayoutDto;
import co.novu.models.components.DuplicateLayoutDto;
import co.novu.models.components.LayoutPreviewRequestDto;
import co.novu.models.components.UpdateLayoutDto;
import co.novu.models.operations.LayoutsControllerCreateRequest;
import co.novu.models.operations.LayoutsControllerCreateRequestBuilder;
import co.novu.models.operations.LayoutsControllerCreateResponse;
import co.novu.models.operations.LayoutsControllerDeleteRequest;
import co.novu.models.operations.LayoutsControllerDeleteRequestBuilder;
import co.novu.models.operations.LayoutsControllerDeleteResponse;
import co.novu.models.operations.LayoutsControllerDuplicateRequest;
import co.novu.models.operations.LayoutsControllerDuplicateRequestBuilder;
import co.novu.models.operations.LayoutsControllerDuplicateResponse;
import co.novu.models.operations.LayoutsControllerGeneratePreviewRequest;
import co.novu.models.operations.LayoutsControllerGeneratePreviewRequestBuilder;
import co.novu.models.operations.LayoutsControllerGeneratePreviewResponse;
import co.novu.models.operations.LayoutsControllerGetRequest;
import co.novu.models.operations.LayoutsControllerGetRequestBuilder;
import co.novu.models.operations.LayoutsControllerGetResponse;
import co.novu.models.operations.LayoutsControllerGetUsageRequest;
import co.novu.models.operations.LayoutsControllerGetUsageRequestBuilder;
import co.novu.models.operations.LayoutsControllerGetUsageResponse;
import co.novu.models.operations.LayoutsControllerListRequest;
import co.novu.models.operations.LayoutsControllerListRequestBuilder;
import co.novu.models.operations.LayoutsControllerListResponse;
import co.novu.models.operations.LayoutsControllerUpdateRequest;
import co.novu.models.operations.LayoutsControllerUpdateRequestBuilder;
import co.novu.models.operations.LayoutsControllerUpdateResponse;
import co.novu.operations.LayoutsControllerCreate;
import co.novu.operations.LayoutsControllerDelete;
import co.novu.operations.LayoutsControllerDuplicate;
import co.novu.operations.LayoutsControllerGeneratePreview;
import co.novu.operations.LayoutsControllerGet;
import co.novu.operations.LayoutsControllerGetUsage;
import co.novu.operations.LayoutsControllerList;
import co.novu.operations.LayoutsControllerUpdate;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;

/**
 * Layouts are reusable wrappers for your email notifications.
 * 
 * <p><a href="https://docs.novu.co/platform/workflow/layouts">https://docs.novu.co/platform/workflow/layouts</a>
 */
public class Layouts {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncLayouts asyncSDK;

    Layouts(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncLayouts(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncLayouts async() {
        return asyncSDK;
    }

    /**
     * Create a layout
     * 
     * <p>Creates a new layout in the Novu Cloud environment
     * 
     * @return The call builder
     */
    public LayoutsControllerCreateRequestBuilder create() {
        return new LayoutsControllerCreateRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a layout
     * 
     * <p>Creates a new layout in the Novu Cloud environment
     * 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerCreateResponse create(@Nonnull CreateLayoutDto body) {
        return create(null, body, null);
    }

    /**
     * Create a layout
     * 
     * <p>Creates a new layout in the Novu Cloud environment
     * 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerCreateResponse create(
            @Nullable String idempotencyKey, @Nonnull CreateLayoutDto body,
            @Nullable Options options) {
        LayoutsControllerCreateRequest request = new LayoutsControllerCreateRequest(idempotencyKey, body);
        RequestOperation<LayoutsControllerCreateRequest, LayoutsControllerCreateResponse> operation
              = new LayoutsControllerCreate.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List all layouts
     * 
     * <p>Retrieves a list of layouts with optional filtering and pagination
     * 
     * @return The call builder
     */
    public LayoutsControllerListRequestBuilder list() {
        return new LayoutsControllerListRequestBuilder(sdkConfiguration);
    }

    /**
     * List all layouts
     * 
     * <p>Retrieves a list of layouts with optional filtering and pagination
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerListResponse list(@Nonnull LayoutsControllerListRequest request) {
        return list(request, null);
    }

    /**
     * List all layouts
     * 
     * <p>Retrieves a list of layouts with optional filtering and pagination
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerListResponse list(@Nonnull LayoutsControllerListRequest request, @Nullable Options options) {
        RequestOperation<LayoutsControllerListRequest, LayoutsControllerListResponse> operation
              = new LayoutsControllerList.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update a layout
     * 
     * <p>Updates the details of an existing layout, here **layoutId** is the identifier of the layout
     * 
     * @return The call builder
     */
    public LayoutsControllerUpdateRequestBuilder update() {
        return new LayoutsControllerUpdateRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a layout
     * 
     * <p>Updates the details of an existing layout, here **layoutId** is the identifier of the layout
     * 
     * @param layoutId 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerUpdateResponse update(@Nonnull String layoutId, @Nonnull UpdateLayoutDto body) {
        return update(layoutId, null, body,
            null);
    }

    /**
     * Update a layout
     * 
     * <p>Updates the details of an existing layout, here **layoutId** is the identifier of the layout
     * 
     * @param layoutId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerUpdateResponse update(
            @Nonnull String layoutId, @Nullable String idempotencyKey,
            @Nonnull UpdateLayoutDto body, @Nullable Options options) {
        LayoutsControllerUpdateRequest request = new LayoutsControllerUpdateRequest(layoutId, idempotencyKey, body);
        RequestOperation<LayoutsControllerUpdateRequest, LayoutsControllerUpdateResponse> operation
              = new LayoutsControllerUpdate.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve a layout
     * 
     * <p>Fetches details of a specific layout by its unique identifier **layoutId**
     * 
     * @return The call builder
     */
    public LayoutsControllerGetRequestBuilder get() {
        return new LayoutsControllerGetRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a layout
     * 
     * <p>Fetches details of a specific layout by its unique identifier **layoutId**
     * 
     * @param layoutId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerGetResponse get(@Nonnull String layoutId) {
        return get(layoutId, null, null);
    }

    /**
     * Retrieve a layout
     * 
     * <p>Fetches details of a specific layout by its unique identifier **layoutId**
     * 
     * @param layoutId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerGetResponse get(
            @Nonnull String layoutId, @Nullable String idempotencyKey,
            @Nullable Options options) {
        LayoutsControllerGetRequest request = new LayoutsControllerGetRequest(layoutId, idempotencyKey);
        RequestOperation<LayoutsControllerGetRequest, LayoutsControllerGetResponse> operation
              = new LayoutsControllerGet.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete a layout
     * 
     * <p>Removes a specific layout by its unique identifier **layoutId**
     * 
     * @return The call builder
     */
    public LayoutsControllerDeleteRequestBuilder delete() {
        return new LayoutsControllerDeleteRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a layout
     * 
     * <p>Removes a specific layout by its unique identifier **layoutId**
     * 
     * @param layoutId The unique identifier of the layout
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerDeleteResponse delete(@Nonnull String layoutId) {
        return delete(layoutId, null, null);
    }

    /**
     * Delete a layout
     * 
     * <p>Removes a specific layout by its unique identifier **layoutId**
     * 
     * @param layoutId The unique identifier of the layout
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerDeleteResponse delete(
            @Nonnull String layoutId, @Nullable String idempotencyKey,
            @Nullable Options options) {
        LayoutsControllerDeleteRequest request = new LayoutsControllerDeleteRequest(layoutId, idempotencyKey);
        RequestOperation<LayoutsControllerDeleteRequest, LayoutsControllerDeleteResponse> operation
              = new LayoutsControllerDelete.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Duplicate a layout
     * 
     * <p>Duplicates a layout by its unique identifier **layoutId**. This will create a new layout with the
     * content of the original layout.
     * 
     * @return The call builder
     */
    public LayoutsControllerDuplicateRequestBuilder duplicate() {
        return new LayoutsControllerDuplicateRequestBuilder(sdkConfiguration);
    }

    /**
     * Duplicate a layout
     * 
     * <p>Duplicates a layout by its unique identifier **layoutId**. This will create a new layout with the
     * content of the original layout.
     * 
     * @param layoutId 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerDuplicateResponse duplicate(@Nonnull String layoutId, @Nonnull DuplicateLayoutDto body) {
        return duplicate(layoutId, null, body,
            null);
    }

    /**
     * Duplicate a layout
     * 
     * <p>Duplicates a layout by its unique identifier **layoutId**. This will create a new layout with the
     * content of the original layout.
     * 
     * @param layoutId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerDuplicateResponse duplicate(
            @Nonnull String layoutId, @Nullable String idempotencyKey,
            @Nonnull DuplicateLayoutDto body, @Nullable Options options) {
        LayoutsControllerDuplicateRequest request = new LayoutsControllerDuplicateRequest(layoutId, idempotencyKey, body);
        RequestOperation<LayoutsControllerDuplicateRequest, LayoutsControllerDuplicateResponse> operation
              = new LayoutsControllerDuplicate.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Generate layout preview
     * 
     * <p>Generates a preview for a layout by its unique identifier **layoutId**
     * 
     * @return The call builder
     */
    public LayoutsControllerGeneratePreviewRequestBuilder generatePreview() {
        return new LayoutsControllerGeneratePreviewRequestBuilder(sdkConfiguration);
    }

    /**
     * Generate layout preview
     * 
     * <p>Generates a preview for a layout by its unique identifier **layoutId**
     * 
     * @param layoutId 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerGeneratePreviewResponse generatePreview(@Nonnull String layoutId, @Nonnull LayoutPreviewRequestDto body) {
        return generatePreview(layoutId, null, body,
            null);
    }

    /**
     * Generate layout preview
     * 
     * <p>Generates a preview for a layout by its unique identifier **layoutId**
     * 
     * @param layoutId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerGeneratePreviewResponse generatePreview(
            @Nonnull String layoutId, @Nullable String idempotencyKey,
            @Nonnull LayoutPreviewRequestDto body, @Nullable Options options) {
        LayoutsControllerGeneratePreviewRequest request = new LayoutsControllerGeneratePreviewRequest(layoutId, idempotencyKey, body);
        RequestOperation<LayoutsControllerGeneratePreviewRequest, LayoutsControllerGeneratePreviewResponse> operation
              = new LayoutsControllerGeneratePreview.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get layout usage
     * 
     * <p>Retrieves information about workflows that use the specified layout by its unique identifier
     * **layoutId**
     * 
     * @return The call builder
     */
    public LayoutsControllerGetUsageRequestBuilder getUsage() {
        return new LayoutsControllerGetUsageRequestBuilder(sdkConfiguration);
    }

    /**
     * Get layout usage
     * 
     * <p>Retrieves information about workflows that use the specified layout by its unique identifier
     * **layoutId**
     * 
     * @param layoutId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerGetUsageResponse getUsage(@Nonnull String layoutId) {
        return getUsage(layoutId, null, null);
    }

    /**
     * Get layout usage
     * 
     * <p>Retrieves information about workflows that use the specified layout by its unique identifier
     * **layoutId**
     * 
     * @param layoutId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public LayoutsControllerGetUsageResponse getUsage(
            @Nonnull String layoutId, @Nullable String idempotencyKey,
            @Nullable Options options) {
        LayoutsControllerGetUsageRequest request = new LayoutsControllerGetUsageRequest(layoutId, idempotencyKey);
        RequestOperation<LayoutsControllerGetUsageRequest, LayoutsControllerGetUsageResponse> operation
              = new LayoutsControllerGetUsage.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
