/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu;

import static co.novu.operations.Operations.RequestOperation;

import co.novu.models.operations.WorkflowControllerGetWorkflowStepDataRequest;
import co.novu.models.operations.WorkflowControllerGetWorkflowStepDataRequestBuilder;
import co.novu.models.operations.WorkflowControllerGetWorkflowStepDataResponse;
import co.novu.operations.WorkflowControllerGetWorkflowStepData;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;


public class Steps {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncSteps asyncSDK;

    Steps(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncSteps(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncSteps async() {
        return asyncSDK;
    }

    /**
     * Retrieve workflow step
     * 
     * <p>Retrieves data for a specific step in a workflow
     * 
     * @return The call builder
     */
    public WorkflowControllerGetWorkflowStepDataRequestBuilder get() {
        return new WorkflowControllerGetWorkflowStepDataRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve workflow step
     * 
     * <p>Retrieves data for a specific step in a workflow
     * 
     * @param workflowId 
     * @param stepId 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerGetWorkflowStepDataResponse get(@Nonnull String workflowId, @Nonnull String stepId) {
        return get(workflowId, stepId, null,
            null);
    }

    /**
     * Retrieve workflow step
     * 
     * <p>Retrieves data for a specific step in a workflow
     * 
     * @param workflowId 
     * @param stepId 
     * @param idempotencyKey A header for idempotency purposes
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public WorkflowControllerGetWorkflowStepDataResponse get(
            @Nonnull String workflowId, @Nonnull String stepId,
            @Nullable String idempotencyKey, @Nullable Options options) {
        WorkflowControllerGetWorkflowStepDataRequest request = new WorkflowControllerGetWorkflowStepDataRequest(workflowId, stepId, idempotencyKey);
        RequestOperation<WorkflowControllerGetWorkflowStepDataRequest, WorkflowControllerGetWorkflowStepDataResponse> operation
              = new WorkflowControllerGetWorkflowStepData.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
