/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu;

import static co.novu.operations.Operations.RequestOperation;

import co.novu.models.components.UpdateSubscriberOnlineFlagRequestDto;
import co.novu.models.operations.SubscribersV1ControllerUpdateSubscriberOnlineFlagRequest;
import co.novu.models.operations.SubscribersV1ControllerUpdateSubscriberOnlineFlagRequestBuilder;
import co.novu.models.operations.SubscribersV1ControllerUpdateSubscriberOnlineFlagResponse;
import co.novu.operations.SubscribersV1ControllerUpdateSubscriberOnlineFlag;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;


public class SubscribersProperties {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncSubscribersProperties asyncSDK;

    SubscribersProperties(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncSubscribersProperties(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncSubscribersProperties async() {
        return asyncSDK;
    }

    /**
     * Update subscriber online status
     * 
     * <p>Update the subscriber online status by its unique key identifier **subscriberId**
     * 
     * @return The call builder
     */
    public SubscribersV1ControllerUpdateSubscriberOnlineFlagRequestBuilder updateOnlineStatus() {
        return new SubscribersV1ControllerUpdateSubscriberOnlineFlagRequestBuilder(sdkConfiguration);
    }

    /**
     * Update subscriber online status
     * 
     * <p>Update the subscriber online status by its unique key identifier **subscriberId**
     * 
     * @param subscriberId 
     * @param body 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerUpdateSubscriberOnlineFlagResponse updateOnlineStatus(@Nonnull String subscriberId, @Nonnull UpdateSubscriberOnlineFlagRequestDto body) {
        return updateOnlineStatus(subscriberId, null, body,
            null);
    }

    /**
     * Update subscriber online status
     * 
     * <p>Update the subscriber online status by its unique key identifier **subscriberId**
     * 
     * @param subscriberId 
     * @param idempotencyKey A header for idempotency purposes
     * @param body 
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public SubscribersV1ControllerUpdateSubscriberOnlineFlagResponse updateOnlineStatus(
            @Nonnull String subscriberId, @Nullable String idempotencyKey,
            @Nonnull UpdateSubscriberOnlineFlagRequestDto body, @Nullable Options options) {
        SubscribersV1ControllerUpdateSubscriberOnlineFlagRequest request = new SubscribersV1ControllerUpdateSubscriberOnlineFlagRequest(subscriberId, idempotencyKey, body);
        RequestOperation<SubscribersV1ControllerUpdateSubscriberOnlineFlagRequest, SubscribersV1ControllerUpdateSubscriberOnlineFlagResponse> operation
              = new SubscribersV1ControllerUpdateSubscriberOnlineFlag.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
