workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    novu-OAS:
        inputs:
            - location: https://api.novu.co/openapi.sdk.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/novu/novu/novu-oas
targets:
    novu:
        target: java
        source: novu-OAS
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/novu/novu/novu-oas-java-code-samples
            blocking: false
