/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations.async;

import static co.novu.operations.Operations.AsyncRequestOperation;

import co.novu.SDKConfiguration;
import co.novu.models.operations.ContextsControllerGetContextRequest;
import co.novu.operations.ContextsControllerGetContext;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import co.novu.utils.RetryConfig;
import co.novu.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class ContextsControllerGetContextRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final ContextsControllerGetContextRequest.Builder pojoBuilder;
    private ContextsControllerGetContextRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public ContextsControllerGetContextRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = ContextsControllerGetContextRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public ContextsControllerGetContextRequestBuilder id(@Nonnull String id) {
        this.pojoBuilder.id(id);
        this._setterCalled = true;
        return this;
    }

    public ContextsControllerGetContextRequestBuilder type(@Nonnull String type) {
        this.pojoBuilder.type(type);
        this._setterCalled = true;
        return this;
    }

    public ContextsControllerGetContextRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public ContextsControllerGetContextRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private ContextsControllerGetContextRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public ContextsControllerGetContextRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<ContextsControllerGetContextResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<ContextsControllerGetContextRequest, ContextsControllerGetContextResponse> operation
              = new ContextsControllerGetContext.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
