/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations.async;

import static co.novu.operations.Operations.AsyncRequestOperation;

import co.novu.SDKConfiguration;
import co.novu.models.operations.DomainsControllerGetDomainRouteRequest;
import co.novu.operations.DomainsControllerGetDomainRoute;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import co.novu.utils.RetryConfig;
import co.novu.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class DomainsControllerGetDomainRouteRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final DomainsControllerGetDomainRouteRequest.Builder pojoBuilder;
    private DomainsControllerGetDomainRouteRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public DomainsControllerGetDomainRouteRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = DomainsControllerGetDomainRouteRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public DomainsControllerGetDomainRouteRequestBuilder domain(@Nonnull String domain) {
        this.pojoBuilder.domain(domain);
        this._setterCalled = true;
        return this;
    }

    public DomainsControllerGetDomainRouteRequestBuilder address(@Nonnull String address) {
        this.pojoBuilder.address(address);
        this._setterCalled = true;
        return this;
    }

    public DomainsControllerGetDomainRouteRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public DomainsControllerGetDomainRouteRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private DomainsControllerGetDomainRouteRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public DomainsControllerGetDomainRouteRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<DomainsControllerGetDomainRouteResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<DomainsControllerGetDomainRouteRequest, DomainsControllerGetDomainRouteResponse> operation
              = new DomainsControllerGetDomainRoute.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
