/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations.async;

import co.novu.models.components.DomainResponseDto;
import co.novu.utils.AsyncResponse;
import co.novu.utils.Blob;
import co.novu.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Override;
import java.lang.String;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Map;
import java.util.Optional;


public class DomainsControllerVerifyDomainResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * OK
     */
    private DomainResponseDto domainResponseDto;


    private Map<String, List<String>> headers;

    @JsonCreator
    public DomainsControllerVerifyDomainResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<Blob> rawResponse,
            @Nullable DomainResponseDto domainResponseDto,
            @Nonnull Map<String, List<String>> headers) {
        headers = Utils.emptyMapIfNull(headers);
        this.contentType = Optional.ofNullable(contentType)
            .orElseThrow(() -> new IllegalArgumentException("contentType cannot be null"));
        this.statusCode = statusCode;
        this.rawResponse = Optional.ofNullable(rawResponse)
            .orElseThrow(() -> new IllegalArgumentException("rawResponse cannot be null"));
        this.domainResponseDto = domainResponseDto;
        this.headers = Optional.ofNullable(headers)
            .orElseThrow(() -> new IllegalArgumentException("headers cannot be null"));
    }
    
    public DomainsControllerVerifyDomainResponse(
            @Nonnull String contentType,
            int statusCode,
            @Nonnull HttpResponse<Blob> rawResponse,
            @Nonnull Map<String, List<String>> headers) {
        this(contentType, statusCode, rawResponse,
            null, headers);
    }

    /**
     * HTTP response content type for this operation
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    public int statusCode() {
        return this.statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public HttpResponse<Blob> rawResponse() {
        return this.rawResponse;
    }

    /**
     * OK
     */
    public Optional<DomainResponseDto> domainResponseDto() {
        return Optional.ofNullable(this.domainResponseDto);
    }

    public Map<String, List<String>> headers() {
        return this.headers;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public DomainsControllerVerifyDomainResponse withContentType(@Nonnull String contentType) {
        this.contentType = Utils.checkNotNull(contentType, "contentType");
        return this;
    }


    /**
     * HTTP response status code for this operation
     */
    public DomainsControllerVerifyDomainResponse withStatusCode(int statusCode) {
        this.statusCode = statusCode;
        return this;
    }


    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public DomainsControllerVerifyDomainResponse withRawResponse(@Nonnull HttpResponse<Blob> rawResponse) {
        this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
        return this;
    }


    /**
     * OK
     */
    public DomainsControllerVerifyDomainResponse withDomainResponseDto(@Nullable DomainResponseDto domainResponseDto) {
        this.domainResponseDto = domainResponseDto;
        return this;
    }


    public DomainsControllerVerifyDomainResponse withHeaders(@Nonnull Map<String, List<String>> headers) {
        this.headers = Utils.checkNotNull(headers, "headers");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DomainsControllerVerifyDomainResponse other = (DomainsControllerVerifyDomainResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.domainResponseDto, other.domainResponseDto) &&
            Utils.enhancedDeepEquals(this.headers, other.headers);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            domainResponseDto, headers);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DomainsControllerVerifyDomainResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "domainResponseDto", domainResponseDto,
                "headers", headers);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private int statusCode;

        private HttpResponse<Blob> rawResponse;

        private DomainResponseDto domainResponseDto;

        private Map<String, List<String>> headers;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(@Nonnull String contentType) {
            this.contentType = Utils.checkNotNull(contentType, "contentType");
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(@Nonnull HttpResponse<Blob> rawResponse) {
            this.rawResponse = Utils.checkNotNull(rawResponse, "rawResponse");
            return this;
        }

        /**
         * OK
         */
        public Builder domainResponseDto(@Nullable DomainResponseDto domainResponseDto) {
            this.domainResponseDto = domainResponseDto;
            return this;
        }

        public Builder headers(@Nonnull Map<String, List<String>> headers) {
            this.headers = Utils.checkNotNull(headers, "headers");
            return this;
        }

        public DomainsControllerVerifyDomainResponse build() {
            return new DomainsControllerVerifyDomainResponse(
                contentType, statusCode, rawResponse,
                domainResponseDto, headers);
        }

    }
}
