/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations.async;

import static co.novu.operations.Operations.AsyncRequestOperation;

import co.novu.SDKConfiguration;
import co.novu.models.components.TriggerEventRequestDto;
import co.novu.models.operations.EventsControllerTriggerRequest;
import co.novu.operations.EventsControllerTrigger;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import co.novu.utils.RetryConfig;
import co.novu.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class EventsControllerTriggerRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final EventsControllerTriggerRequest.Builder pojoBuilder;
    private EventsControllerTriggerRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public EventsControllerTriggerRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = EventsControllerTriggerRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public EventsControllerTriggerRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public EventsControllerTriggerRequestBuilder body(@Nonnull TriggerEventRequestDto body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public EventsControllerTriggerRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private EventsControllerTriggerRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public EventsControllerTriggerRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<EventsControllerTriggerResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<EventsControllerTriggerRequest, EventsControllerTriggerResponse> operation
              = new EventsControllerTrigger.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
