/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations.async;

import static co.novu.operations.Operations.AsyncRequestOperation;

import co.novu.SDKConfiguration;
import co.novu.models.operations.IntegrationsControllerSetIntegrationAsPrimaryRequest;
import co.novu.operations.IntegrationsControllerSetIntegrationAsPrimary;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import co.novu.utils.RetryConfig;
import co.novu.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class IntegrationsControllerSetIntegrationAsPrimaryRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final IntegrationsControllerSetIntegrationAsPrimaryRequest.Builder pojoBuilder;
    private IntegrationsControllerSetIntegrationAsPrimaryRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public IntegrationsControllerSetIntegrationAsPrimaryRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = IntegrationsControllerSetIntegrationAsPrimaryRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public IntegrationsControllerSetIntegrationAsPrimaryRequestBuilder integrationId(@Nonnull String integrationId) {
        this.pojoBuilder.integrationId(integrationId);
        this._setterCalled = true;
        return this;
    }

    public IntegrationsControllerSetIntegrationAsPrimaryRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public IntegrationsControllerSetIntegrationAsPrimaryRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private IntegrationsControllerSetIntegrationAsPrimaryRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public IntegrationsControllerSetIntegrationAsPrimaryRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<IntegrationsControllerSetIntegrationAsPrimaryResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<IntegrationsControllerSetIntegrationAsPrimaryRequest, IntegrationsControllerSetIntegrationAsPrimaryResponse> operation
              = new IntegrationsControllerSetIntegrationAsPrimary.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
