/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package co.novu.models.operations.async;

import static co.novu.operations.Operations.AsyncRequestOperation;

import co.novu.SDKConfiguration;
import co.novu.models.components.UpdateSubscriberChannelRequestDto;
import co.novu.models.operations.SubscribersV1ControllerUpdateSubscriberChannelRequest;
import co.novu.operations.SubscribersV1ControllerUpdateSubscriberChannel;
import co.novu.utils.Headers;
import co.novu.utils.Options;
import co.novu.utils.RetryConfig;
import co.novu.utils.Utils;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class SubscribersV1ControllerUpdateSubscriberChannelRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final SubscribersV1ControllerUpdateSubscriberChannelRequest.Builder pojoBuilder;
    private SubscribersV1ControllerUpdateSubscriberChannelRequest request;
    private final Options.Builder optionsBuilder;
    private boolean _setterCalled;

    public SubscribersV1ControllerUpdateSubscriberChannelRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = SubscribersV1ControllerUpdateSubscriberChannelRequest.builder();
        this.optionsBuilder = Options.builder();
    }

    public SubscribersV1ControllerUpdateSubscriberChannelRequestBuilder subscriberId(@Nonnull String subscriberId) {
        this.pojoBuilder.subscriberId(subscriberId);
        this._setterCalled = true;
        return this;
    }

    public SubscribersV1ControllerUpdateSubscriberChannelRequestBuilder idempotencyKey(@Nullable String idempotencyKey) {
        this.pojoBuilder.idempotencyKey(idempotencyKey);
        this._setterCalled = true;
        return this;
    }

    public SubscribersV1ControllerUpdateSubscriberChannelRequestBuilder body(@Nonnull UpdateSubscriberChannelRequestDto body) {
        this.pojoBuilder.body(body);
        this._setterCalled = true;
        return this;
    }

    public SubscribersV1ControllerUpdateSubscriberChannelRequestBuilder retryConfig(RetryConfig retryConfig) {
        this.optionsBuilder.retryConfig(retryConfig);
        return this;
    }

    private SubscribersV1ControllerUpdateSubscriberChannelRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    
    public SubscribersV1ControllerUpdateSubscriberChannelRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public CompletableFuture<SubscribersV1ControllerUpdateSubscriberChannelResponse> call() {
        Options options = optionsBuilder.build();
        AsyncRequestOperation<SubscribersV1ControllerUpdateSubscriberChannelRequest, SubscribersV1ControllerUpdateSubscriberChannelResponse> operation
              = new SubscribersV1ControllerUpdateSubscriberChannel.Async(
                                    sdkConfiguration, options, sdkConfiguration.retryScheduler(),
                                    _headers);
        return operation.doRequest(this._buildRequest())
            .thenCompose(operation::handleResponse);
    }
}
